### ISSUE TITLE
Suggestion: WordPress Integration

### ISSUE THREAD

**Issue by site101** [pH7Software/pH7-Social-Dating-CMS#1092]
Along with the much anticipated self-updating script, for version 18 I would like to suggest a WordPress hook that will allow existing WP members to have access to the dating site.

**Comment by pH-7** [comment]
Hi @site101

Thank you for the suggestion!

However, having a WP integration isn't a plan. pH7Builder is design to work by itself (standalone) and it wouldn't make much sense to have it to depend through a WP plugin. 

You can still have a Wordpress site on a different (sub) domain URL, but it won't be integrated into it.

You can however ask a designer (on Fiverr, UpWork, ...) to create a very similar design for your Wordpress site, so that both your pH7Builder dating website and Wordpress site will look alike and users won't see it like it's integrated to each other.


Hope it helps!


Have a great day!
