### ISSUE TITLE
Membershiplist Error 500 (Admin Panel)

### ISSUE THREAD

**Issue by Pascal1233** [pH7Software/pH7-Social-Dating-CMS#1169]
Hi there, hoping for help here.
As soon as i want to add a Membership or try to open the Membership-List im getting these Error.
I tried to display the Error for more information but it doesnt work as well.

Thanks already for trying to help.

![membership](https://github.com/user-attachments/assets/62efae60-d8e9-48b5-8bde-a7f7a73a5e60)

**Comment by pH-7** [comment]
Hi @Pascal1233 

This is due to an internal error. To understand the cause, could you see to enable the development mode to show the PHP errors (exceptions) on the page?

To do so, please edit `_protected/app/configs/config.ini`, and replace `environment = production` to `environment = development`, and then save it.

Then, go back to your web browser and  refresh the page.
From there, you will normally see an explanatory PHP error message. Let me know the error(s) you will see from there.

**Comment by pH-7** [comment]
Hi @Pascal1233 

This is due to an internal error. If you can't enable the debugging mode like what you said, then, can you try to edit `_protected/app/configs/config.ini`, and replace `environment = production` to `environment = development`, and then save it. If you can't save the `config.ini` file, you might have to change the UNIX permission for the file (google and chatgpt it if needed).

Then, go back to your web browser and  refresh the page.
From there, you will normally see an explanatory PHP error message and the reason why you are getting this. Let me know the error(s) you will see from there.

I hope it will help! 🙂 


Have a great day ahead
