### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Worldwide7477** [pH7Software/pH7-Social-Dating-CMS#121]
Checking out this great project, but i have found for some reason after installing i just get a white screen?

Any thoughts on this.

**Comment by pH-7** [comment]
Hi there!

It seems you have an internal error. Can you please set the development mode in order to see the error message.

You can set the development mode by editing `/_protected/app/configs/config.ini` file.
Replace "environment = production" by "environment = development" at the beginning of the file and then save it.

Then, refresh the page and post your error here.

**Comment by pH-7** [comment]
Hi again @Worldwide7477 
Like I said, this error is from your environment. Something is wrong from your web hosting. 
It means I can't reproduce the error for you and help you. So, please set the development mode (like I said above) and give the PHP error you get.

**Comment by Worldwide7477** [comment]
Thanks PH-7 i'm redoing my server as we speak and will post again if there is a problem after i'm done thanks for the reply, and sorry for my late reply.

**Comment by Worldwide7477** [comment]
Here's what i have when installing.


Warning: require_once(/home/markedout/public_html/_protected/vendor/autoload.php): failed to open stream: No such file or directory in /home/markedout/public_html/_protected/framework/Loader/Autoloader.php on line 58

Fatal error: require_once(): Failed opening required '/home/markedout/public_html/_protected/vendor/autoload.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/markedout/public_html/_protected/framework/Loader/Autoloader.php on line 58

**Comment by pH-7** [comment]
Well, on github, I don't include the third-party libraries (since it doesn't to have them on the repo).


If you download pH7CMS from Github, you have to follow those instructions https://github.com/pH7Software/pH7-Social-Dating-CMS#installation

Apparently, you didn't and didn't run `composer install` in the repo in order to install the dependencies.


Another solution is to directly download pH7CMS 7.0 from Sourceforge (where it has already the dependencies) -> https://sourceforge.net/projects/ph7socialdating/

Hope this helps!

**Comment by pH-7** [comment]
No problem. You're more than welcome! ;)
