### ISSUE TITLE
安装错误，显示无法连接网络

### ISSUE THREAD

**Issue by junshenshi** [pH7Software/pH7-Social-Dating-CMS#132]
http://ph7.niyuanit.com

**Comment by pH-7** [comment]
Make sure there is no firewall that blocks external websites. pH7CMS checks if it can reach one of the following domains `google.com, facebook.com, twitter.com, yahoo.com or bing.com` in order to know if it has internet.
pH7CMS needs internet since it uses JS, ... libraries located on remote CDN servers, etc.
