### ISSUE TITLE
Table 'ph7cms.ph7_settings' doesn't exist

### ISSUE THREAD

**Issue by jv95** [pH7Software/pH7-Social-Dating-CMS#136]
Hello,
I am trying to install ph7cms I am getting this error.
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ph7cms.ph7_settings' doesn't exist`
Where is the problem? I am running it on localhost. WAMP is running and everything seems fine. I am really lost now and I need your help. I also tried to download ph7cms from sourceforge and from github. Both versions throwing this error. Any ideas? Where do I get this table? Am I doing something wrong?

**Comment by jv95** [comment]
Problem fixed by using XAMPP.

**Comment by pH-7** [comment]
BTW, I think I found the cause of your problem.
https://stackoverflow.com/questions/2659684/why-my-tables-names-are-converted-into-lowercase-in-phpmyadmin

If you check your tables, there are chances that your table names were converted to lowercase. This won't work since the table names are different. You will have to disable that option. See my link above.

Hope that helps! Again, have a great day! 😺

**Comment by pH-7** [comment]
@jv95 FYI, in the next further version (v12), all database tables will be in lowercase by default. 

I really hope that will help you ;)
