### ISSUE TITLE
Installation seems to have issue

### ISSUE THREAD

**Issue by Calvinism** [pH7Software/pH7-Social-Dating-CMS#154]
I installed the codes on my server running windows WAMP. https://dating.r2dy.com/
Something seems to be missing. Is this the normal view or I have something missing?

**Comment by pH-7** [comment]
No, it's not normal.
I checked your css files view-source:https://dating.r2dy.com/asset/gzip/?t=css&d=static/css/&f=bootstrap.css,bootstrap_customize.css,animate.css and there are empty.

It seems you have issues with cURL. Maybe your server blocks external websites. Basically, pH7CMS will fetch all CSS/JS files externally with cURL. But, for some reason, something blocked it on your website. If you use a sharing hosting, please contact your web hosting asking them to investigate this issue concerning cURL and make sure there are no security software that might block cURL or external websites.

Once this is fixed, please delete all static files cached in `/_protected/data/cache/pH7_static/*`, otherwise the static files (css/js) won't be updated.


Hope that helps!

**P.S. Don't forget to "Star" the project in order to get updates.**

Good luck.

**Comment by Calvinism** [comment]
I'm running on windows server WAMP php 5.6. Do I need to run it with php 7? Could this be the cause for the issue?

**Comment by Calvinism** [comment]
It works now after loading from localhost. That means I need to load the web from localhost the first time when the cache is cleared. Loading from domain will not work.

**Comment by Calvinism** [comment]
Does that mean I need to load all the pages whenever I clear the cache? I can load the page using localhost but not from domain. If the cache need to refresh, how can I maintain the page without using localhost?
