### ISSUE TITLE
Unable to write to log file  by upload  photos or  making fake profiles

### ISSUE THREAD

**Issue by dplay74** [pH7Software/pH7-Social-Dating-CMS#177]
Unable to write to log file
can't write  logfile  by upload  photos or  making fake profiles

Change your Profile Photo
Unable to write to log file

Maybe somewhere  missing a  777 in a folder but cannot find  out wich one  

anyone can help Thanks

**Comment by pH-7** [comment]
When you upload a photo, pH7CMS doesn't write any log files.

Can you please send a screenshot of the full screen when you get this error.

Thanks

**Comment by pH-7** [comment]
Please also make sure that the ~/data/* (and its sub-folders) are set to 777 (or ask your Web host if you don't know). Hope that helps!

**Comment by dplay74** [comment]
hi see enclosed files
![changephoto](https://user-images.githubusercontent.com/37182939/37243626-0ea9eeb4-247d-11e8-8306-f572aee899f5.png)
![fakeprofiles](https://user-images.githubusercontent.com/37182939/37243627-0ec9be1a-247d-11e8-963a-6d2add94d12a.png)

**Comment by pH-7** [comment]
Thanks. Apparently pH7CMS doesn't have permission to write files `_protected/data/log/pH7log/except/` folder.

Anyway, it seems from an internal error. Can you enable the development mode in order to see the exception message. To do so, please go to Admin Panel -> Tools -> Environment Mode. and enable the development mode, then retry

**Comment by dplay74** [comment]
Hi also set the write to 
PUBLIC HTML/data/system/modules/user/avatar/img
combined with yoursetting that solved  it  also 

now  instead  of  profilenames  i got site.name/new-profile/83
Thats probarly a simply  .htaccess setting  can you assist me with this

**Comment by dplay74** [comment]
I had another problem that after editing  a  picture as  new  user it  logged  me  out  but this  maybe a time setting  i go to experiment  with that - it  is  hard to make  new  user as admin as it  uses  same  IP i use tunnelbear VPS to solve that to add new  users  as  it  gives  me  different  IP and also different countries 
That part works great  if  i have spanish IP system see  me as a spanish user  
Another things is can i as administrator  have access to users  passwords?  In edting  ?

**Comment by dplay74** [comment]
another question: whats  the right  url to get chat working  inc api I dont get thaty done  yet

**Comment by pH-7** [comment]
Hi again!

1- The URL you mention is from the "Dating-Style Profile Page" module. You can disable it from Admin Panel -> Mod -> Enable/Disable

2- You can create new users directly from the admin panel -> Admin/User -> Users -> Add New User
Maybe you got logged out because you have dynamic IP address. Otherwise, please retry with another web browser (firefox, safari, chrome). Never had that issue... Otherwise, if the problem persists, please screencast the situation.

3- The default one is https://ph7cms.com/addons/chat/?name=%site_name%&url=%site_url%&skin=4
Work well for me. You can change it though 
Have a look here: https://ph7cms.com/how-to-change-chat/

4- In order to be informed, don't forget to Star this repo
<img width="1030" alt="install_issue_ _issue__156_ _ph7software_ph7-social-dating-cms_ _github" src="https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png">

 
Hope that helps! 🎉

**Comment by dplay74** [comment]
Hi again very helpfull and yes there  is the  star ! Great support I go to work on it  more  any error  or questions  I post  here  Thanks!

**Comment by dplay74** [comment]
What i am missing  is  in the setting  that you can put  links to social netwoerks  of the website  like  twitter  FB etc can put that  off course  into the SEO part off course

**Comment by dplay74** [comment]
A facebook login fuction would  be also a great thing - maybe possibility to use twitter login 
I am sure  it generate  lot  of  users

**Comment by dplay74** [comment]
Ok i missed this  one  
. Instead, I prefer for the moment to spend my time on things that pH7CMS really needs and that can really help users to create the BEST social dating service (after all, social authentication won’t change a lot).

Anyhow  if you  do FB marketing and try to get  users from there  it can be helpfull same as with  twitter wich no one  use but always  post and read Anyhow see when you  have  time  or not ... it  was  just a suggestion

**Comment by pH-7** [comment]
You are very welcome @dplay74 🎉 
> What i am missing is in the setting that you can put links to social networks of the website like twitter FB FROM the site itself So not to like or link - but the accounts of the site self
Sorry, not sure to understand what you mean. Do you mean the " Social Media Widgets" in Settings field.

**Comment by pH-7** [comment]
Finally, there is a social connect module, but doesn't work anymore for Facebook for the moment because facebook changed their api (and their do that often).
More info in https://ph7cms.com/better-not-enable-connect-mod/

Unfortunately I don't have time for the moment to update it.

**Comment by dplay74** [comment]
for now you can share your website due  twitter - FB etc- from the homepage - what I mean is  that you show  the  FB / twitter /soc media  accounts from the site  itself  - for example:  Icon and  FB or twitter account  What  i liked  in the system self was the ability to share  all posts from the forums - to make  it  more clear that you  show the  buttons -of the social netwerks from the site itself

**Comment by pH-7** [comment]
Okay, that's clearer. Thanks for your suggestion @dplay74 
I will see later on if it can be implemented in a next version.

**Comment by pH-7** [comment]
I will close this ticket for now if there is no more issues with your initial problem. Please feel free to create a new one if you occur another problem.
