### ISSUE TITLE
What is the Database Password ?

### ISSUE THREAD

**Issue by jack17529** [pH7Software/pH7-Social-Dating-CMS#194]
I downloaded it from here - https://sourceforge.net/projects/ph7socialdating/?source=directory

Tried installing it, got stuck here - http://localhost/pH7CMS-12.1.2/_install/?a=config_system

Says - 

"Error connecting to your database.
SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)"

Please help me asap .

**Comment by polynamaude** [comment]
The database password is the one you choosed when you created your database and assigned a user (probably using phpMyAdmin).

I suggest you go out and read about MySql/MariaDb. There's many good books around.

And by the way, on a volunteer based community don't try to pressure people by "ASAP". No one has the slightest obligation to help you out and honestly some years ago the only answer you'd get for such a question would be "RTFM" !

If you don't know what happened in your case and where does this message come from then I doubt that you have useful knowledge for such a product. Software ain't a thing about "Point-Click-Next", you'll need more than that to get this do something useful.

Do some PHP testing at home with PDO and you'll see what I meant. It's not because you can install Visual Studio that you know how to use it and produce code. Same for a CMS, just the way you described your problem showed be that you don't understand the basic. Why would we know YOUR database password !

**Comment by polynamaude** [comment]
The database password is the one you choosed when you created your database and assigned a user (probably using phpMyAdmin).

I suggest you go out and read about MySql/MariaDb. There's many good books around.

And by the way, on a volunteer based community don't try to pressure people by "ASAP". No one has the slightest obligation to help you out and honestly some years ago the only answer you'd get for such a question would be "RTFM" !

If you don't know what happened in your case and where does this message come from then I doubt that you have useful knowledge for such a product. Software ain't a thing about "Point-Click-Next", you'll need more than that to get this do something useful.

Do some PHP testing at home with PDO and you'll see what I meant. It's not because you can install Visual Studio that you know how to use it and produce code. Same for a CMS, just the way you described your problem showed be that you don't understand the basic. Why would we know YOUR database password !

**Comment by polynamaude** [comment]
The database password is the one you choosed when you created your database and assigned a user (probably using phpMyAdmin).

I suggest you go out and read about MySql/MariaDb. There's many good books around.

And by the way, on a volunteer based community don't try to pressure people by "ASAP". No one has the slightest obligation to help you out and honestly some years ago the only answer you'd get for such a question would be "RTFM" !

If you don't know what happened in your case and where does this message come from then I doubt that you have useful knowledge for such a product. Software ain't a thing about "Point-Click-Next", you'll need more than that to get this do something useful.

Do some PHP testing at home with PDO and you'll see what I meant. It's not because you can install Visual Studio that you know how to use it and produce code. Same for a CMS, just the way you described your problem showed be that you don't understand the basic. Why would we know YOUR database password !

**Comment by polynamaude** [comment]
The database password is the one you choosed when you created your database and assigned a user (probably using phpMyAdmin).

I suggest you go out and read about MySql/MariaDb. There's many good books around.

And by the way, on a volunteer based community don't try to pressure people by "ASAP". No one has the slightest obligation to help you out and honestly some years ago the only answer you'd get for such a question would be "RTFM" !

If you don't know what happened in your case and where does this message come from then I doubt that you have useful knowledge for such a product. Software ain't a thing about "Point-Click-Next", you'll need more than that to get this do something useful.

Do some PHP testing at home with PDO and you'll see what I meant. It's not because you can install Visual Studio that you know how to use it and produce code. Same for a CMS, just the way you described your problem showed be that you don't understand the basic. Why would we know YOUR database password !

**Comment by pH-7** [comment]
Hi @jack17529 
You will have to create the database and user database (and set a password for the DB user) before starting the installation :)

If you read well the instruction during the installation process, on the first step (page), it says
> Before to continue, please create a MySQL database and assign a user to it with full privileges. Once you created the MySQL database and its user, make sure to write down the database name, username and password since you will need them for installation.

Hope that helps! 🎉 

P.S. Jack, don't forget to Star this Github repo 😺

**Comment by pH-7** [comment]
Hahaha, I arrive a bit late to the party @polynamaude. Just see your message 😃 You are so quick! 👍

**Comment by pH-7** [comment]
Hahaha, yeah, exactly. I see what you mean. I totally agree with you!

Ah, the good old Commodore 64!! 😄

**Comment by pH-7** [comment]
Closing it, since there was no problem here 😃
