### ISSUE TITLE
User email activation not working, same with "Forgot Password" email, none was sent. I have tried several times, checked my Spam box yet found nothing. But the Admin email "Forgot Password" is working, any help please?

### ISSUE THREAD

**Issue by Prinz234** [pH7Software/pH7-Social-Dating-CMS#198]

**Comment by polynamaude** [comment]
Please give more information like the webserver used, operating system, related logs, how did you do the installation (regular or softaculous)...?

It's not serious to classify an "issue" and request to the community for help if you don't do your part of the job ! How do you think someone can help you out in such a case ? We don't have a clue about what's going on except for a vague complain of the type "not working = not happy = it's your stuff the problem".

What have you tried to fix the problem ?
Is this on commercial or self hosted ?
What Apache modules are enabled ?

We'd be glad to help but do your share and ask at the good place ! What make you think the issue is pH7 related and not server mid configuration ? Have you looked to other similar open and closed issue?

We call it basic RTFM !

Sincerely

**Comment by polynamaude** [comment]
You see the "no description provided" underneath your question on top of the page? It should give out a hint about something missing.

And please don't tell me "hosting provider technical support said your software is the problem" because if they don't give you more than that it's because they just throw out an easy answer.

pH7CMS pushes webserver software to it's limit to give high optimisation so it may show out problems other software won't. Like the time in the mid 90 that Linux showed off the bad RAM that msdos didn't.

**Comment by polynamaude** [comment]
Just looking at your complain, may I ask have you checked your SMTP server log to see if pH7 does connect ? And further more on your Apache logs to see if there's some request denied?

**Comment by Prinz234** [comment]
Thanks @polynamaude 
But too many questions for a newbie :)
The Sever is Apache 2.4 and this is self hosted on Plesk/Linux VM. The Software installation was done via Softaculous, could this be one of Softaculous issues... Strange to me is that the Admin side is working perfectly. I contacted Softaculous when I was having Admin login issues and they said they are trying to fix it but nothing happened until I found solution on my own. I only hope I can find a way to upload the software on my own, I have tried but the message I got half way during uploads is "Command MLSD" on FTP clients, I have used Filezilla and Voyager.

**Comment by Prinz234** [comment]
@polynamaude I can confirm that the mail issue has nothing to do with pH7CMS/Software or Softaculous. I found all the mails Queued in Plesk "Deffered Mails", and I have used Plesk Repair Tools to automatically fix the problem but no issues was found. Finally contacted Plesk Support, still waiting for it to be resolved.
Thanks for pointing out "Simple Mail Transfer Protocols" as part of what might be the problem because it helped me to trace where the error is coming from.

Still learning, but through practice.

**Comment by tuntoy** [comment]
My web hotsting has softaculous installer which install the pH7CMS 12.1.2 version but my problem is i tried to login to the admin panel but i can see a flash message says "log in first please what is the problem or what can i do
![for dating complat](https://user-images.githubusercontent.com/9052165/40048938-5912cc6e-582b-11e8-883c-ebdf1f6470d3.png)
