### ISSUE TITLE
Step 3/6 Install issue

### ISSUE THREAD

**Issue by fdputhuff** [pH7Software/pH7-Social-Dating-CMS#203]
What might be causing this issue?
See Attached
![capture](https://user-images.githubusercontent.com/38889683/39727711-c2789478-5221-11e8-8830-228098d9c660.JPG)

**Comment by pH-7** [comment]
Hi @fdputhuff 

Unlike what you said by email, it isn't an issue with FFmpeg at all. 
The error is because your database user doesn't have the permissions for the hostname or isn't assign to that database. If you are using a web host company and don't know what to do, please give them the error message and they should be able to fix it for you. Once it's fixed, you will have to remove _constants.php file in the root folder and start again the installation process (if possible in an incognito window or with another Web browser or remove the cookies).

Hope that helps!


P.S. if you web host offers it, you might be able to install pH7CMS directly through Softaculous (which might be easier for you).

**Comment by pH-7** [comment]
In short, grant all privileges to the user first.

If you read well the instruction, on the first step during the installation, it says
> Before to continue, please create a MySQL database and assign a user to it with full privileges. Once you created the MySQL database and its user, make sure to write down the database name, username and password since you will need them for installation.

**Comment by fdputhuff** [comment]
I had noticed "please create a MySQL database and assign a user to it with full privileges" but was not able to figure out how to do it until last night.
Today I came home and tried to install again and everything worked fine.

Thanx guys
