### ISSUE TITLE
Switching to Social Site

### ISSUE THREAD

**Issue by fdputhuff** [pH7Software/pH7-Social-Dating-CMS#205]
Quick question:
How do you switch this software to the social site theme and not the dating theme?

From the WebSite: ttps://ph7cms.com

> pH7 Dating CMS is a Professional Social CMS to build an Online Dating Services or **Social Network Websites.**

**Comment by pH-7** [comment]
Hi @fdputhuff 
If you did the classic installation (without using Softaculous) using the installation https://ph7cms.com/doc/en/install, you will see at the end of the installation, a [page where you can select your niche](https://ph7cms.com/ph7cms-ready-social-dating-niche/).

Otherwise, if your site is already installed, you can do it manually by selecting the "Zendate" theme (in Admin -> Settings -> General). And disable the "dating theme" and enable the more "social" module on Admin -> Mods -> Enable/Disable Module.

Can you also give a review on https://sourceforge.net/projects/ph7socialdating/ This really help me :smile: 

Hope that helps! Thanks!

**Comment by pH-7** [comment]
FYI ;)
<img width="1313" alt="screen shot 2018-05-17 at 7 36 59 pm" src="https://user-images.githubusercontent.com/1325411/40194165-bbbad188-5a09-11e8-9c3c-a28cc933950d.png">
