### ISSUE TITLE
Sign Up Problem

### ISSUE THREAD

**Issue by p666231** [pH7Software/pH7-Social-Dating-CMS#215]
After sign up and sign in,
cannot create new cookie

**Comment by pH-7** [comment]
Hi @p666231  How are you?

Although I have nearly no details concerning your issue, it might be a problem with the session (especially if the form doesn't give any error messages), because your server might have "permission issues" when writing the sessions.
You can contact your host for asking them to investigate and check their log.

Let me know if the problem persists or if you fix it.

Have a lovely day anyway!

**Comment by pH-7** [comment]
I'm closing it for now since I didn't get any news concerning the issue. Please reopen it or open a new explicit issue with further details if needed.
