### ISSUE TITLE
Version 8.0.4 data lost

### ISSUE THREAD

**Issue by kirenpillay** [pH7Software/pH7-Social-Dating-CMS#216]
I received notification that versions less that 8.0.6 would not work anymore. I was busy at that time and that thought I could upgrade after May 2018. 

However, I logged in now and see that ALL my data is gone? Was this your software that did this? If so, you should have warned us that our data would be deleted. It took six months to accumulate 200 users, now I have to start from scratch, if they ever use my site again.

**Comment by pH-7** [comment]
Hi @kirenpillay 
The post you might see https://ph7cms.com/issue-new-installation-from-old-version/ concerns only new installations for 8.0.4 or older.
All data are stored to your web hosting. I don't have any powers to change or remove your data. You are the only one who owns your data. The data of your website is stored into your MySQL database. Please contact your web hosting in order to know why the data are gone (maybe your or your web hosting did backup) or please check with phpmyadmin in order to investigate and see if you see your data. Another possibility is that the credential of your database changed, but if so, you would see an error message.

Anyway, the only one who might have the answer is your web hosting ;) Hope this helps.

Please open another ticker if you have a further issue related to the software and you didn't find the answer.
