### ISSUE TITLE
 does your cms support sendmail?

### ISSUE THREAD

**Issue by mingkan** [pH7Software/pH7-Social-Dating-CMS#219]
I use my own web server at home. It installed sendmail at the same LAMP in the same server. I have few websites hosted. One of them are using joomla. It can send email in my joomla website.

However, it can't in your cms. I have followed https://www.quackit.com/php/tutorial/php_mail_configuration.cfm instructions. My SMTP = localhost in php.ini 7.2

All my version of my software in my server are latest.

Thanks.

**Comment by polynamaude** [comment]
Hi !
Could you define "latest" as it doesn't say much.

What do you use for your hosting ? One instance or multiple virtual machine. Have you tried looking at your sendmail log for errors ? Have you tried enabling loggin in your php instance by forcing into the php.ini?

For now and with the information I got, nothing point out to a specific problem with the CMS. Have you tried putting 127.0. 0.1 ? Or better would be your IP (private or public).

PM

Le 10 juin 2018 17:05:37 EDT, Ming Kan <notifications@github.com> a écrit :
>I use my own web server at home. It installed sendmail at the same LAMP
>in the same server. I have few websites hosted. One of them are using
>joomla. It can send email in my joomla website.
>
>However, it can't in your cms. I have followed
>https://www.quackit.com/php/tutorial/php_mail_configuration.cfm
>instructions. My SMTP = localhost in php.ini 7.2
>
>All my version of my software in my server are latest.
>
>Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/219

-- 
Polyna-Maude R.-Summerside

**Comment by pH-7** [comment]
Hi @mingkan 

Like what @polynamaude said, the best is to look at your logs from your email server or ask your web host to investigate why you don't receive emails. Please also check your spam folder of your mailbox.

Further details can be found here https://ph7cms.com/doc/en/why-pH7CMS-can't-send-emails

P.S. Apparently you found the solution since you closed the ticket. If there was a trick you found in order to fix the issue, could you post it here? (so, other people with the same problem might benefit from it).

**Comment by pH-7** [comment]
Hi @mingkan

Like what @polynamaude said, the best is to look at your logs from your email server or ask your web host to investigate why you don't receive emails. Please also check your spam folder of your mailbox.

Further details can be found here https://ph7cms.com/doc/en/why-pH7CMS-can't-send-emails

P.S. Apparently you found the solution since you closed the ticket. If there was a trick you found in order to fix the issue, could you post it here? (so, other people with the same problem might benefit from it).
