### ISSUE TITLE
Membership setup

### ISSUE THREAD

**Issue by PRINCEPANNU** [pH7Software/pH7-Social-Dating-CMS#223]
how i can setup membership for a user in many packages and how they upgrade membership

**Comment by polynamaude** [comment]
In the user editor you can assign a user to a specified membership.

After the duration left they fall back to default.

When user pay for membership they get the level they paid for.

Take a look around the admin panel. It's quite easy, explore around.

Also you can go to the _doc url to get documentation.

Also look into php code and you'll get more information.

PM

Le 20 juin 2018 02:07:20 EDT, PRINCEPANNU <notifications@github.com> a écrit :
>how i can setup membership for a user in many packages and how they
>upgrade membership
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/223

-- 
Polyna-Maude R.-Summerside

**Comment by polynamaude** [comment]
As always do some try around. Nothing can be broken.

You seem pretty new to the developper community I think?

Le 20 juin 2018 02:07:20 EDT, PRINCEPANNU <notifications@github.com> a écrit :
>how i can setup membership for a user in many packages and how they
>upgrade membership
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/223

-- 
Polyna-Maude R.-Summerside

**Comment by pH-7** [comment]
Indeed, like what @polynamaude said very well!, go to Admin Panel -> Mods -> Billing, and you will see all options. Assign your users to a default group with specific permissions, then add extra memberships which they will have to upgrade (pay) to get more features, more permissions, etc.
P.S. @PRINCEPANNU Don't forget to Star the Github repo and [leave a nice review](https://sourceforge.net/projects/ph7socialdating/reviews/). All hard work here are make by volunteers, so I would really appreciate if you could do something like this ;)

**Comment by PRINCEPANNU** [comment]
How i can integrate paytm payment gateway for my user actually folks I want
to target use paytm

**Comment by PRINCEPANNU** [comment]
If I want to add another how can i add in my website

**Comment by pH-7** [comment]
@PRINCEPANNU As easy as it says, **Admin Panel -> Mods -> Billing -> Add Membership**
Do you mind to Star the Github repo and leave a nice review?

**Comment by PRINCEPANNU** [comment]
I want another platform to payment for users.

**Comment by PRINCEPANNU** [comment]
Yes i remembered to give and i will definitely give my review

**Comment by pH-7** [comment]
To add other payment gateways, this cannot be done through the admin panel, since each payment system relies on a specific API which needs to be handle with a specific library. 
This can only be done by modifying the source of the ["payment" module](https://github.com/pH7Software/pH7-Social-Dating-CMS/tree/master/_protected/app/system/modules/payment) and in [pH7Framework](https://github.com/pH7Software/pH7-Social-Dating-CMS/tree/master/_protected/framework/Payment/Gateway/Api) (eventually, you could add a composer library if available for that payment provider) and follow the same way like how it's done for the current payment gateways.

You can also do it by forking this repo, do your changes, push it to your Github account and open a pull request to this repo with this new payment gateway. Don't forget to follow [pH7CMS's coding conventions](https://ph7cms.com/doc/en/code-convention).

Finally, do you mind to Star the Github repo and [leave a nice review](https://sourceforge.net/projects/ph7socialdating/reviews/). All hard work here are make by volunteers, so I would really appreciate if you could do something like this ;)

**Comment by PRINCEPANNU** [comment]
Thanks

**Comment by pH-7** [comment]
Closing this ticket since everything has been clarified. @PRINCEPANNU Don't forget to Star the Github repo and [leave a nice review](https://sourceforge.net/projects/ph7socialdating/reviews/) ;)

**Comment by polynamaude** [comment]
@PRINCEPANNU 
If you need some references for php books or tutorials then let me know.

If you don't already do PHP coding then I suggest you take a look at the source code to see how easy PHP is to read and write. You'll gain much flexibility in customizing by doing so.

**Comment by polynamaude** [comment]
@pH-7 By the way, thanks for your hard work.

**Comment by pH-7** [comment]
Thanks @polynamaude! 😊
