### ISSUE TITLE
Block Search Engine scanning/indexing...

### ISSUE THREAD

**Issue by craigarno** [pH7Software/pH7-Social-Dating-CMS#225]
pH7 is being considered for a new social site.  The acceptance blocking "Feature" for our application is "SEO-Friendly".  Our user-base must absolutely be protected from Search Engine indexing.  Without the ability to block search engine access to our site, this product can't be used.

PRIVACY is a huge concern.

**Comment by polynamaude** [comment]
@craigarno

Have you installed the software and looked at the available options ?

You have all the liberty needed to customize to your needs as the source code is clean, commented and follow standard design pattern (MVC and others).

Hope this help

PM

**Comment by craigarno** [comment]
To be fair, I had not installed the software.  My comment was based on having read your web site claims.

I tried installing your software on Ubuntu 16.04 LTS x64, a production server for a non-production dating site installation test/review.  After reading your installation requirements/procedure I had to enable exec() PHP, which seems a bit of a security risk, but I did it anyway for this test.

You can see the mostly not functioning results at https://arno.com/dating
My PHP config is here http://arno.com/info.php
and from inspection it looks like the database built correctly.
  mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper
ph7_admins
ph7_admins_attempts_login
ph7_admins_log_login
ph7_admins_log_sess
ph7_ads
ph7_ads_affiliates
ph7_affiliates
ph7_affiliates_attempts_login
ph7_affiliates_countries
...

Install reported it completed successfully: **Woohoo! pH7CMS is now installed!**

I can't login as administrator, myself, or using my email address
Instructions seemed straightforward, they just didn't result in a functioning system.

Every attempt to login results in 
"The requested URL /dating/login was not found on this server."

I tried running https://arno.com/dating/WebsiteChecker.php and it just immediately returns to the non-functioning site home page.

Without a functioning system I can't determine how/if security can be handled as needed.  Apparently I need help with this install.

**Comment by polynamaude** [comment]
@craigarno 
Look through others issue and you'll find one about mod_rewrite. Make sure it's enabled and modify your htaccess if the installation folder is not on the root (/) of your server. I'd recommend creating a dedicated vhost linked to a particular hostname in apache.

It would be a good choice (in life) to substantiate affirmation instead of making assumption without knowledge. You made the assumption of a privacy problem based on very litte information and that is SEO optimised. Did you know that Google's engine will calculate page loading time to establish your site ranking. So when this software compress your pages and minify the scripts then it's part of SEO.
Like I mentioned earlier you have many options to control search engines but that's far from the pH7CMS subjects.

Honestly, it doesn't look as a professional way to act when you judge before you see.

As I see the links you gave for your site then update your htaccess file or move your site to a web root.

If we can offer such resources efficiency then it's because software abilities are push to the limit for webserver. That's why mod_rewrite is needed and a custom htaccess. It will be much easier to move to a root folder than to modify configuration.

Also, could you explain why you consider that exec() constitutes a security breach in the present case ? Or is it simply a loose comment ?

Do those change and your website will work. Pretty normal that you get a 404 as the rewrite system will call the base /init.ph7 or /index.php and that's probably a different system in your case.

Don't forget to star the repo as this is our paycheck for the hard work done over the years.

You can go to /_doc once installed and you'll get your documentation.

Also, little trick make your installation as standard as possible when you start using a software (root folder of webserver in our case) as you just make it harder on yourself to customize the standard procedure without knowing a product.

PM

**Comment by pH-7** [comment]
Hi @craigarno 
All users registered to your website can choose to exclude their profile from search engine from their privacy settings.
<img width="920" alt="screen_shot_2018-06-21_at_12_29_49_pm" src="https://user-images.githubusercontent.com/1325411/41714042-590a098a-754f-11e8-9bc2-858a2b9fa77c.png">

Now, if you want to exclude all profile from search engines index (without giving the possibility to your users), you will have to modify one line of code, since the option isn't available for the moment in the admin panel.

Add 
```php
$this->excludeProfileFromSearchEngines();
```
in [_protected/app/system/modules/user/controllers/ProfileController.php](https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/b9c28ba859132d3149b9b7d0af3f87259c5d8d61/_protected/app/system/modules/user/controllers/ProfileController.php#L60), line 60


You can do the same for "Dating-Style Profile Page" (it enabled in Admin Panel -> Mods -> Enable/Disable Modules), 
add 
```php
$this->excludeProfileFromSearchEngines();
```
in [_protected/app/system/modules/cool-profile-page/controllers/MainController.php](https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/b9c28ba859132d3149b9b7d0af3f87259c5d8d61/_protected/app/system/modules/cool-profile-page/controllers/MainController.php#L52), line 52

**Comment by zeerprettiggestoord** [comment]
About the teaching part....
Im using codecademy to brush up on my html and css knowledge..
Unfortunately they dont have a course in php anymore.

Do you guys know a similar free website to learn php?

Op do 21 jun. 2018 19:25 schreef Polyna-Maude R.-Summerside <
notifications@github.com>:

**Comment by polynamaude** [comment]
@zeerprettiggestoord 
Hi !
Could you post your question onto the issue that it is relating ?
We are already dealing with a subject here and the goal is not to finish with a "spaghetti" of different thread unrelated to each other.

We did actually close your issue but it shouldn't make it impossible for you to write a message.

Also if you appreciate the value added support that is given then it would be a good thing that you answer when we make you suggestions. Our paycheck come from the appreciation of the users so instead of letting us close a thread when you got the solution you could give a simple "thank you for your help" . If you're not sure what I'm talking about then see #213 

Also I'd suggest you read back what I said in the last message of #207 and refer you to Stackoverflow or Google. When I did talk about programming support what I meant was if you needed help for coding relating to pH7CMS. What you asked here is something you could find answer pretty easily by yourself.

Like I said, you're just influencing the attitude people will be giving you so if you ask such question you're at risk of just getting ignored on the long run. Honestly, I just type "php tutorial training" on Google and got many result pretty easily.

PM

**Comment by craigarno** [comment]
On 6/21/2018 2:18 AM, Polyna-Maude R.-Summerside wrote:
> Also, could you explain why you consider that exec() constitutes a
> security breach in the present case ? Or is it simply a loose comment ?

Unless functions like exec() are implemented with great care, thought,
and the rest of the system is locked down, again with great care, exec()
allows execution of arbitrary code.

Consider exec("./install-rootkit"), or exec("cat /etc/passwd")

How could pH7 be fooled into executing these strings? (The devil is in
the details)
Does pH7 allow uploads? (yes)
Are pH7 files writable? (yes, all installed files appear to be set to
"-rwxrwxrwx" which means any file can be rewritten by any user,
including www-data, which makes it much easier to find a way to inject
the two simple "exec()" examples)

A quick Google search finds this
https://stackoverflow.com/questions/3115559/exploitable-php-functions

... keep thinking like this and it shouldn't be long or require much
imagination before an exploitable vulnerability is found.  Someone with
modest skills bent on causing havoc with pH7 sites shouldn't have too
much trouble exploiting a system which is mostly configured by pH7
install software.  This raises the question about how much experience,
education, or skill is behind your statement "... security involved as
it was a priority when designed."

Any low level "protected" account can be used to install a root-kit. 
exec() allows execution of code on the target system.  I'm not about to
launch an effort to find vulnerabilities in your design, but just using
exec() or other command execution mechanisms on a rewritable system
suggests it wouldn't take much skill, effort, imagination, or training
to crack a targeted pH7 installation.

Not a loose or idle comment.

**Comment by polynamaude** [comment]
@craigarno
Have you ever did any programming ?
When we do use file upload there's sanitizing upon the filename transmitted so there's no possibility of user writting file outside of our control.

Maybe you'd be better with looking at security alert of some other php software so you could see real world example and understand how does those breach work.

It's pretty much what I call loosely held talk what you served me. Basicly sound like "enabling remote login on a server could compromise security if your username and password get discovered".

Good luck !

**Comment by polynamaude** [comment]
@craigarno  you can bypass O/S security and become root user with that much ease ! You're hell of a genius, go work for NSA or MI5 and stop wasting your time with social dating.

**Comment by polynamaude** [comment]
@craigarno What that seem to be out of your understanding is that most pH7CMS site are operated by developper who build upon our work but you seem much more to be looking for something that won't require you to write a line of code. So instead of complaining you can fork, make the great mofification you suggest then do a Pull Request. So we'll all learn and benefit from the years of experience you got.

Easy to complain but can you do better?

**Comment by polynamaude** [comment]
@craigarno If you look at pH7Cms, when configurer with supplied htaccess you'll be directing your request to index.php and from there the request will be analyzed to serve the good controller. There's restriction imposed by the server.

Indeed there's possibility of file upload but we don't use any input from the user and identify the file type as images or we simply don't even go to saving it.

To be able to control what is executed by exec you need the ability to get control over the string used in the exec function and those are hard coded.

So the way we work is much like PDO prepared statements that are used to prevent SQL injection.

To believe that because we use exec() the arbitrary code could be executed is the same as saying that a web application is open to XSS because it uses Ajax or simply accept information through a POST/GET request.

I surely understand that you did search about this function and got some warning. But to really understand what I'm saying you can go look at Joomla or Drupal security feed to see what is a vulnerability, get metasploit framework and look into the exploit as there's nice example in modules/exploit/unix/webapp/joomla_media_upload_exec.rb . It works on old version of Joomla and was fixed long ago but is good for knowledge. You can also look at offensive security exploit database.

I can understand that you put high priority on security but the warning you got is something we all get and that we deal with.

If you ask PH he could confirm but exec() is only used for calling a local curl to get web page loaded into the cache. But that's only valid for pH7CMS as some external library use such call from memory that is Symfony components and Stripe.
 It's a function used in many packages when doing PHP.

Use grep and search the code to find occurrences if you want to see.

PM

**Comment by pH-7** [comment]
@zeerprettiggestoord You have a lot of good and and really complete PHP tutorials on Udemy https://www.udemy.com/courses/search/?q=php

**Comment by pH-7** [comment]
@craigarno Concerning your issue with 404 pages, maybe it's because Apache rewrite mod isn't correctly setup https://ph7cms.com/doc/en/how-to-install-rewrite-module or because .htaccess wasn't uploaded correctly to your root folder, etc. Anyway, it's a problem with your web server.

**Comment by zeerprettiggestoord** [comment]
@ph7 thank you very much!

Op vr 22 jun. 2018 13:18 schreef ♚ PH⑦ Soria ♛ <notifications@github.com>:

**Comment by polynamaude** [comment]
@pH-7 Hi,
I found exec() in the Symfony dependency but I got it wrong as Stripe is using curl_exec.

I looked at Video.class.php and everything look pretty much clean as the command is hard coded (ffMpeg), same for options, the parameter come from inside pH7Cms and nothing is possible to get user controlled.

The main failling point on big PHP projects is opening the API to extensions that won't be secured as the core because often ill-tested. Nothing we get close here.  There's also the necessity for backward compatibility that messes everything on the long run.

I'm running some XSS tests and other security hunting. I'll send you the results when completed.

Thanks for adding correction.

**Comment by pH-7** [comment]
@polynamaude Thanks for these details! 😃 That's great for the XSS tests you are running :)

**Comment by pH-7** [comment]
I'm closing this issue now, since initial question has been answered, and it now goes to other unrelated things. Please open a new issue for further matters.

**Remember**, one issue = ONE question/problem.

**Comment by polynamaude** [comment]
@pH-7 Good thing to be reminded one issue/one thing
