### ISSUE TITLE
Cron error: file not found

### ISSUE THREAD

**Issue by BlackTiger63** [pH7Software/pH7-Social-Dating-CMS#233]
I made a cron like the example in the docs, but then for the birthdays, like this:
`10 0 * * * "GET https://domain.com/asset/cron/24h/Birthday/?secret_word=xxxxxxxxxxxx"`
So it should run every night at 00.10 hours.

But now I got an e-mail stating:
`/bin/sh: GET https://domain.com/asset/cron/24h/Birthday/?secret_word=xxxxxxxxx: No such file or directory`

I do meet the requirements as far as I could see and curl is present on the server, but the GET command is not. I guess. When I use GET in SSH it says:

> -bash: get: command not found

Am I missing something or doing something wrong here?

**Comment by BlackTiger63** [comment]
FYI: I tried it like this too:
`curl --request GET "https://domain.com/asset/cron/24h/Birthday/?secret_word=xxxxxxxxx"`

This looks like the cronjob will work, but then I get another email:
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   352  100   352    0     0   9263      0 --:--:-- --:--:-- --:--:--  9263
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /asset/cron/24h/Birthday/
on this server.<br />
</p>
<p>Additionally, a 403 Forbidden
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```
So something is going wrong there.

**Comment by polynamaude** [comment]
@BlackTiger63 
Hi,

I'm not sure what system the examples are made for but cron job are called like any other command so you use "/usr/bin/curl" or wherever the command is on your host.

**Comment by polynamaude** [comment]
@BlackTiger63

Also remove the ending / after birthday for 24h/birthday?secret=xxx

And the problem is gone.

Please make a nice comment on sourceforge and star our repo.

Thanks

**Comment by BlackTiger63** [comment]
> I'm not sure what system the examples are
??? Why not? They are from the pH7 docs like I stated.
[https://ph7cms.com/doc/en/cron](url)
You can also see that just GET is called in the cron example and not /usr/bin/curl GET or something like that. I already wondered about this.

But where do the apostrophe come then?
Will it be /usr/bin/curl --request GET "domain.com etc." or "/usr/bin/curl --request GET domain.com etc" or without the --request?

I know a trailing / requests a directory but the trailing slash was stated in the example here:
[https://ph7cms.com/doc/en/cron-list](url)
So I did not make a typo according to the doc, if the trailing slash should not be there, both the doc's contain several (same) typo's.:)

I would like to leave stars and a nice comment, but I suggest the docs are fixed decently first, because otherwise users will keep making these mistakes.

Ok tried again without the trailing slash as you suggested like this:
`/usr/bin/curl GET "https://domain.com/asset/cron/24h/Birthday?secret_word=xxxxxxxxxx"`
and got the same error as I did before:

```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: GET

100   351  100   351    0     0  13000      0 --:--:-- --:--:-- --:--:-- 13000
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /asset/cron/24h/Birthday
on this server.<br />
</p>
<p>Additionally, a 403 Forbidden
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

```
I'm using Centos 6.10 and curl and everything is present.
So I'm still wondering what's wrong as I have done it correctly now.

**Comment by polynamaude** [comment]
@BlackTiger63 

First thing, I'm not the one who wrote the docs.

I help out concerning the CMS but I don't train people in the use of Unix system.

Ever tried "man crontab" or "man cronjob" ?

Because as far as I'm concerned the docs are ok  because we had many user install our software and none complained. Maybe you need to do a little work on your side too.

Do a "man 5 crontab" and you'll see how to format a cron file.

We state that the cronjob should request the following and we believe that system administrator know the use of vixie cron, curl and other infrastructure.

Have you tried "man curl"?

If you did, you would have had your answer. Remove the word "GET" as it's not needed. We write "GET" in the docs because you need to do a get request.

so /usr/bin/curl -g https://lonely.com/asset/cron/24h/birthday?secret=yoursecret  .

And because you don't want to get shell expansion on your string, you put address between " http://......?secret=yoursecret".

Am I wrong or you're the same dude who was saying there's a error because in the way we wrote /asset/24h... But you didn't understand the difference between the file - folder and URL ?

Anyway you got enough to get going with that.

PM

**Comment by polynamaude** [comment]
@BlackTiger63 

By the way, if you look at your output, you see that the cron did run and get a "GET" command not found. Didn't that gave you the idea to remove GET ? You already got your solution.

**Comment by BlackTiger63** [comment]
@polynamaude I'm sorry.
Since you wrote "our repo" I though you were writer or co-writer.
But it looks like you are trying to piss me off, well you succeed, but we both can try this.

> Didn't that gave you the idea to remove GET ? You already got your solution.

No I did not look at my output, I went for an icecream. OMG!
Try reading my reply's. Didn't I try /usr/bin/curl --request GET instead? Which worked but gave also an error output? Right! So it wasn't my solution as you think.

Your line is by the way faulty. It should not be /usr/bin/curl -g but should be /usr/bin/curl -G with capital, so you might try man curl yourself because -g is globoff and -G is get. :)

Beside that, what I used before /usr/bin/curl --request GET "ht...." is also a correct way. Which gives *exactly* the same error as your "correct" line.

> We write "GET" in the docs because you need to do a get request.

We? You just told you did not write anything.
Sorry but that's no way to write an example. Most users do have 0 knowledge and copy/paste these examples. One can't expect them to know about crons, and curl etc.

Same for putting things between " signs which is also not done in a real example if it should not be used. And I don't think the writer really intended it as you say/think.
It would be like expecting windows users to know their way around the command prompt.
So I really wonder with how many users the cron won't even work. I doubt that almost nobody would use copy and paste commands to put the examples in to cron, that would be a first.

Yes I was the same dude that wrote that about /assets/24h. And I was correct, that was a doc mistake too. I do understand a difference between file, folder and url, I'm not stupid. But I can also overlook some things, like you did with your curl command (see below).

I really like this is free, but please don't piss me off by blaming me for making DOC stated faulty statements and wrong examples. I'm just pointing them out.
Unless you are on of those who don't see a benefit in improving docs and examples.
I'm not even doing this for myself but to help a friend which got stuck on a too old version.

So let's start a decent way again I hope... I tried like you said in the cron:

`/usr/bin/curl -G https://domain.com/asset/cron/24h/Birthday?secret_word=xxxxxxxx`
even tried your exact example with -g.

Without any " or GET statement.
And the same error occurs both times, so who's wondering now?
So no solution!
Now you got yourself something to think about.

If you want to be of help, please stop the irritating comments, you make mistakes too.
And my reply's will be a lot shorter! :)

**Comment by BlackTiger63** [comment]
Just to be sure everybody's on the right track... this is still the error output:

```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   351  100   351    0     0  11322      0 --:--:-- --:--:-- --:--:-- 11322
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /asset/cron/24h/Birthday
on this server.<br />
</p>
<p>Additionally, a 403 Forbidden
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```
So nothing about wrong curl or get or whatever commands. Same error as in my "curl --request GET" command I tried before.

**Comment by polynamaude** [comment]
@BlackTiger63 
I'm the kind of person who think that it's not because you install a software that you got what it take to use it.

By the way, if there was an error in the doc then it was only a "core" missing.

Have you used the supplied htaccess file ?

Also, what did you try other than ask for help ?

Anyway ! Good luck... I'm not here to get into arguments. You seem lot more to enjoy the "I get free your work" than to respect people who try to help you or did put hours of work for stuff you enjoy.

If you'd take a deep breath you'd understand that I only said take time to review yourself.

Sorry but I'm into opensource development for the last 15 years and saw too many newbie that just like the "free" but don't understand more than that. As such that you'll be needing to do some diagnostic on your own and learn. Maybe you should complain to Linus Torvalds about some incomplete man page.

**Comment by polynamaude** [comment]
@BlackTiger63 

For your info, if I ask what you tried it's to get a picture of what's possibly wrong and not ask you to do the same.

Also it's not a support forum and if we do help out. It's because we're kind to do so. As the name imply "issue" it's for problem in the system. One person in a hundred who get a specific bug that we can't reproduce ain't something we can fix.

So either give us all the information needed so we can get a virtual machine or better provide it to us. And show we got a bug.

Or do like I would.... Learn about Apache configuration. And other stuff too !

Have you checked your logs? What do they say ?

You don't seem to get it that it's not a out of the box solution. Let me bet that you used Unix only since you started playing around with hosting.

If you don't like my answer then don't worry you'll get worst if you do such or developer mailing list.

RTFM

**Comment by polynamaude** [comment]
@BlackTiger63 Reading back what you wrote... I'm sorry but if you're a Windows user expecting plain "copy paste" - "point click" then you won't get much from this software.

Also when you make a software to be used by system administrator then you can presume that they know what vixie from, crontab, Apache configuration, some CSS/HTML/php and more. If we didn't use "" in the docs it's probably because as I already said. It's a example and there's many cron system, vixie like on CentOS is just one of them.

I'm not going to pass hours teaching you about administration. If you have a precise question and can take that you're not entitled to getting answered but may get help by kind person then you may try to ask. But try stuff before and not just "why does click click click click copy paste click click" don't work.

You're like a guy who complain that a C++ compiler is faulty but don't have a damn idea about writing c++.

Yes free software has incomplete documentation and is a bit more complex. That's why you can pay to get help or get a chance to learn by trying stuff.

**Comment by polynamaude** [comment]
@BlackTiger63 Like you said if you can't get your way with command prompt then wake up, you're using Unix/Linux now.

**Comment by pH-7** [comment]
Hi @BlackTiger63 
You second cron config is correct (https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/233#issuecomment-404339835).

Your problem looks similar to https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/182
.htaccess might block the user-agent "curl".
Try to remove https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/.htaccess#L176 in the root .htaccess 

Or, if this still doesn't work, please check if mod_security/mod_security2 is enable (if so, please disable it; you can ask your web host for this).


Finally, @BlackTiger63 please let us know if this work. Thanks in advance!

**Comment by polynamaude** [comment]
@BlackTiger63 You can add a useragent option to curl and choose one of the "allowed" user agent per .htaccess file. This should give you a hint if your getting blocked because of User-Agent.

Like pH said, look for modsecurity that is often a standard on shared hosting. It cause lot of problems when we need to do debugging. Your logs should give you hints.

**Comment by polynamaude** [comment]
@pH-7 Thanks for diving in. I kind of loose a bit of myself when I'm in front of this type of situation. I totally forgot about the 403 sent when called too often.

I don't remember if modsecurity mark it's blocking in the log or if they are just like the rest of 403?

Hope you're getting a good Sumner time. I'm getting out to the countryside tonight and until Sunday, much needed !

**Comment by pH-7** [comment]
That's great @polynamaude Have a great time then, and enjoy the sunshines! Mine is good too ;) Thanks!

**Comment by pH-7** [comment]
@BlackTiger63 Yes, it seems working well now. To make sure, you can even run again the cron in your Web browser. Go to https://domain.com/asset/cron/24h/Birthday/?secret_word=xxxxxxxxx URL and you should see an error message saying that the cron has already been ran within the last 24 hours...
This means it has been ran successfully :smiley:

Thanks for the suggestion! I will take a look. Don't forget to Star the Github repo if you don't mind ;)

**Comment by BlackTiger63** [comment]
Thank you pH-7.
In the browser I tried that already yesterday and that was working fine, hence me wondering why the cron did not. But that's logic if only curl is blocked.

Due to your help I'm going to have a look how I can star the repo!
Thanks for your help!

**Comment by pH-7** [comment]
You're very welcome @BlackTiger63 Have a great day!

**Comment by polynamaude** [comment]
@pH-7 Doesn't a message get sent beside the 403? Like "already gunned"? I was looking for such.

@BlackTiger63 you can add -A TigerAgent or something alike to bypass the curl blockade.

PM

**Comment by polynamaude** [comment]
@BlackTiger63 Seem like total bullshit as you talked about Windows user knowing command prompt. Happy you got a laughter, maybe the only one in your life of complaints !

**Comment by BlackTiger63** [comment]
@polynamaude I was looking for errors too but strangely enough, it only said cron changed and executed:
```
Jul 11 16:52:16 server18 /usr/bin/crontab[32036]: (root) REPLACE (user)
Jul 11 16:53:01 server18 crond[4474]: (tend21) RELOAD (/var/spool/cron/user
```
Thank you for the user-agent tip, but I just leave curl out there.
About the Windows user knowing command prompt, read again, it was an example that you can't expect Windows users to know command prompt. Which is the same as expecting users using your script (which also a lot of windows users with hosting accounts will do) knowing curl, cron and httpd get commands. That was what I was referring too.

And I don't have a life of complaints. I think that if you think these were all complaints, it says more over you then over me. My life is mostly fun.

Have a nice day at the beach! (or are you already back again?).

**Comment by polynamaude** [comment]
@BlackTiger63  For your information, the world ain't a unique timezone so maybe I'm not in yours ;-)

**Comment by BlackTiger63** [comment]
@polynamaude LoL. FYI, you said yourself 3 ours ago you would now leave for the countryside (indeed not the beach) until Sunday.
So it's quite logic that I was amazed you're still here. And that has nothing to do with timezones. :-)

**Comment by BlackTiger63** [comment]
Ah it's not tonight at your place yet... oke. :-)
