### ISSUE TITLE
russian langage

### ISSUE THREAD

**Issue by phil276** [pH7Software/pH7-Social-Dating-CMS#248]
I have installed some langages but I can't install russian langage, please help me.

**Comment by pH-7** [comment]
Hi @phil276 
Russian language was available in the installer, however I had to remove it since it wasn't possible for me to maintain it. Russian isn't as well available in the software for the moment.

Currently available in the full software: https://github.com/pH7Software/pH7-Internationalization#available-languages

You can easily translate it into Russian https://ph7cms.com/doc/en/how-to-translate-to-another-language

Then, if you are feeling generous, you can submit it by email or as a Pull Request to https://github.com/pH7Software/pH7-Internationalization repo.


Hope this helps!

Have fun!
