### ISSUE TITLE
Site redirecting to another website

### ISSUE THREAD

**Issue by jijin** [pH7Software/pH7-Social-Dating-CMS#253]
i have installed ph7cms 12.9 and after changing the .htaccess file to https enable the site redirect to xvideos.fr and i cannot access admin123 also.
kindly advice.
thanks

**Comment by pH-7** [comment]
Hi @jijin 

What do you mean by changing the .htaccess file? Is it only [this](https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/8c5b675d22e4a4abe8cf3583abd206e38a31db3a/.htaccess#L664-L665)?

Can you make sure you hasn't enable the "Adult Disclaimer" from the General Settings? If so, please disable it or use another one, since this is offered by a third-party provider. There is a warning on the setting page saying it.

**Comment by pH-7** [comment]
And finally, what's your website URL, so I can have a look for you.

**Comment by jijin** [comment]
Thanks for  the support.
In the .htaccess file i have enabled the ssl ( https:)
My URL is therealcouples.com
I cannot access my admin also because it automatically redirect to other site.
Please advice.
Thanks

Sent from Yahoo Mail on Android 
 
  On Mon, 30 Jul 2018 at 16:12, ♚ PH⑦ Soria ♛<notifications@github.com> wrote:   
And finally, what's your website URL, so I can have a look for you.

**Comment by pH-7** [comment]
@jijin I checked. Indeed, you enabled the "Adult Disclaimer". On the settings page, there is a red warning saying that you have to be careful before enable it. However, this SHOULDN'T redirect you to another website like this. I will see with the third-party provider, otherwise I will remove it from the software. Once you log in, please disable it in order to avoid this issue again (Admin Panel -> Settings ->  Adult Disclaimer).
<img width="950" alt="screen_shot_2018-07-30_at_4_07_51_pm" src="https://user-images.githubusercontent.com/1325411/43402450-0b5edb38-9413-11e8-9b02-e498fe94d963.png">


I was able to reach your admin login page without any issues. Maybe you can't because you are on Android. Can you please try it on desktop.
<img width="1167" alt="screen shot 2018-07-30 at 4 04 58 pm" src="https://user-images.githubusercontent.com/1325411/43402510-31e49e96-9413-11e8-9f29-175387d77fc6.png">
Again, I'm really concerning this issue! :)

**Comment by jijin** [comment]
I have disabled the Adult Disclaimer. Now i can able to view all. Thanks for your awesome support dear.Much appreciated.

**Comment by pH-7** [comment]
No prob @jijin ! 😊 
If you could leave a nice review on Sourceforge https://sourceforge.net/projects/ph7socialdating/ (you need to create an account) or just Star this github repo.
**It is something that would make me really happy!** and really help the software to get better 😃 


Have a wonderful week!

**Comment by pH-7** [comment]
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)
