### ISSUE TITLE
404 not found /admin123

### ISSUE THREAD

**Issue by DEATHJ0KER** [pH7Software/pH7-Social-Dating-CMS#255]
I state ... I'm not an expert!!! I installed the script on a host that does not have cpanel. It is working on the php version 7. The installation is successful, not specified or a specific folder and resides in the directory path "/". The home page opens, but you can not access the administration panel.

http://site.domain/admin123 return 404 :(  Error

Can it work equally on the PHP 7 version? 
Do I have to edit the .htaccess file?

I can not reproduce the error log file due to failure to access the settings. Where can I find this information?

**Comment by polynamaude** [comment]
@DEATHJ0KER Yes it works with PHP 7.

You need to use the enclosed htaccess file.

What about cPanel ? Learn manual configuration of Apache instead and you'll be good for every situation.

Check docs on www.ph7cms.com to rename the admin panel.

**Comment by polynamaude** [comment]
@

**Comment by DEATHJ0KER** [comment]
Of course, you are the genius, for me it's all difficult. I tried to install it with a click through Softaculous and only in the byethost hosts everything works correctly. Manually installing it on host Altervista, without CPanel, I set everything manually, at least what you can do. In their opinion it might work, but they can not tell me where the problem is born. They tell me that with such a large file as it is .htaccess, it is difficult for me to help. It works correctly when first installed, but does not open the control panel. I do not know what to do to solve... 

The site where it works is www.virtualxdating.epizy.com/admin123


The site where it not works is www.virtualxdating.altervista.org/admin123





Inviato da Posta per Windows 10

Da: Polyna-Maude R.-Summerside
Inviato: venerdì 3 agosto 2018 01:17
A: pH7Software/pH7-Social-Dating-CMS
Cc: Valentino Decaroli; Mention
Oggetto: Re: [pH7Software/pH7-Social-Dating-CMS] 404 not found /admin123(#255)

@DEATHJ0KER Yes it works with PHP 7.
You need to use the enclosed htaccess file.
What about cPanel ? Learn manual configuration of Apache instead and you'll be good for every situation.
Check docs on www.ph7cms.com to rename the admin panel.

**Comment by polynamaude** [comment]
@DEATHJ0KER Have you did like I told you in the other issue and checked with your hosting provider if they use modsecurity ?

**Comment by DEATHJ0KER** [comment]
I can give you the login details of the host where it was installed... Surely you understand the problem at first glance.

**Comment by DEATHJ0KER** [comment]
Host Login to https://www.altervista.org
username: virtualxdating
password: Nobody999

**Comment by polynamaude** [comment]
I am not going to do YOUR job. By the way, it's kind of dead stupid to publish your login details on a public place.

Start by asking your hosting provider if they use modsecurity. Don't abuse of the help people give you and do your share by helping yourself.

I'm not going to contact your provider. You don't understand that YOU HAVE TO WORK ?

Go out and read the docs plus ask about modsecurity like already said.

You're asking like someone who pay some thousand $ to buy MatLab. First call tech support to understand how to do install because can't use a shell prompt.

Afterward complain he can't do nice "drawing" but just bought a scientific calculus software without having even finished high school math.

Maybe there's some basic skills that you should work on.

**Comment by DEATHJ0KER** [comment]
Okay I close the question here. Traced scripts for 20 years, if you're not curious to solve this problem, leave it to do this as a job. I always helped everyone when they had problems with my scripts and eventually installed them without problems anywhere. That profile was created to solve the problem, as I said, your script can be installed using just one click in a single free host service. You have nothing to teach cats, they are able to climb on their own... It would be a nice idea to solve this mountain of problems LOL³ Thank you for your time.

**Comment by pH-7** [comment]
Hi @DEATHJ0KER 

Really sorry, just so it right now. Have you tried to uncomment https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/.htaccess#L23 line (in the root .htaccess file).

Finally, are you sure the mod_rewrite is correctly configured? https://ph7cms.com/doc/en/how-to-install-rewrite-module 
Do you have 404 error else where when with your website or is it only with /admin123 URL?

Thanks!

**Comment by DEATHJ0KER** [comment]
The problem is only on /admin123 | mod_rewrite work well

I opened a ticket to the host. The host has some limitations and requires the intervention of paid technical support regarding the installation of scripts. Not all scripts are allowed to install, the service has limitations. This is why it does not access the /admin123 administration page. I installed PH7 CMS successfully through free InfinityFree hosting with installation wizard. It works perfectly, does not present any problem. Free host recommended to easily install the script ---> InfinityFree https://infinityfree.net 
I do not use this script for profit, I have deactivated all the payment formulas of the service to be used freely.
P.S. Now I'm having trouble parking my domain on the host... Problems are being created in the hosts in the form of a promotion to their paid services. I like the free network!

Thank you for your precious time and for making available a script of such importance. 
If I like this script? Very very much.

Thanks again.

**Comment by pH-7** [comment]
What a shame! Indeed, please don't use free hosting companies. You can find very good ones (if you don't have much traffic) for just a few bucks per month (less than a coffee!)
I usually recommend WebFaction or others here https://ph7cms.com/doc/en/hosting

For the domain name, I usually recommend NameCheap or Name.com (they are awesome, and you can park/redirect your domain easily). I have no clue for yours... since your web host is free, I guess you can't if your domain is free. Otherwise, see with your domain registrar provider.

You're very welcome! If you could leave a nice review on [Sourceforge](https://sourceforge.net/projects/ph7socialdating/reviews/) (or just Star the Github repo, that would be AWESOME! 😃).


Good luck!

**Comment by DEATHJ0KER** [comment]
Treat instant messaging based on clients, therefore I do a lot of tests and I use many different hosts to practice with cms.
Of course, my domain is registered on NameCheap. When I have to park it in a free host it usually takes no more than 40 minutes. I had the dns aimed for over 4 days on InfinityFree host and even today he told me to set their DNS LOL³ :D

Check to see if my sourceforge review reflects the quality of your script.
Review by vxdscripts 

 I wish you a good job!!!

**Comment by pH-7** [comment]
You Rock @DEATHJ0KER! 🎉

**Comment by pH-7** [comment]
Hi @DEATHJ0KER 

Please try to go to YOUR-WEBSITE.com/admin123/setting/analyticsapi and remove the code there, then save it. Please also try to clear the cache, Admin Panel -> Tool -> Caches -> Caches Manager

**Comment by DEATHJ0KER** [comment]
Solved tnx u are awesome 💯 :

**Comment by pH-7** [comment]
Happy to hear that! 😊 Enjoy!
