### ISSUE TITLE
not open correctly after installing ssl certificate

### ISSUE THREAD

**Issue by vimgau28** [pH7Software/pH7-Social-Dating-CMS#268]
after installing ssl certificate page not open correctly how to adjust http://  to https://

loner.ml

**Comment by pH-7** [comment]
Hi there,

How you check your Apache's error logs? What's issue did you get? I couldn't reach your website.

**Comment by vimgau28** [comment]
website name is loner.ml

**Comment by pH-7** [comment]
Hi again @vimgau28 
Let me know if this works, so I can know if your problem is solved or if you need further help :smile: Thanks.

**Comment by vimgau28** [comment]
i am trying to remove  L 664- 665 but .htaccess file disapear from the
htdocs i am using free hosting thier is htaccess limited to 10kb

restricted to edit htaccess.
please tell me any soulution.

**Comment by pH-7** [comment]
Hi @vimgau28 
Please don't use free hosting companies. You will only have hassles.
You can find very good ones (if you don't have much traffic) for just a few bucks per month (less than a coffee!)
I personally use and usually recommend WebFaction or others here https://ph7cms.com/doc/en/hosting

**Comment by vimgau28** [comment]
on your directions i removed two lines L 664 to L665

 # RewriteCond %{SERVER_PORT} 80
 # RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

but nothing any effect site open without https:/

i want to ask one question at the time of installing we seleted http:// in
the url now how to change it to https://

i installed via softaculaous
domain name is loner.ml

**Comment by pH-7** [comment]
@vimgau28 

1. Maybe your .htaccess file couldn't be saved. Please ask your web hosting if there is something wrong. And like I said, you will have only problems with free hosts since there aren't compatible with pH7Builder (pH7CMS).
2. Like I told you, you can use .htaccess Apache file to automatically redirect your website from http to https. You should also be able to do it through cPanel (or ask your web host company).

Hope this helps!

**Comment by pH-7** [comment]
Hi @vimgau28!

1. I said to UNCMMENT these two lines, not removing them. Maybe I wasn't clear enough.
To uncomment them, you need to remove the dash `#`, which starts the line.
So, L 664 to L665 should look like:
```
RewriteCond %{SERVER_PORT} 80
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```
This should do the job.

And make sure the .htaccess file is correctly saved. Please ask your web hosting if there is something wrong. Finally, like I said, you will have only problems with free hosts since there aren't compatible with pH7Builder (pH7CMS).

2. Like I told you, you can use .htaccess Apache file to automatically redirect your website from http to https. You should also be able to do it through cPanel (or ask your web host company).

Hope this helps!

**Comment by pH-7** [comment]
Hi @vimgau28!

1. I said to UNCOMMENT these two lines, not removing them. Maybe I wasn't clear enough.
To uncomment them, you need to remove the dash `#`, which starts the line.
So, L 664 to L665 should look like:
```
RewriteCond %{SERVER_PORT} 80
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```
This should do the job.

And make sure the .htaccess file is correctly saved. Please ask your web hosting if there is something wrong. Finally, like I said, you will have only problems with free hosts since there aren't compatible with pH7Builder (pH7CMS).

2. Like I told you, you can use .htaccess Apache file to automatically redirect your website from http to https. You should also be able to do it through cPanel (or ask your web host company).

Hope this helps!

**Comment by vimgau28** [comment]
ok fine

**Comment by pH-7** [comment]
Don't forget to Star this Github repo as well
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)
@vimgau28

**Comment by pH-7** [comment]
Really happy if you figured it out 👏 
I'm closing this ticket by now. Please reopen a new one if you have another relevant issue.
