### ISSUE TITLE
Routes are not valid when on production server. URL & path changed

### ISSUE THREAD

**Issue by 000kelvin** [pH7Software/pH7-Social-Dating-CMS#273]
Hello devs, I got the Dating cms successfully up and running on my localhost and everything worked perfectly well. I then pushed it online to my production server (through cpanel) and setup all configurations but everything seemed disfigured. All links also returned error 404. 
I even installed the cms directly on my production server but it produced the same result. 
I'd love any help, thanks.

**Comment by pH-7** [comment]
Hi @000kelvin 

Since [v12.1](https://ph7cms.com/ph7cms-12-1-released/), all URL lookups from the router are cached.

Because you changed the website URL, please try to remove `/_protected/data/cache/pH7_cache/str/uri/` folder. This folder will be regenerated and the cached URIs recreated.

Finally, if you wish, you can disable this feature by changing the `Uri:: URI_CACHE_ENABLED ` constant to false https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/framework/Mvc/Router/Uri.class.php#L25 

Hope this helps!

**Comment by 000kelvin** [comment]
I got it sorted out, thank you for your support.

**Comment by pH-7** [comment]
You’re welcome @000kelvin

If you are happy with my benevolent support and by the software I did, it will be very nice of you to give a nice review at https://sourceforge.net/projects/ph7socialdating/

**Comment by pH-7** [comment]
Really happy for you 😊
If you are happy with the support and the software, it will be very nice of you to give a nice review at https://sourceforge.net/projects/ph7socialdating/ (it really helps and motivates me!)

**Comment by pH-7** [comment]
Really happy for you @000kelvin 😊
If you are happy with the support and the software, it will be very nice of you to give a nice review at https://sourceforge.net/projects/ph7socialdating/ (it really helps and motivates me!)
