### ISSUE TITLE
webpage won't show properly

### ISSUE THREAD

**Issue by CharleeHan** [pH7Software/pH7-Social-Dating-CMS#284]
My pH7-Social-Dating-CMS site will not show properly. Please visit at myvegandate.uk to see the problem.
Please advise.

Thanks

**Comment by juandpr** [comment]
Your assets are under HTTPS, but your website is under a non secure HTTPS. I think that might be the issue

**Comment by CharleeHan** [comment]
What do you mean assets, please?

**Comment by CharleeHan** [comment]
The site is on a Ubuntu 18.04 server.

**Comment by juandpr** [comment]
Sorry, with the assets I mean the CSS files and JS files. I can't reach the site using HTTP

**Comment by CharleeHan** [comment]
I am going bed now. Speak to you later. Thanks.

**Comment by pH-7** [comment]
@CharleeHan Please keep in mind that this is a volunteer support.

Your asset files are empty (e.g. http://myvegandate.uk/asset/gzip/?t=css&d=templates/themes/datelove/css/&f=common.css,style.css,layout.css,menu.css,like.css,color.css,form.css,js/jquery/rating.css,js/jquery/apprise.css,js/jquery/tipTip.css). That's why it doesn't show properly.

It seems you have issues with cURL. Maybe your server blocks external requests. Basically, pH7CMS will fetch all CSS/JS files externally with cURL, then compress them with `gzencode` and store them in `_protected/data/cache/pH7_static/` folder to give faster delivery.

However, for some reason, something blocked it on your website. If you use a shared web hosting, please contact them asking to investigate this issue concerning cURL and make sure there are no security software that might block cURL or external websites.

Once this is fixed, please delete all static files cached in `/_protected/data/cache/pH7_static/*`, otherwise the static files (css/js) won't be updated (you should also be able to remove the Static Cache though the Admin Panel https://ph7cms.com/doc/en/how-to-clear-caches).


Hope it helps!

**Comment by pH-7** [comment]
BTW, other similar solved issue that might help you: 
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/106 
Or even https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/%5BDRAFT%5D-Problem-Getting-Assets-(CSS-JS)-cURL (from someone who had a similar problem than you).

You should have everything in your hand to solve this problem by now. I don't see what else I can give you to solve the problem... 

P.S. In case you do, please follow these instructions if you plan to move your website from http to https: https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-redirect-pH7CMS-from-HTTP-to-HTTPS 

Please reopen it in case the problem was from something else...

**Comment by CharleeHan** [comment]
Hi Guys,
Just deleted the content of /_protected/data/cache/pH7_static/* and refreshed the page. The result is a working site (No any changes made - http and https). Thanks for the advise.

**Comment by polynamaude** [comment]
Hi,
Cross Origin Request Security (CORS) prevent mixing http/https when including javascript as it's considered "another site" because it's not on the same port. Same rule as AJAX

On September 4, 2018 8:52:22 PM EDT, Juan Dalmasso <notifications@github.com> wrote:
>Your assets are under HTTPS, but your website is under a non secure
>HTTPS. I think that might be the issue
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/284#issuecomment-418563510

-- 
Polyna-Maude R.-Summerside
