### ISSUE TITLE
Change or add registration questions?

### ISSUE THREAD

**Issue by Savaena** [pH7Software/pH7-Social-Dating-CMS#286]
I would like to add and change some of the questions on the registration screen, such as "I am a man/woman/couple" etc.

Where do I go to do that?

**Comment by itbob1** [comment]
I would like to do the same as Savaena. How do we change and add questions?

**Comment by benhartwich** [comment]
Would also be in my interest.

**Comment by benhartwich** [comment]
Would also be in my interest

**Comment by polynamaude** [comment]
You edit the underlying code for the form. It's pretty much commented in the PHP source code.

**Comment by benhartwich** [comment]
> You edit the underlying code for the form. It's pretty much commented in the PHP source code.

And how can I ensure, that these customizations are available again after an update? Perhaps there should be any kind of customizer at the admin area, which would make it much more easier.

**Comment by polynamaude** [comment]
Perhaps their shouldn't be any war in the world ?
There's nothing that prevent you from writing such a module !
Just a question ? How many hours do you think it took to write to whole framework plus content management ?

You do two things if you want that it stays after update.
First, you make a copy of the repo with git. You write your code in a branch and make a Pull Request. Then Pierre-Henry will include it in the distribution when he has time do to so.

Or you make your code in a branch and later on make a local merge request. This will push your modification onto the new code. You'll have to do this before applying the update.

**Comment by benhartwich** [comment]
@Savaena I think this rude answers were posted because of my direct questions. But I think this kind of communication is quite normal at github. So never mind and look further.

**Comment by polynamaude** [comment]
No my answer was straight forward because people don't seem to understand the time involved in developing software and to do it for free. So when they say "it should, it should, it should" then it get nothing more than annoying.

For sure, that would be a wonderful thing that software development is done through Artificial Intelligence and yes we're getting there ! So we get self coding system, ain't that great ?

For the answer @Savaena, I never saw a software that is so self described when you look into the source code. Pierre-Henry really did something wonderful at documenting the source code. It follows exactly the Object Oriented Model based on Design Pattern. So if you want to get a deeper understand of how the pieces fits together then you can look for the book "Element of reusable software patterns" by the Gang of Four. Not sure the exact name but if needed I can check in my library to give it out.

There's nothing rude in saying that there's a line between what we'd like and what is done.

Yes there could be a customizer in the admin area, there could also be a real time live chat inside the CMS itself but I haven't had the time to finish it. Yes, we're all volunteer here ! So lots of things would be great.

So if you're a self taught person, then great ! You know what the word effort mean, so think about Pierre-Henry who did around 14 000 lines of code to get it where it is now.

You talk about your website that is basic. How'd you feel if I'd go see it and say "Well it should be responsive, would make it easier to look on my tablet / cellular phone / wide screen / small screen / Text-to-speed. Oh and by the way, you don't respect the General Data Protection Regulation and you accept people from Europe, that's pretty bad ! And how about if I get on about the American with Disability Act / Europe Accessibility Regulation, your site is far from being easy to access when you are blind :(

I'm pretty sure your answer would look like "Hey, I do my best ! And you should note that what you'd like and what's possible is rarely the same". So me too I pray for the end of war.

If you make modification, you can always follow them to Pierre-Henry by using a Pull Request and he's gonna put it into the next release if it's something that's worth to be used by everyone.

And honestly, if you didn't like what I said, well I can't say more than sorry. But that's life and that's pretty much nicer than what you would get on most developer mailing list. Google RTFM if you want a hint ;-)

So a simple answer, is yes you can do customisation and as you get an idea of how hard things are when you do programming. As it's never, well the computer think and does it right, no you have to think about all the possibility. Then you can understand why, there's no such thing as a easy click-click-click website done.

Anyway, all website that are done just by using a mouse only design either all look the same, are pretty bad on optimisation or simply don't do much.

**Comment by Savaena** [comment]
Firstly, I am not 'people'. I am an educated person who makes full attempts to learn what I'm able to within my own limits before I ever try to reach out for help. 

Second, you misunderstood by what I said about 'basic' - as in my knowledge and understanding of programming is basic. You're suggesting I read the source code. I do not know where this is and do not have time to go in depth and become a programmer myself.  The only thing I wanted to know was where in the coding I needed to look to change something. I didn't come here for a condescending lecture.

Third, you have no idea how I would respond to criticism on my website so do not dare to assume. If you were to tell me those critiques above, I would strive to make those changes happen. And in fact my website is responsive, GPDR compliant, and TTS friendly. Unlike some people in this conversation, I actually do value criticism, even though I never offered any of my own criticism in this thread at all. I just asked an innocent question that you took the wrong way and ran with it.

How are people supposed to learn if they do not ask a question?

At this point, I'll consider my pH7-Social-Dating-CMS Pro License a financial loss and move on. It's completely obvious I won't find the answer I need here. 

Also, WTF is your deal with comparing this discussion to war? Very inappropriate and awkward....

**Comment by polynamaude** [comment]
First, there's no such thing as a "pro" version. The software is now totally from and as been for a while. I don't know why people still talk about a paid version. It's possible that there's still some old documents laying around.

Second, if you really want to learn how to customise then some things will need to be mastered at least at the basic level. I'm pretty sure that Design Patterns concept won't be too much of work for you, if you did some superior education (and that's no way of speaking for high above, it's what's called everything done after a college degree). The design patterns concept is something imported for the architectural world into computing in the late 70, early 80s. It's a uniform way to solve known problem with known solutions, for example you can search "MVC" and you'll see what's the Model-View-Controller pattern. This one is used in pH7CMS. It's one of the way all the objects that build the system can fit together.

Start with the main file (index.php / index.ph7) and from there follow the flow of the request. That should be a good start. I'll check the exact name and line number of the files for specific modification needed.

I didn't compare the discussion to war, what I said is something really common "We'd all like to have world peace". And if you don't like it, well, that's your problem. It's a sentence I used quite often, nearly every day. As I teach at a local university at the Master level, I often need to remember my students to keep it to what's needed and don't do too far. So I simply tell them "Hey guys, we're not going to solve the problem of wars in the world today, either are we going to get world peace in the next 24 hours. ".

People = persons, so yes you're part of people. Maybe in the country you live in, not many person have education or your lifestyle, that's not part of what I know or what I need to know. But until I get more knowledge, you're part of people and everyone that are quite unknown to myself.

You may have suffered much in your life and probably still do suffer, Cancer ain't something easy to go through and can create much anxiety. But more and more people get through and live a quite normal life after. Without taking away any of what you may be suffering, it doesn't make it something others have to know in you day to day interaction. You don't know who else you're talking too, not even if the persons (more than one on this thread) that are reading you may have similar suffering or even worst (Cancer and live in Central Africa without a penny in stock, for example). I'm not saying it doesn't mean you're not having any suffering, I'm just saying it doesn't change nothing to how interaction will happens on such a mailing list.

You seem to be really picky on every word people say, maybe you should take into consideration what the other speaker said on the thread. Maybe you should consider that not everyone will interpret what you say in the same way. For me a basic web site, it's playing shit old HTML4 without JS and not responsive at all. And same goes for how you may interpret what I'm saying.

As you closed the thread, I won't make research into the file to see the exact places of the requested feature change. If needed you can leave a message.

Cheers and good luck for the feature, may god save you (if you believe in god).
