### ISSUE TITLE
Users can't contact admin

### ISSUE THREAD

**Issue by Mobiller** [pH7Software/pH7-Social-Dating-CMS#290]
Hello Again
I send a member (tester) a message as admin and when he tried to reply to the admin via message he couldn't, instead said to use contact us.
Can that be changed
![issue](https://user-images.githubusercontent.com/43084373/45251323-0cdcb280-b33c-11e8-94d3-6c4f42e477be.jpg)

**Comment by pH-7** [comment]
This is done on purpose. Admins cannot handle messages.
Otherwise, you would have lots of messages from users, etc. (you don't want that; You need to save your time as much as possible and not shooting the breeze). 

Admins aren't there to communicate with users, but they can send messages to them to inform about something (the message should be specific enough, so users won't have to reply to you).

If you want to chat with users, just create a user profile for that or email them (you have the email address of each user on the User Browse Page. 
FYI, I added a mailto link on each email, so admins can email users even easier (https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/3f237aa9917e22f7effc0b32b77609cd6fdbdec8). This will be available in the next release.
