### ISSUE TITLE
unable create add new membership

### ISSUE THREAD

**Issue by CharleeHan** [pH7Software/pH7-Social-Dating-CMS#294]
Hi,
Please see error message below.
![image](https://user-images.githubusercontent.com/34712470/45354887-c941ad00-b5b6-11e8-942b-650ff779caf0.png)

**Comment by pH-7** [comment]
Hi @CharleeHan 
Thanks for letting me know this. This is apparently due to your current MySQL configuration (which is different than mine). Anyway, that SQL field isn't used anymore by the CMS.

Can you run the following code through your phpmyadmin
```sql
ALTER TABLE ph7_memberships DROP COLUMN orderId;
```
Note: Change `ph7_` by the prefix your other tables have, if different (you have normally chosen the prefix for the database tables during the installation).

**Comment by pH-7** [comment]
I will publish a patch for it, which will be available in the next release (v14.3).

**Comment by CharleeHan** [comment]
deleted the column and it worked. Thank you.

**Comment by pH-7** [comment]
For the record, I added a fix here https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/c53634ba241877026094948661e2f2e34b050a0b
It will be available on v14.3
