### ISSUE TITLE
Adding/Creating Links

### ISSUE THREAD

**Issue by Mobiller** [pH7Software/pH7-Social-Dating-CMS#300]
How can I use smartlinks to create links on my site?

**Comment by polynamaude** [comment]
The same way as any other website ? Either you dive into brain feeding yourself and get a understanding of how the routing works and URL are made or you go to the page you wanna link and do a copy/paste of the URL.

I think that's quite obvious when you got what it takes to run a website and not only do install and wonder why your site is like everyone else plus as added bonus get hacked by users because you didn't know much more than to do a "click next/default value/why change seed?". Anyway it's basicly www.mysecurehost.com/(module name) or www.mysecurehost.com/(user name).

Code is heavy commented so look into the routing scheme.

On September 17, 2018 8:12:32 AM EDT, Mobiller <notifications@github.com> wrote:
>How can I use smartlinks to create links on my site?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/300

-- 
Polyna-Maude R.-Summerside

**Comment by Mobiller** [comment]
> The same way as any other website ? Either you dive into brain feeding yourself and get a understanding of how the routing works and URL are made or you go to the page you wanna link and do a copy/paste of the URL. I think that's quite obvious when you got what it takes to run a website and not only do install and wonder why your site is like everyone else plus as added bonus get hacked by users because you didn't know much more than to do a "click next/default value/why change seed?". Anyway it's basicly [www.mysecurehost.com/(module](http://www.mysecurehost.com/(module) name) or [www.mysecurehost.com/(user](http://www.mysecurehost.com/(user) name). Code is heavy commented so look into the routing scheme.
> […](#)
> On September 17, 2018 8:12:32 AM EDT, Mobiller ***@***.***> wrote: How can I use smartlinks to create links on my site? -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #300
> -- Polyna-Maude R.-Summerside

Hello and Thank very much for your input, much appreciated
