### ISSUE TITLE
Module development

### ISSUE THREAD

**Issue by graceryfolad** [pH7Software/pH7-Social-Dating-CMS#308]
hello, good work done on this script. i will like to add some functionalities to this script via the module.
please how do i develop modules in ph7cms.

**Comment by pH-7** [comment]
Well, if you are a developer and have good knowledge of PHP, you can learn easily how to add new feature. Firstly, pend some time to learn how pH7Builder (pH7CMS) works, and I suggest having a look to the [helloworld module](https://github.com/pH7Software/pH7-Social-Dating-CMS/tree/master/_protected/app/modules/helloworld). I made it to help other devs to know how to create a basic module and how a module in pH7Frameworks's architecture looks like.

Otherwise, just hire a good PHP programmer, and if possible with working knowledge of pH7CMS or other MVC frameworks (Toptal.com should be a good place to start).
UpWork as well, however I've heard that it's harder to find good devs there, with good practices and clean code).

In my case, I don't want to take custom development projects at the moment.

Good luck!
