### ISSUE TITLE
General Settings save error

### ISSUE THREAD

**Issue by therooster2002** [pH7Software/pH7-Social-Dating-CMS#327]
Hi I keep trying to make changes to my new installation under General settings / Global settings and keep getting the same error message when i click save 
403
Forbidden
Access to this resource on the server is denied! 
Please help  I am not that experienced with servers or software any help would be appreciated 

Regards

**Comment by pH-7** [comment]
Hi @therooster2002 

Can you please disable `mod_security` (or ask your web host to do so for you) and try it again.

**Comment by pH-7** [comment]
Like I wrote in the requirements page

> mod_security/mod_security2 disabled - pH7CMS may not work correctly if enabled so we advise to disable it for your domain (just ask your Web host or do it through cPanel).

**Comment by pH-7** [comment]
Please let me know @therooster2002 if this did the trick?

**Comment by therooster2002** [comment]
> Please let me know @therooster2002 if this did the trick?

It did!! Thanks very much and sorry for not seeing i had to turn that off!! I am trying to work out how to use the chat side of your site as that is what I am really interested in but i can find no access to the chat as admin to get into the setting, Am i just stupid ?

**Comment by pH-7** [comment]
Really happy it works @therooster2002 😀
Concerning the chat, you are not stupid. There is no admin panel, since the software uses a third-party provider in order to make your website faster and decrease CPU usage of your Web server.

You can change the chat at anytime by going to Admin Panel, -> Settings -> API -> Chat API
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-change-the-Chat-in-pH7CMS

P.S. If you are happy with the support and the software, it will be very nice of you to give a review at https://sourceforge.net/projects/ph7socialdating/ (and even to Star this Github Repo on the top of the page).
It really helps and motivates me!

**Comment by pH-7** [comment]
@therooster2002 Hopefully, you will be able to log a review for me 🤞

BTW, I wrote an article that helps tens of pH7Builder's holders to build a successful niche and I'm sure it can help you too if you haven't found a specific niche yet. The article is: https://ph7cms.com/10-excluside-niche-ideas-for-your-dating-web-app/ :trophy: And even this one https://ph7cms.com/make-dating-service-magic/

**Comment by pH-7** [comment]
@therooster2002 Hopefully, you will be able to log a review for me at https://sourceforge.net/projects/ph7socialdating/ 🤞

BTW, I wrote an article that helps tens of pH7Builder's holders to build a successful niche and I'm sure it can help you too if you haven't found a specific niche yet. The article is: https://ph7cms.com/10-excluside-niche-ideas-for-your-dating-web-app/ :trophy: And even this one https://ph7cms.com/make-dating-service-magic/
