### ISSUE TITLE
Reinstall while keeping database data intact

### ISSUE THREAD

**Issue by kirenpillay** [pH7Software/pH7-Social-Dating-CMS#354]
My installation has been corrupted after a mistake I've made: I didn't realise that my _protected folders was in out of the /var/www folders and with every pull from git I wasn't moving this code. 

What I've done is upgrade the database from 12.9.8 all the way up to 14.3.6 (which is master).

1. Would it be possible for me to do a brand new installation of the software while pointing to the existing DB? i.e. If I run the install script, will it leave my existing data and information intact?
2. Can I install 14.3.4 even though the db has been upgraded to 14.3.6?

**Comment by pH-7** [comment]
Hi @kirenpillay 
So, please download the latest master version (https://github.com/pH7Software/pH7-Social-Dating-CMS/archive/master.zip), because the one currently on Sourceforge is 14.3.4 (14.3.6 is a kind of "preview" without official releases).

Then, do the installation with the installer, and when you are ask to specify a database name, use a dummy one (or simply change the database prefix to a different prefix that doesn't exist in your database).

Once you finished the installation, open `_protected/app/configs/config.ini` and change at line 41 `name = "YOUR_DUMMY_DB"` to your previous database.

Hope this helps!

**Comment by kirenpillay** [comment]
I am doing this now, I've done the composer part to install vendor modules,
however the following folders are missing from the downloaded ZIP. Is this
correct?

~/YOUR-PUBLIC-FOLDER/_repository/module/*

~/YOUR-PUBLIC-FOLDER/_repository/upgrade/*

**Comment by kirenpillay** [comment]
I'm getting the following error:
"/usr/local/share/applications/ph7cms/_protected/app/configs/config.ini"
config file cannot be found.

My httpd error log is
[Tue Nov 13 10:19:54.993960 2018] [php7:error] [pid 41316] [client
66.249.64.158:38463] PHP Fatal error:  Uncaught Error: Class
'PH7\\Framework\\Server\\Environment' not found in
/usr/local/share/applications/ph7cms/_protected/app/Bootstrap.php:129\nStack
trace:\n#0
/usr/local/share/applications/ph7cms/_protected/app/Bootstrap.php(80):
PH7\\Bootstrap->loadInitFiles()\n#1 /var/www/
xyz.co.za/pH7-Social-Dating-CMS/index.php(46): PH7\\Bootstrap->run()\n#2
{main}\n  thrown in
/usr/local/share/applications/ph7cms/_protected/app/Bootstrap.php on line
129, referer: https://www.xyz.co.za/new-profile/65

Indeed there is not config.ini file, somehow the app thinks I am past the
initial installation? [could it be the missing modules folder causing this?]

**Comment by kirenpillay** [comment]
Hi Pierre-Henry

Your recommended solution worked, I am back online! 

Thank you!
