### ISSUE TITLE
Robot.txt for PH7 builder

### ISSUE THREAD

**Issue by chalit9999** [pH7Software/pH7-Social-Dating-CMS#376]
Hi i'm using PH7 builder 14.7.0   is this robot.txt  the right one ?   Thankssss
####################
# Nav Doc Script (by Pierre-Henry Soria)
# URL: https://github.com/pH-7/Nav-Doc-Script-V2
#
# To work, this file has to be in the root of the domain (e.g., doc.ph7cms.com)
####################

# Don't index the get params to avoid duplicate contents due to the URL rewriting
Disallow: /*?*

**Comment by pH-7** [comment]
No, the one you posted is from https://github.com/pH7Software/pH7-Documentation

The correct one is https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/robots.txt
You have it already on your website, since it is included by default. You shouldn't bother you with it, it isn't really important :)
