### ISSUE TITLE
is it possible to make top menu bar taller to fit larger Logo?

### ISSUE THREAD

**Issue by chalit9999** [pH7Software/pH7-Social-Dating-CMS#379]
i just wonder if it's possible to make top user's menu taller to fit a larger logo and fonts too ?

**Comment by polynamaude** [comment]
Do you edition on a git repo, commit every change you make so you can undo.
Look in the template folder.
If I have time, I'll try to find the exact line for you. But can't make promise there.

**Comment by chalit9999** [comment]
that's nice of you, i'll git repo,   i understand your time is precious, but still hope you will have time to find this line for me, Thanks

**Comment by pH-7** [comment]
Have a look here https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/templates/themes/base/css/common.css#L47-L54 

Please note that once you change the css file (if it's not the base template), you will need to clear the static cache, *Admin Panel -> Tool -> Caches -> Caches Manager -> Static Files*

https://ph7cms.com/doc/en/how-to-clear-caches

**Comment by pH-7** [comment]
buy the way @chalit9999 , in order to help the software and to support you, don't forget to Star the repo as well 😊 And if you have time, review the project on Sourceforge https://sourceforge.net/projects/ph7socialdating/  (it takes just one minute).
You will need an account to do so, but it really helps me and motivates me a lot to continue this project :)
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by pH-7** [comment]
@chalit9999 , if you appreciate the software I build and the support provided, don't forget to review the project on Sourceforge https://sourceforge.net/projects/ph7socialdating/  (it takes just one minute). Thanks a lot! I really appreciate it. Any help needed, just let me know at anytime :)

**Comment by pH-7** [comment]
@chalit9999 , if you appreciate the software I build and the support provided, don't forget **to give a review on Sourceforge** https://sourceforge.net/projects/ph7socialdating/  (it takes just one minute). **It really motivates me to continue the project**. Any help needed, just let me know at anytime :)
