### ISSUE TITLE
pH7CMS installation errors

### ISSUE THREAD

**Issue by SMN-Sam** [pH7Software/pH7-Social-Dating-CMS#382]
hello,
While installing pH7CMS it stops as soon as it reaches 28.6% of the process.
any ideas, please?

**Comment by pH-7** [comment]
Hi @SMN-Sam 
Can you be more specific. What errors do you see there? Can you check if there are any log files in `_install/data/logs/`?
If so, please let me know the exact error message.

Without it, I won't be able to help you further unfortunately.

**Comment by SMN-Sam** [comment]
hello)
thanks a lot for your kind reply.
I finally could fix everything))
One thing that I couldn't find if it is possible to have a multi language
site, I mean the language changes in accordance to the country.

**Comment by pH-7** [comment]
Really happy to hear that!
Yes, I replied to you here https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/386 😊

P.S. Don't forget to Star this repo
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

Have a great weekend!

**Comment by pH-7** [comment]
FYI, I replied to your other question here https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/386 😊
AND don't forget to Star this repo
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

Have a great Sunday @SMN-Sam

**Comment by SMN-Sam** [comment]
hello)
thanks a lot for you kind reply.
Just got another question)) can i disable the option Couple, just to have man or woman?
thanks

**Comment by pH-7** [comment]
Very good. 
To remove the "couple" option, please remove the following highlighted lines in the code

### Join Form
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/e1b4913b8a40232fb9629da91b48ede04e185823/_protected/app/system/modules/user/forms/JoinForm.php#L101

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/e1b4913b8a40232fb9629da91b48ede04e185823/_protected/app/system/modules/user/forms/JoinForm.php#L114

### User Edit Form
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/89a8b5fbfb769fcf5fa8493e9b7b3b6657436fab/_protected/app/system/modules/user/forms/EditForm.php#L79

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/89a8b5fbfb769fcf5fa8493e9b7b3b6657436fab/_protected/app/system/modules/user/forms/EditForm.php#L93

### Quick User Search From
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/89a8b5fbfb769fcf5fa8493e9b7b3b6657436fab/_protected/app/system/core/forms/SearchUserCoreForm.php#L57

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/89a8b5fbfb769fcf5fa8493e9b7b3b6657436fab/_protected/app/system/core/forms/SearchUserCoreForm.php#L69

### Advanced User Search From
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/89a8b5fbfb769fcf5fa8493e9b7b3b6657436fab/_protected/app/system/core/forms/SearchUserCoreForm.php#L108

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/89a8b5fbfb769fcf5fa8493e9b7b3b6657436fab/_protected/app/system/core/forms/SearchUserCoreForm.php#L120

Next time (in order to keep the thread cleaned), please create a new issue, since it is a different problem than the initial one.
