### ISSUE TITLE
Trying to create an api to the backend

### ISSUE THREAD

**Issue by anurupr** [pH7Software/pH7-Social-Dating-CMS#389]
I'm trying to create a small api which i can use to connect to the backend. I would like to build my own frontend but using the backend provided by this project. 
But I am not able to include the core classes in my script.
I have setup a script called api.php

`<?php
namespace PH7;
require __DIR__ . '/_protected/vendor/autoload.php';
define('PH7', 'SomeDefaultValue');
require __DIR__ . '/_constants.php';
require PH7_PATH_APP . 'Bootstrap.php';

$oApp = Bootstrap::getInstance();
/* i required all the classes required by UserCoreModel.php */
?>`

But obviously this isn't the way to go. I'm not sure what i'm doing wrong

**Comment by pH-7** [comment]
Hi there! 👋 

Excellent choice! Like you probably noticed, pH7CMS is the most powerful and secure social dating framework available on the market. And beside of that, it is 100% open source (and of course, free).

Indeed, that’s not the way to do it. You want to build a RESTFul API? Why would you want to create something beside pH7CMS? 

Everything should be done into pH7CMS, and it will handle the HTTP requests for you and the wanted output (e.g. JSON).

So, the right way is to build a pH7CMS’s module that does this job.

Finally, please note that pH7CMS already has an API module available.
See here: https://github.com/pH7Software/pH7-Social-Dating-CMS/tree/master/_protected/app/system/modules/api
And for some helpful information about how to use it: https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-To-Use-the-RESTful-API-and-Add-new-Endpoints

So, you can simply use it instead of reinventing the wheel, and add more endpoints in its controllers (or create a new controller if that data you want to retrieve is different than "user" stuffs, in order to keep things clear).


P.S. The "api" module is still like "beta" version, however if you find something wrong, feel free to open a PR with the fixes (and open an issue if you don’t understand something). 

Hope this helps! 😊 Good luck! 🍀
