### ISSUE TITLE
Mobile redirect on login landing page

### ISSUE THREAD

**Issue by WolfDaddy** [pH7Software/pH7-Social-Dating-CMS#395]
I just installed ph7_social_network using Softaculous through the C-Panel provided by my Webhost and landing/login page redirects mobile users to url m.xvideo.com. I'm assuming that someone has managed to insert some malicious coding into your repository and thought you should know about it. My site is https://CumForDaddy.net if you want to see for yourself. It doesn't redirect desktop traffic, it only redirects mobile traffic. As I've only just installed your repository and I haven't had an opportunity to familiarize myself completely with the admin panel, nor comb through your script to see if I can find the redirect myself. I may just uninstall and then try to reinstall by git cloning instead of through Softaculous to see if that makes a difference. Perhaps you can take a quick look to see if you can find and remove the mobile redirect then let me know so I can do a clean install? It would be greatly appreciated.

Thank You.

And Kudos for what seems to be an incredible social networking program you've created. Thanks for all your hard work.

**Comment by pH-7** [comment]
I checked your website, and couldn't see anything wrong. Maybe you already fixed the issue...

I think, the problem is that you enabled the "Adult Disclaimer". 

On the settings page, there is a red warning saying that you have to be careful before enable it. 
HOWEVER, this SHOULDN'T redirect you to another website like this! I will see with the third-party provider, otherwise I will remove it from the software. Once you log in, please disable it in order to avoid this issue again (Admin Panel -> Settings ->  Adult Disclaimer).
<img width="950" alt="screen_shot_2018-07-30_at_4_07_51_pm" src="https://user-images.githubusercontent.com/1325411/43402450-0b5edb38-9413-11e8-9b02-e498fe94d963.png">

**Comment by pH-7** [comment]
Really happy if you like my software 😊
If you are happy with it, could you leave a nice review on Sourceforge https://sourceforge.net/projects/ph7socialdating/ (you .
**It's something that really motivates me to continue the development of this project!** and really help the software to get better 😃

**Comment by pH-7** [comment]
@WolfDaddy Since you didn't get back to, I assume this issue is solved and can now be closed.
