### ISSUE TITLE
Homepage opens without style:

### ISSUE THREAD

**Issue by SMN-Sam** [pH7Software/pH7-Social-Dating-CMS#399]
When I open my page through the localhost, it reveals without any style, same as to turn off all css commands.

**Comment by polynamaude** [comment]
Do you have modsecurity-crs installed on your host ?
That may be a big part of the problem you are facing.

**Comment by SMN-Sam** [comment]
no i don't. 
I just use Windows 10, have installed WAMPSERVER & the last version of ph7cms.

**Comment by pH-7** [comment]
@SMN-Sam Is it a fresh installation? Did you do some changes? When you click on a link on your website, does it give a 404 error? 

Have you tried to clear the Static file through Cache Manager? https://ph7cms.com/doc/en/how-to-clear-caches


It might seem a lot of questions, but needed in order to help you 😉

**Comment by SMN-Sam** [comment]
hello,
If I uninstall WAMP & delete all the files of ph7cms & reinstall, will it be helpful?
