### ISSUE TITLE
SQL Issue

### ISSUE THREAD

**Issue by pepsi4u2** [pH7Software/pH7-Social-Dating-CMS#407]
Users get this error when trying to edit their profiles:

Internal Server Error

The server encountered an error. This is most often caused by a scripting problem, a failed database access attempt, or other similar reasons.

If you are the administrator of the site, please go to your admin panel -> Tools -> Environment Mode and set to "Development", then go back here to see the details of the error. 

In development mode the response is:

Message: | SQLSTATE[01000]: Warning: 1265 Data truncated for column 'sex' at row 1
-- | --
File: | /home/leatha5/public_html/loveinthe21st.com/_protected/framework/Mvc/Model/Engine/Record.class.php
Line: | 206

**Comment by pH-7** [comment]
Hi @pepsi4u2 

What version do you use? lower or equals to 14.8.0?
Or 14.8.8 / 14.8.9?
There are SQL changes from version 14.8.8~14.8.9

Finally, what's your MySQL version?

**Comment by pH-7** [comment]
Hi again @pepsi4u2 
I tried to reproduce the issue for you, and don't have that problem.

Are you logged as an admin when you get that problem? Because, normally users cannot change their gender (for security reason), so it's strange you get that problem.

Or, maybe you are running an old version of the software and users are still able to amend their genders.

**Comment by pH-7** [comment]
@pepsi4u2 Is this issue still relevant? Have you read my above comments?

**Comment by pH-7** [comment]
Is this still relevant @pepsi4u2? Please be as specific as possible, thanks!

**Comment by pepsi4u2** [comment]
Nope I dumped ph7 … Couldn’t get many areas to function correctly…

**Comment by pH-7** [comment]
Very good! Thanks for letting me know @pepsi4u2 :)
