### ISSUE TITLE
Google map issue

### ISSUE THREAD

**Issue by chalit9999** [pH7Software/pH7-Social-Dating-CMS#412]
on my page the map shows as below is it my api key or something else?  Thank

" This page can't load Google Maps correctly
Do you own this website?  " 
 OK

**Comment by pH-7** [comment]
Google did recent changes and now you need to setup the billing info as well to be valid (otherwise, your Google API key won't work).
https://developers.google.com/maps/documentation/geocoding/usage-and-billing

Probably, your account isn't setup correctly. I believe that's the reason why it doesn't work correctly.

Please also check this related thread -> https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/302

Another option, is to just disable the Google Maps (Admin -> Mods -> Enable/disable modules -> uncheck "Google Maps").

**Comment by pH-7** [comment]
@chalit9999 Is this still relevant. Can you close it if it's solved?
