### ISSUE TITLE
Data too long for column 'metaKeywords'

### ISSUE THREAD

**Issue by loryel** [pH7Software/pH7-Social-Dating-CMS#418]
When I change language, I get this error.

Message: | SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'metaKeywords' at row 1

**Comment by pH-7** [comment]
Hi @loryel 

Where did you get the Korean translation? Since I didn't receive any requests to add it at https://github.com/pH7Software/pH7-Internationalization

For your information, your problem is caused because the number of characters exceeds the maximum length allowed for `metaKeywords` SQL field. You will have to remove some words there 😼

**Comment by loryel** [comment]
Thank you for your replying.

But I'm sorry, it is actually copy of English, not Korean.

I only changed file name from en_US to ko_KR and some contents in it.

And then I got the error.

Unfortunately I don't know how to edit metaKeywords.

diff -ruN en_US/config/config.ini ko_KR/config/config.ini
--- en_US/config/config.ini     2018-12-23 05:06:02.000000000 +0000
+++ ko_KR/config/config.ini     2019-01-22 06:02:40.933076376 +0000
@@ -1,7 +1,7 @@
 [language]
 ; The prefix of the language: English = en, Italiano = it, Español = es, ...
 ; You may also be more accurate EX: English in United States = en-US, English in Great Britain = en-GB, ...
-lang = en
+lang = ko

 ; ltr = Left to right language (English, Italiano, Español, ...) | rtl = right to left language (Arabic, Hebrew, ...).
 dir = ltr

**Comment by loryel** [comment]
If you mean metaKeywords is "Meta Tags/Homepage Texts", it has default values.

And the other options remain as installed.

I only changed directory name and some contents as above.

**Comment by loryel** [comment]
It was only mysql error.

Thank you very much for your replying.

**Comment by pH-7** [comment]
No problem at all @loryel 
You are very welcome!

Actually, I've found an issue in the software too according to the exception message you posted (before you edited your message).
I was caused by the new varchar length (https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/8014e83c86b1bc6422f102f9be1e2ccb03c382ef#diff-1b88df76554e8b5c9f766a632d5cd3ba) updated for `utf8mb4` compatibility. 

I will submit a patch for it.

**Comment by pH-7** [comment]
Patch: https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/7a83235c1eab6b5f6278aaea27598979582b894a

Now, the default metaKeywords's values (generated when a new language is added to the system) won't be more than 191 characters long.
