### ISSUE TITLE
system hang, need License Key

### ISSUE THREAD

**Issue by alvin101** [pH7Software/pH7-Social-Dating-CMS#42]
I now get this message when I try to access the system, front or admin.  I have been playing with it for about a week or two, everything seem fine until now. using v1.1.8

You need to buy a valid pH7CMS License Key to use the features requiring a license key!

What do you think could be the cause of this?

http://ph7.go2an.com/

**Comment by pH7Software** [comment]
In order to know what happens, please subscribe our Facebook page ->
https://www.facebook.com/Ph7Soft
http://ph7cms.com/all-our-apologies/


*- If you want to contribute to this project (bug fixes, **new features,
new modules, **documentation, translation, ...) do not hesitate to contact
me and I will give you the GIT repository access.*

*- To support the development and volunteer help, make a donation **here*
<https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XWLDYLFKCLEJQ>
*.*


Best regards,

Pierre-Henry Soria
