### ISSUE TITLE
Admin panel login Any setting changes Reagain login

### ISSUE THREAD

**Issue by Ramlmm** [pH7Software/pH7-Social-Dating-CMS#422]
Admin login is good.but once any changes in settings it has re again asking for login. how can i set my video background home page and how to add premium charging members gateways.

**Comment by pH-7** [comment]
Looks like a session issue.
Maybe the disk space is full, and so it causes problems with your session. 
Anyway, it looks to be a problem with your session.
I would suggest you to contact your Web host for asking them to investigate and check their log.

P.S. Can you please create an issue per question, otherwise it gets messy, and confusing for others who read this. Thanks

**Comment by pH-7** [comment]
Have a great weekend anyway! Please reopen it if the problem persists. Thanks!

**Comment by Ramlmm** [comment]
Thank you! For reply.  I install ph7cms in a domain http://www.socialfriends.site  I find some of issues. 
1.The Home page user fields appears not Beside the pictures as like demo .Admin issues, Activation Email not get after Registeration. Affiliation and Banner Ads promotion.
2.. When user login Any News feed  How can it activate for news feed
3.. Searching profiles Any country is not available and states or not visible 
4. When user want to Upgrade membership menu is not listed and changed the membership will not get 
5. universal login get by 400 errors and icons very big . Add more social icons
6. Video plugins not added. Flash player swf as not work out.
7. How can i get full pledged design support.

**Comment by polynamaude** [comment]
Hi !
First of all, I'd suggest you start by going through the already solved issue and look for information. Possibly that you have misconfigured your webserver and / or you have modsecurity activated. If you want more help than it would be needed that you inform us about what system you are running under and what is your configuration.

Also, you can get some information by going through the documentation at : http://ph7cms.com/doc/

At last, we are all working on a volunteer basis for support so our pay is when you take the time to star the repo on gitHub.

https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png

**Comment by pH-7** [comment]
Thank you @polynamaude!

**Comment by pH-7** [comment]
@Ramlmm Apparently, you didn't read my full comment saying to create one single issue per single question (and not 8-10), otherwise it gets messy, and confusing for others who read this. Thanks

**Comment by pH-7** [comment]
>. When user login Any News feed How can it activate for news feed
Like it says in your website, a user has first to comment on a profile, and it will show up on the homepage wall.

**Comment by pH-7** [comment]
>  universal login get by 400 errors and icons very big . Add more social icons
So, you manually enabled the "Connect" module. However, beside it, it says this -> https://ph7cms.com/better-not-enable-connect-mod/

Although it is disabled by default, I leave it in the software in case someone wants to update it, so that the module can work with the latest APIs Google, FB, Twitter, etc.
Personally, I don't plan to update the "connect" module in a near future (already too busy), but any good devs are welcome to do so if they wish :)
