### ISSUE TITLE
Encode geolation is wrong

### ISSUE THREAD

**Issue by nandosilvajr** [pH7Software/pH7-Social-Dating-CMS#425]
When I try make a seach with People Nearby show the follow error:

 ![image](https://user-images.githubusercontent.com/32247688/51808214-e8e92180-2288-11e9-884d-a4b46b4651a5.png)

In the console show the follow message:

![image](https://user-images.githubusercontent.com/32247688/51808217-03bb9600-2289-11e9-893f-6e43e558a46c.png)

The info that its get is:

![image](https://user-images.githubusercontent.com/32247688/51808246-74fb4900-2289-11e9-889e-c3054a29b4c4.png)

**Comment by pH-7** [comment]
Hi @nandosilvajr 
Thanks for reporting this problem!

If you try `http://your-website.com/dating-portugal/setubal` without the `ú`, it works well, right?

**Comment by pH-7** [comment]
Last thing @nandosilvajr 😊
Don't forget to Star the repo as well   😊
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

Thanks

**Comment by pH-7** [comment]
Hey @nandosilvajr 
I have an excellent news for you.
I found the reason of the issue you got.

Can you just change https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/f440472298c00f9a736e4d2c4daec6a781a47a27/_protected/framework/Http/Http.class.php#L289
File `_protected/framework/Http/Http.class.php`, line 289

Replace
```php
return Server::getVar(Server::REQUEST_URI);
```
to 
```php
return rawurldecode(Server::getVar(Server::REQUEST_URI));
```

Save it. That's all. And ignore the previous ugly fixes I gave you before :)

Technical reason: It was because `$_SERVER['REQUEST_URI']` s always URL-encoded :)

**Comment by nandosilvajr** [comment]
@pH-7 Great!!! Thanks for everything!

**Comment by pH-7** [comment]
You're welcome @nandosilvajr! 
BTW, you will probably have to clear the "Database and Other Data" cache after you have made the changes.
https://ph7cms.com/doc/en/how-to-clear-caches
Admin Panel -> Tool -> Caches -> Caches Manager -> Database and Other Data.

**Comment by nandosilvajr** [comment]
Hi, @pH-7 !
I tested after the change and it worked very well.
One more, thanks! @
