### ISSUE TITLE
problems installing new language

### ISSUE THREAD

**Issue by ungoliant235** [pH7Software/pH7-Social-Dating-CMS#440]
Hello,
i just installed pH7 and tried to install a new language the recommended way([like this](https://ph7cms.com/doc/index.php?p=how-to-translate-to-another-language&l=en)) but soon as i activate the new language i got this error:
![2019-02-13 14_07_25-fatal error_ exception](https://user-images.githubusercontent.com/47657742/52843957-c9b11780-3103-11e9-868c-4c8ce0705ad2.png)
Has anyone an idea?

thanks and kind regards

**Comment by pH-7** [comment]
Related to https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/418

**Comment by pH-7** [comment]
What version are you using?

**Comment by pH-7** [comment]
I published a patch to fix it https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/418#issuecomment-457073240
You can manually add it, or use the pH7CMS 14.9.0 or higher.

**Comment by pH-7** [comment]
Hope this helps!

Enjoy your weekend and your social dating website anyway :tada: !

**Comment by pH-7** [comment]
Hey @ungoliant235 
Since you didn't get back to me, I assume that this issue is now solved for you and can be closed. Just let me know if this isn't the case 😃

Don't forget to also STAR the project on GitHub
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by ungoliant235** [comment]
Hello,

sorry I've been ill the last few days so i did not much :)
Yes the fix works indeed thank you for helping!
