### ISSUE TITLE
All file and folder permissions are set to 777 in new update, why?

### ISSUE THREAD

**Issue by kevinbkk** [pH7Software/pH7-Social-Dating-CMS#441]
By default all files and folders permissions are set to 777, why is that? I'm wondering this causes serious security risks. Plus I get error 500 when i tried to install the new version exactly because of these crazy pre-set 777 permissions.

**Comment by polynamaude** [comment]
You get an "Error 500" because of folder permissions ? That's more than odd :) Maybe you should (try) to explain the link between those two to myself ?

Oh, and by the way, if you have time... It would be great if you gave me a list of the software you wrote in your life and your expertise in development ? Just so I know the background of the person who come to make such critics !

**Comment by kevinbkk** [comment]
So you're saying that all files and folders 777 pre-set doesn't look odd to you?

**Comment by kevinbkk** [comment]
I'm not saying I'm a professional programmer, but this error caused by permissions, why I'm sure? because when I change the _install folder permission to 755 it's working. I'm just worry about all those 777 permissions on every single file and folders. It just looks very wrong to me.

**Comment by polynamaude** [comment]
@kevinbkk It is not because you do one thing and your problem goes away that you have found what caused it. At most have you did something that makes it go away :dancer: 

If you'd take the time to read the documentation of pH7CMS then you would have already understood that some folder are needing to be 777 and others not.

https://ph7cms.com/doc
https://ph7cms.com/doc/en/install

That's what I call a RTFM case !

**Comment by kevinbkk** [comment]
> @kevinbkk It is not because you do one thing and your problem goes away that you have found what caused it. At most have you did something that makes it go away 💃
> 
> If you'd take the time to read the documentation of pH7CMS then you would have already understood that some folder are needing to be 777 and others not.
> 
> https://ph7cms.com/doc
> https://ph7cms.com/doc/en/install
> 
> That's what I call a RTFM case !

Your install documentation says "all folders":
Warning, these permissions don't allow editing and creating files in the File Management admin module.
If you want to allow it, you need to set in numerical values 777 for **all folders** and 666 for all files.

**Comment by pH-7** [comment]
The 500 error isn't related to the 777 permissions.

To see what are the reasons of your 500, please open `_protected/data/log/php_error.log` file and you should have more details in there.

**Comment by kevinbkk** [comment]
Thanks for your answer. But my question is why should I give 777 permissions to all folders? Why in new update all folders and files has 777 permissions by default. These are my questions and still didn't get a clear answer.

**Comment by polynamaude** [comment]
@kevinbkk Go back and read the message that I wrote you.
You have your answer.
And even better, you have the installation instruction saying the permissions for folders.
If you extract a _tar_ archive and get everything to 777 then take the time to read the _tar_ manual to learn how to extract permissions or simply set them by hand.

**Comment by kevinbkk** [comment]
Ok, so please fix this 2 line in your manual as it gives so much confusing:
Warning, these permissions don't allow editing and creating files in the File Management admin module.
If you want to allow it, you need to set in numerical values 777 for **all folders** and 666 for all files.

**Comment by kevinbkk** [comment]
OK thanks, I do get guys. looks like the file manager system is not a critical module. So I will keep the 777 permissions limited to only those 10 folders suggested in installation manual.

**Comment by pH-7** [comment]
Good @kevinbkk :) Good luck and all the best with your website Kevin :)
