### ISSUE TITLE
Site URL  ? IP

### ISSUE THREAD

**Issue by gatgat1991** [pH7Software/pH7-Social-Dating-CMS#461]
Hello have  a Prob my Homepage  have One domain and   my Homepage use My Server ip Oo wy ?

here 1 pic.
http://prntscr.com/mrkddy  
and here
http://prntscr.com/mrke5w

**Comment by gatgat1991** [comment]
https://mydates.ch/ sorry here is my  Domain

**Comment by polynamaude** [comment]
What is exactly your question ?
I think you should look with a professional technician. This is the support for pH7CMS specific issue not for network infrastructure configuration or Apache web server configuration.

**Comment by pH-7** [comment]
Hey @gatgat1991 

FYI, since [v12.1](https://ph7cms.com/ph7cms-12-1-released/), all URL lookups from the router are cached.

Because you changed the website URL, please try to remove `/_protected/data/cache/pH7_cache/str/uri/` folder. This folder will be regenerated and the cached URIs recreated.

Finally, if you wish, you can disable this feature by changing the `Uri:: URI_CACHE_ENABLED ` constant to false https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/framework/Mvc/Router/Uri.class.php#L25 

Hope this helps!

**Comment by pH-7** [comment]
Hope it helps and don't forget to STAR the repo 😉 

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by kevinbkk** [comment]
How can we disable the whole cache system? I had several issues with your cache system and just wondering if your script can run totally without caches? I tried to disable some caches through admin panel but the caches are still generated in cache folder.

**Comment by polynamaude** [comment]
@kevinbkk Look in the options on your administrator control panel.

**Comment by kevinbkk** [comment]
> @kevinbkk Look in the options on your administrator control panel.

That doesn't work, caches are not stopped 100%. How can I disable all caches to be generated. PH-7 suggested to delete some line codes in some files. I want some guide like that and for all caches.

**Comment by polynamaude** [comment]
Yes the cache are stopped completely.
If you modify source code then you'll need to do all those modification every time you do an update because you are going to loose them.

**Comment by gatgat1991** [comment]
tix for  this is working :)

**Comment by pH-7** [comment]
> but the caches are still generated in cache fold

You can disable caches in Admin Panel -> Tools -> Caches -> Cache Setting, however this ISN'T recommended for speed/CPU usage reasons.

The folder you still see in the cache folder contains the dynamic PHP files generated by pH7Tpl when translating the .tpl files into PHP (this one cannot be disabled, but they aren't cache files, just PHP files, which are re-generated each time you do a modification in a .tpl file).

**Comment by pH-7** [comment]
Hi @charleskay!

Steps to do in order to see the error details.

- Set the "development" mode.
 -> Open /_protected/app/configs/config.ini
  Change 

```
[mode]
    environment = production
```

to

```
[mode]
    environment = development
```
1. Refresh the page and see the errors on the page.
2. Check if you have a log file in /_protected/data/log/
3. Then, you will see better what's wrong with your website :muscle:

**Comment by pH-7** [comment]
Finally, maybe this will also help you (or your web host).

Here are the steps to do in order to see the error details... (hopefully it will, depending of your host configuration).

- Set the "development" mode.
 -> Open /_protected/app/configs/config.ini
  Change 

```
[mode]
    environment = production
```

to

```
[mode]
    environment = development
```
1. Refresh the page and see the errors on the page.
2. Check if you have a log file in /_protected/data/log/
3. Then, you will see better what's wrong with your website :muscle:

**Comment by Mobiller** [comment]
Removing the `/_protected/data/cache/pH7_cache/str/uri/` folder worked for me.
Thank you

**Comment by pH-7** [comment]
Glad to hear that @Mobiller! :tada:
