### ISSUE TITLE
girls profile must be free to chat and video if male user is paid

### ISSUE THREAD

**Issue by samit78** [pH7Software/pH7-Social-Dating-CMS#462]
girl profile can chat and video free if the male and ladyboy profile is paid. as girls will never pay on my site. how to do that

**Comment by polynamaude** [comment]
You will need to go through the source code and add such logic to the membership related classes.

If you need some hint for finding the exact classes then let me know but if you know how to program in PHP then you should be okay on your own because the code is pretty clear and totally Object Oriented.

Please take time to read the links I've sent you in the other messages before opening other issues.

**Comment by samit78** [comment]
Hi,
Please let me know the class and what to change as i dont have knowledge of PHP
Regards,
 

    On Friday, March 1, 2019, 7:44:33 PM GMT+7, Polyna-Maude R.-Summerside <notifications@github.com> wrote:  
 
 
You will need to go through the source code and add such logic to the membership related classes.

If you need some hint for finding the exact classes then let me know but if you know how to program in PHP then you should be okay on your own because the code is pretty clear and totally Object Oriented.

Please take time to read the links I've sent you in the other messages before opening other issues.

**Comment by polynamaude** [comment]
Hi !
Like I already said, please start by go reading the following link.

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

**Comment by pH-7** [comment]
This isn't available in the software. However, since the software is 100% open source, everything is possible, but you will need to build your own chat since pH7Builder uses a third party.

I suggest you hiring a good PHP dev on Toptal or Upwork and mention you need someone for "pH7CMS software".

**Comment by pH-7** [comment]
Good luck anyway!!
