### ISSUE TITLE
Caches Crashed all my website

### ISSUE THREAD

**Issue by kevinbkk** [pH7Software/pH7-Social-Dating-CMS#467]
The problems with caches are endless. As PH-7 (the script author) suggested I set **Uri:: URI_CACHE_ENABLED** to **false**. Then I go back to **admin panel** and **disabled all cache settings**. Then I tried to **clear caches from admin panel**, First I clicked on "Database and Other Data", it said the caches are cleared, then I clicked on "Server Code Template" and guess what happened? The website crashed. Completely white blank page. My 3 weeks hard work is now gone.

To fix this I cleared the cache folder from cPanel and browser caches and returned back **Uri:: URI_CACHE_ENABLED** to **true**. Doesn't help. Totally white blank page. I can't access to admin panel or any page of my website. All page are just blank. As I could guess in first place, your caches are only troubles. Please give us an option to completely disable caches.

**Comment by pH-7** [comment]
Hey @kevinbkk 
Really sorry to hear that. 
This shouldn't happened.
Like I told you, normally you just had to delete `/_protected/data/cache/pH7_cache/str/uri` (or only "Database and Other Data" from the admin panel).

Your blank page here doesn't help me since I don't have any information.
Maybe, a "CHMOD permission issue" form your web server to regenerate the folders in /_protected/data/cache/

Please contact your web host and ask them to investigate on this. 

Finally, MAYBE you also have some useful logs in /_protected/dada/log/*


P.S. The "Server Code Template" you cleared aren't exactly cache files, but only generated PHP files translated from pH7Tpl syntax. This one can never be disabled.

So, your problem is from there... The template files cannot be generated and you get a blank page. Once again, your web hosting company will be able to give you much more info, since they will be able to investigate deeper on the problem and see the logs.

P.S.2 Maybe you did a modification in some places which causes this issue.

Good luck!

**Comment by pH-7** [comment]
Finally, maybe this will also help you (or your web host).

Here are the steps to do in order to see the error details... (hopefully it will, depending of your host configuration).

- Set the "development" mode.
 -> Open /_protected/app/configs/config.ini
  Change 

```
[mode]
    environment = production
```

to

```
[mode]
    environment = development
```
1. Refresh the page and see the errors on the page.
2. Check if you have a log file in /_protected/data/log/
3. Then, you will see better what's wrong with your website :muscle:

**Comment by kevinbkk** [comment]
Your cache clear system is so dangerous, it deletes all the website files from the domain root so I don't have any files or logs....
My question now is how to disable all caches. I see you're using smarty for it, is there anyway we can disable it permanently and see even no cache folder ever created. I will really appreciate if you give an option for it.

**Comment by polynamaude** [comment]
I've been using the CMS for the past 2 years and for a year been helping on the support forums for pH7. I never heard something alike that the cache erased your root folder. Could you explain more if you really want to get help ?

The functions to clear the cache only erase what's in the cache folders.

As for now, it seems lot more complains than anything else but never any feedback if what we told you worked or a simple thanks.

In all case and for every OpenSource project, you are free to hire any developer to add or modify so it responds to your personal needs.

**Comment by pH-7** [comment]
Thank you for your help @polynamaude! I really appreciate it!

**Comment by pH-7** [comment]
Hi again @kevinbkk :)

Like I told you on a different thread (https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/461#issuecomment-470383619), YES, you can disable caches in Admin Panel -> Tools -> Caches -> Cache Setting, however this ISN'T recommended for speed/CPU usage reasons.
The folder you still see in the cache folder contains the dynamic PHP files generated by pH7Tpl when translating the .tpl files into PHP (this one cannot be disabled, but they aren't cache files, just PHP files, which are re-generated each time you do a modification in a .tpl file).


You probablt did something wrong and deleted all files (or did through cPanel File Manager or with an FTP/SSH client..., but the "pH7CMS's Cache Manager" can ONY delete the cache folders (and not its parent folders). It's a pretty harmless tool.. :)


P.S. FYI, the software uses its own "homepmade" template engine, which is called "pH7Tpl" 
Only the installation wizard uses Smarty, which used to be a standalone tool I initially built separately for different projects. That's why the installer still uses Smarty for legacy reasons, but the rest of the whole software doesn't). 

P.S.2 Remember to backup your website twice a month or so (you should be able to automize it with cPanel/Plesk backup tool, or similar tools usually provided by your Web host).

In this case, if one day you accidentally erase your whole website, you will still be able to restore it "easily"..

Good luck! (and hopefully my help will be useful...) .

**Comment by kevinbkk** [comment]
> As for now, it seems lot more complains than anything else but never any feedback if what we told you worked or a simple thanks.

If I report an issue here, doesn't mean I'm not thankful. I already give star in Github and 5 star in sourceforge.

**Comment by kevinbkk** [comment]
> Hi again @kevinbkk :)
> 
> Like I told you on a different thread ([#461 (comment)](https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/461#issuecomment-470383619)), YES, you can disable caches in Admin Panel -> Tools -> Caches -> Cache Setting, however this ISN'T recommended for speed/CPU usage reasons.
> The folder you still see in the cache folder contains the dynamic PHP files generated by pH7Tpl when translating the .tpl files into PHP (this one cannot be disabled, but they aren't cache files, just PHP files, which are re-generated each time you do a modification in a .tpl file).
> 
> You probablt did something wrong and deleted all files (or did through cPanel File Manager or with an FTP/SSH client..., but the "pH7CMS's Cache Manager" can ONY delete the cache folders (and not its parent folders). It's a pretty harmless tool.. :)
> 
> P.S. FYI, the software uses its own "homepmade" template engine, which is called "pH7Tpl"
> Only the installation wizard uses Smarty, which used to be a standalone tool I initially built separately for different projects. That's why the installer still uses Smarty for legacy reasons, but the rest of the whole software doesn't).
> 
> P.S.2 Remember to backup your website twice a month or so (you should be able to automize it with cPanel/Plesk backup tool, or similar tools usually provided by your Web host).
> 
> In this case, if one day you accidentally erase your whole website, you will still be able to restore it "easily"..
> 
> Good luck! (and hopefully my help will be useful...) .

Thanks mate! great answer.
