### ISSUE TITLE
Images are taking a lot of spaces

### ISSUE THREAD

**Issue by justin4444** [pH7Software/pH7-Social-Dating-CMS#469]
For example a user uploads an image with the size of 1mb, your script creates 5 or 6 images and one images that it created is 4mb. Images itself takes a lot of space and your script makes it even harder to face with them. Why should be such an function to make images even more huge. I was happy with your script but I'm very confused about the image sizes.

**Comment by polynamaude** [comment]
Some choices are deliberate design choices.
If you make thumbnails "on the fly" or as needed then for sure it will take less place but you will take much more processing power on the server side and you won't be able to handle many concurrents connection.

I don't know what type of service you operate but considering the price of disk space on hosting provider, I doubt that it will be a real problem.

**Comment by justin4444** [comment]
So You're saying that making 1mb image to 4mb image is something helping processing power.
I doubt that, let's see if anyone agrees with you here.

**Comment by polynamaude** [comment]
@justin4444 At first, if you want to talk then start by understanding subtle differences.

If the software need to build a thumbnail on the fly every time some one sees a list of profile, then this mean that for a simple page request there may need to build 20 thumbnails. Building those will require processing power (aka CPU speed) and if you get many request by many users at the same then it will take a very big amount of processing power because building a thumbnail require using algorithms.

Now if I pre-process all the images ahead, then when someone request a page then I only have to serve to raw data. This does not require as much processing power because no calculation is made.

So this is what allow the CMS to deal with many users at the same time.

Oh yes, when I do process them on the fly and don't save them on the disk then it seems to look as if it would take less place but it's only because they aren't saved. But they'll need the same bandwidth.

And yes most CMS will exactly work the same way and have a cache. Joomla does, Wordpress too...

If you don't know the difference between render a image and display it, then make a search on Internet.

Maybe you should gain some minimal experience in software development before just saying anything out.

Do I need to continue ?

**Comment by justin4444** [comment]
Did you ready second post in this topic (I'm telling you what is the point of making 1mb image to 4mb)?
Please read it over and over again before reply.

**Comment by polynamaude** [comment]
Yes I exactly did read it. Thanks. And I did give you some explanation in case you don't understand the benefits of such design choices. Got it ?

**Comment by polynamaude** [comment]
And say things how they are, it's not only "making images bigger" as you think. We call that pre-processing,
And it's more subtle then the simple affirmation you make.
Either make some research, learn how to program or learn not to talk when you don't know (Hey 3 choices).

**Comment by justin4444** [comment]
I don't have any problem with making 6 pictures or 20 images and save it to help processing power. What I'm telling again and again is what is the point of making 1mb image to 4mb image (I'm talking about one of the image that made which is 4 times bigger than original image). one image................. one image............. one image.............. im talking about one image only. what is that image point????????????????????????

**Comment by polynamaude** [comment]
@justin4444 Maybe if you'd write in proper English then it would be lot easier to understand.

First of all, https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

If you want me to answer on some specific situation then give that information.
In this case, both image you are talking about and I'll look at the EXIF data for understanding.

Talking on something without any material is like doing astrology.

**Comment by polynamaude** [comment]
If you look at your first messages and the subjet, you are talking about **_imageS_**
And you asked about the whole system, now you are talking about one particular image. OMG you have lot of time to waste, digging through an image cache !

**Comment by justin4444** [comment]
> OMG you have lot of time to waste, digging through an image cache !

Looks like you don't have real life experience with having a dating website. It's not just about space, you need to back up those files everyday or every week. Just imagine how hard it would be. And it's not too hard if you see the problem by yourself. 

Just upload a profile picture and compare the size of the biggest image with original one. 

Please try to give real help and respect people questions. We don't have time for your nonsense.

**Comment by polynamaude** [comment]
@justin4444 I gave you an answer and I asked you something if you want to know more.
Now understand that it's not a commercial technical support.
Also, the word "issues" mean problem and here there's no such "problem" but only you trying to understand something.

And yes indeed it does take place to do backup. That's why there's such as "backup policy" like using a sliding window of 7 days.

What would you do if you'd be running a website with thousand of users ? You'd scale up ! And yes it does require resources.

If you don't like my answer then RTFM (Apache manual, PHP manual, System Administrator manual, etc).

It's not because you can install a software that it makes you a WebSite manager !

**Comment by justin4444** [comment]
Ok thanks again for another nonsense, please leave my question alone for others to answer.
My question was:
What is the point of making triple an image size? If that is not a problem then please skip answering this question. Peace!

**Comment by polynamaude** [comment]
@justin4444 What I told you and that you don't seem (or don't want) to understand is that if you give me the information about those specific image then I can explain to you why (what your brain calls the **_point of make triple an image size_**).

What is the point of asking a question over and over again until I get the answer I want.

**Comment by polynamaude** [comment]
@justin4444 Maybe you should change your title to "What is the point of making one image triple size". Because as it is now, you are asking about images that take place.

Or write in proper English, that is use a "s" when you talk about more than one and omit the "s" when you are talking about only one thing

**Comment by justin4444** [comment]
Ok, enjoy!

**Comment by jilinos** [comment]
ok

**Comment by jilinos** [comment]
> Looks like you don't have real life experience with having a dating website. It's not just about space, you need to back up those files everyday or every week. Just imagine how hard it would be. And it's not too hard if you see the problem by yourself.
> 
> Just upload a profile picture and compare the size of the biggest image with original one.
> 
> Please try to give real help and respect people questions. We don't have time for your nonsense.

I agree with you, it's not just an open source
