### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by hykelauncher** [pH7Software/pH7-Social-Dating-CMS#481]
Pls how can I disable/or edit the links on footer

**Comment by polynamaude** [comment]
Why don't you take a look at the docs instead of opening issues ?
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help
http://ph7cms.com/doc/
https://ph7cms.com/doc/en/how-to-remove-the-link-in-the-footer

**Comment by hykelauncher** [comment]
Am sorry....i have done it,thanks

**Comment by pH-7** [comment]
@hykelauncher 
That's the file to edit `templates/themes/base/tpl/bottom_menu.inc.tpl`

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/templates/themes/base/tpl/bottom_menu.inc.tpl

You can also use the File Manager system available in the admin dashboard. *Admin -> File/Page -> Public Files* and edit the mentioned file through it (otherwise, just edit it with cPanel File Manager or with a FTP client software.

**Comment by pH-7** [comment]
Hope it helps @hykelauncher, and in order to help me continuing the software, it would be great if you can spend one minute to create an account and leave a review at https://sourceforge.net/projects/ph7socialdating/
Thanks a lot. Enjoy your weekend!

**Comment by pH-7** [comment]
Hope it helps @hykelauncher ⚡️, and in order to help me continuing the software, it would be great if you can spend one minute to create an account and leave a review at https://sourceforge.net/projects/ph7socialdating/ 🚀
Thanks a lot. Enjoy your Sunday @hykelauncher!
