### ISSUE TITLE
Can't search members without a city

### ISSUE THREAD

**Issue by kevinbkk** [pH7Software/pH7-Social-Dating-CMS#489]
There's a default value (Houston) in city field in search members box. You can't delete it and search members only by country. Shouldn't you fix this?

**Comment by polynamaude** [comment]
Why don't you fix it ?

**Comment by polynamaude** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/499

Great answer from pH-7 that you should keep in your mind.

**Comment by kevinbkk** [comment]
I already did the reading of his comment and that's why I closed this. 
Did I do something wrong here? Are you a teacher in high schools? Cause you act like them.

**Comment by polynamaude** [comment]
I do act like one when people do act with the mind of less then teenage.

Never went through your mind about contributing something that others can benefits instead of only giving complains about what you dislike but never about what you like ? Tell me why the hell are you still here if nothing's good about this work. Maybe you should do the same with you gitHub account than you did with this issue.

Starting by being able to write one line of code before complaining about others work.

You compare a small project being run by some volunteers with projects being run by big team. Maybe you should ask yourself what you are missing here ?
