### ISSUE TITLE
universal login

### ISSUE THREAD

**Issue by tendoryu** [pH7Software/pH7-Social-Dating-CMS#495]
now in this time every one have facebook or gmail
it wil be nice if the can log in with it
it wil be huge

**Comment by polynamaude** [comment]
Hi,
Thanks for the suggestion.
You can help the development of pH7CMS by your contribution.
https://www.patreon.com/bePatron?u=3534366

You can also hire a developer to build such solution for you and we'll add this to the package.

Also, if you can star us on gitHub it would be appreciated.
You can also make a nice review on Sourceforge.

<img width="1030" alt="star-repo" src="https://user-images.githubusercontent.com/21186871/55447976-0641b100-5594-11e9-8bcf-12d647dd960f.png">

**Comment by pH-7** [comment]
Thank you @polynamaude! :1st_place_medal:  Really appreciate it :+1:

**Comment by pH-7** [comment]
Hey @tendoryu 

This used to be implemented in the past for Twitter, Facebook, Google and Microsoft accounts. Unfortunately, the module had to be disabled by default, because they APIs changed and the "connect" module couldn't be working at all anymore. Those APIs will have to be updated. However, because of lack of time, this isn't my priority at the moment.
