### ISSUE TITLE
Can I limit the number of messages users can send per day?

### ISSUE THREAD

**Issue by kevinbkk** [pH7Software/pH7-Social-Dating-CMS#502]
As this script has a good labeling feature for members (gold, silver, free and paid) I'm wondering if there's an easy way to limit the number of messages a user can send or receive or read per day?
If currently there's no such an option it would be a good idea to add this feature to your script.

**Comment by polynamaude** [comment]
@kevinbkk You ask and suggested many things. May I ask what do YOU have to give ? Like I repeat quite often in business meeting, we'd all love to stop the wars in the world. But what do we do for this ?

If you want to make the software custom for your needs then that's exactly what does the GPL license allow you to do, with the bonus that you give back to the community at the same time. You didn't spend a dime out of your pockets for a license fee for this software or any type of fees whatsoever.

You make critics saying "Think big, Facebook does it this way and the big dating site work this way", Great ! But I doubt that they run over HostGator and complain about PHP version problem because they want to stick with 5.6 ! And yes they use GPL software and contribute back to the community by paying programmer to work on Open Source software. For example, the React Framework made by Facebook, the Linux Kernel that IBM pays programmers to work on, etc.

**Comment by polynamaude** [comment]
@kevinbkk I think you are from South-East asia ? Maybe you could contribute one a translation to one of the local language ?

That'd be a great feature to add to this script !
If you need help doing so, I can give you some hint.

**Comment by kevinbkk** [comment]
Some suggestions I made here may takes only one or two line of code for experienced programmers. 
BTW these are just a suggestion, nothing to angry about, you just need to skip the suggestions if you don't like them or you just think it's unfair or whatever.
PS. Translation is not necessary, I don't go through wrong paths while there are so much rooms for improvement and this script is not even close to something that actually can work.

**Comment by kevinbkk** [comment]
However I should admit the creator of this script is genius but still not enough work done here. Back in 2010 the creator of Thaifriendly code the website in just one attempt. Since then there's no update in the site's script. He did a good job once and used it for many yrs.
What I see here is too many nonsense commits for years and years while there're important feature for basic dating site is still not included.
I gave you the site name caz I wanted to know if your problem is the lack of ideas about dating sites, this perfect example could fix your 2 yrs non-sense attempts and commits. Do the job one time and enjoy from the money comes in for lifetime.

**Comment by polynamaude** [comment]
@kevinbkk May I ask what background do you have in development to make the affirmation about "non sense" commit ?

You must not have written much software to think this way because doing development is not about getting ideas but implementing them. At first there's a difference between a script and a program. So I'll give you one great suggestion, start by using the good words.

Before saying thing about what you find "non sense" but don't seem to have done much programming. As I can see that you created a gitHub account for the only reason of being able to open issue here. Maybe you could try to make a module for one of the **_great needs_** you got. That would be a great experience of doing some non-sense programming for others to review, make suggestion and tell you what to improve.

A "**_script_**" is code that acts upon some system in an external or independent manner and can be removed or disabled without disabling the system itself.

A "**_program_**" is code that constitutes a system. The program's code may be written in a modular manner, with good separation of concerns, but the code is fundamentally internal to, and a dependency of, the system itself.

Scripts are often interpreted, but not always. Programs are often compiled, but not always.

**Comment by polynamaude** [comment]
@kevinbkk About the not enough work done, maybe if people would actually contribute more than ideas then the software would develop faster. Like PH said himself, he could take some time off to invest in the development and make features develop faster.

On my part, I'm working on a nice AJAX based instant messaging modules.

And oh, yes about if you think you are going in the wrong path than maybe you should simply think about installing UNA. You'll get much more possibility and a nice monthly fee ! Or you can use patreon and pay a monthly fee as a contribution to get some work done faster.

**Comment by polynamaude** [comment]
@kevinbkk And back in 2010 we wrote pretty much one-way web application without needs for responsiveness (adaptation to mobile platform) and didn't use much ES2015 (as it's out in 2015). So yes what we used to do back then could be done in a easier way because we didn't have to check for XSS and other type of security problem, we didn't use as much multimedia as now, and many others thing. So what you compare is pretty, let me see, pretty loose.

**Comment by polynamaude** [comment]
@kevinbkk And I'd ask, as you got just genius ideas. What type of development pattern would you use for you message limitation based on the users level ?

A solution that allow to serve as base for the limitation of all actions on the system (as opposed to the actual system that's based on module only limitation) ?
Where would you implement such control ?
Would you reset the values based on UTC or based on the users time zone ?
If you implement limitation only for messages and not a pattern that allow inheritance of object with override, then what happens if we feel like this could be useful to add other type of usage limitation ? Let's say, number of minutes you can play in game ? We design a new system for the games ? And finish having different system for every type of modules / features ?

Maybe what you think is "non sense" commit is actually what developer call "refactoring" (Oh no ! Maybe I should think that because I don't understand why then it does not mean it's non-sense !).

**Comment by kevinbkk** [comment]
What I'm telling is that you don't need to invent something from scratch. There're already many sources you can use in order to get ideas and even do better job. But what I see here is like you're inventing the dating sites again. Just see how much time used here for development and still some basic features missed. (for example: searching members in a country and browse toolbar in mobile displays).

If we lived forever then it would be OK if 10 yrs used for development but the reality is life is short. Again do the job once and in a good way or never start it caz the results is failure.

BTW I'm not going to extend this discussion as I think we don't understand each other but misunderstanding.

**Comment by kevinbkk** [comment]
> On my part, I'm working on a nice AJAX based instant messaging modules.

Instant messages? I thought this is for dating. I never thought we're going to make chat application like whatsapp.

Adding extra features is fine but we have something called priority. Have you ever heard about this word "priority"

**Comment by kevinbkk** [comment]
How about making a module for cooking chickens caz I like to eat sometimes.
Aside joking, about instant messaging it would be a good idea if you totally replace it with current message system. and not have to system for messaging.

But please please please look at Thaifriendly to see how they implemented it. It has a very good instant message system that opens in user profile so whenever you visit a user profile you can see the chat history with the user too. This also implemented by DateinAsia.

Again and again we don't have to invent something from scratch.

Good luck!

**Comment by polynamaude** [comment]
@kevinbkk Yes I heard about priority but for sure one thing you don't seem to know about is software development. I've read plenty of "do this, do that" but not once did I've read a line of code coming from yourself.

So for now on, I wish you good luck with your projects and when you have something constructive to add then maybe they're will be a place for your speech. You think we don't already know everything you are saying ?

No there's no need to reinvent the wheel but look around, why do you think there's 10 different Joomla plugin for Facebook, same for WordPress ? Maybe because people like to make things in a way that suit they're own need. And a reason for Instant Messaging is pretty simple and far from trying to take the place taken by WhatsApp (oh yes, WhatsApp, Badoo, Mignonne.Com and plenty of other site all have Instant Messaging). You sometime want to exchange some "instant" words with the person before having them added to your Facebook profile as you want to keep some anonymity.

When you do something else than open issue (and close them when you see that you're talking alone) then you'll have understood something about collective work.

**Comment by kevinbkk** [comment]
> about instant messaging it would be a good idea if you totally replace it with current message system. and not have two system for messaging. But please please please look at Thaifriendly to see how they implemented it. It has a very good instant message system that opens in user profile so whenever you visit a user profile you can see the chat history with the user too. This also implemented by DateinAsia.

I knew what's instant messaging but the implementation of it is more important. Before replying to comments please read them carefully.

**Comment by kevinbkk** [comment]
You made modules that are too useful to be used. I disabled almost all of them. Thanks for your work! Well done!

**Comment by polynamaude** [comment]
Before making useless issue maybe you should think about the context into making them. When someone tells you many time there's limited resources for development and you don't do better than to call refactoring "useless commits" then you're what we call simply someone disrespectful for the work of others. There's no other name for that or as my parent taught me, you're someone who don't have manners and don't know how to live in society.

**Comment by polynamaude** [comment]
If this software is so useless to you then you must be someone really sad to waste all of your time with it.

**Comment by kevinbkk** [comment]
Avoid extending this discussion. I never used useless word. All I said is times matter. Good luck teacher!

**Comment by polynamaude** [comment]
WoW ! He finally understood.... What a fast learning guy.
