### ISSUE TITLE
User friend problem

### ISSUE THREAD

**Issue by spike99** [pH7Software/pH7-Social-Dating-CMS#504]
If user X send friend request to user Y, and user Y does not respond to the request of friendship and enter to user X profile, he have "add friend" if user Y send a request. they will be friends 2 times in friends list

**Comment by kevinbkk** [comment]
Suggestion: disable friend module if you running a dating site and ask him to fix more important things. We don't need another Facebook but a real dating website.

**Comment by polynamaude** [comment]
@kevinbkk Maybe you could fix the problem ? You seem to know everything and which goal should go first. Or maybe you could write a whole software on your own ?

**Comment by kevinbkk** [comment]
and why you don't fix it? I never said I'm a programmer But you always keep saying that you're a programmer. I'm HR in a hotel but I can tell what does it mean if a dating site not provide search by country feature, specially what does it mean for new dating site with small amount of users. Don't you get the point? Without this feature we all fail and we can call this program a virus (virus for wasting my time for 2 month).

**Comment by polynamaude** [comment]
@kevinbkk If you ain't a programmer then I'll understand that you don't know much about what you are talking when you say that the passed "two years of useless commits" and don't have much a clue about what does it means to do bug tracking.

If you're in human resources then I think you should read back your books about mental sanity because one day you say that the guy who started developing this is a genius, the other you say that most of the software is useless (you turned off the modules) and another day you are saying you wasted your time.

The day you'll be able to use a command line and / or write some line of code then this day you'll get close to having the necessary knowledge to judge other peoples work, even more when it's volunteer,

Like I already told you, go with Una or another paying option, at least you'll get the chance to also complain to your bank / credit card provider about not having what you paid for.

You are clearly the kind of person who expect much but don't give anything back. Could I ask you how would you develop such way for searching with a list of city ? Or is it what you are talking about ? Selecting a country, afterward seeing all the city that users that are registered live in and finally getting of the user in such city ?

You see a new release going out with many commits and fixes, but because you still find a bug that you expected to having fixed, what do you do ? You jump writing a issue saying it wasn't fixed. Never had in mind that maybe it's gonna be in the next one ? As you never did any programming in your life (and maybe you should try so you could understand) then I'll tell you it's much like a human being, you can change something and another place totally non related will break. We call that systemic effects, sometime you may think that a bug fix will be easy to write but discover much more later on.

If you feel that I'm acting with you like a teacher then grow up, act like an adult. When people offer thing for free, we don't ask like kids over and over again "can i get this, can i get that, please please please, I want the bigger one, no it's never enough".

If you have shitty customer, you know the one that you'd prefer they go somewhere else then be assured that you are acting exactly like one.

http://www.una.io/ You're gonna get all your features there !

**Comment by polynamaude** [comment]
@kevinbkk Maybe you should tell the guys at UNA that they are going the wrong way because they have both a IM (Intercom) and a messaging client in the system. And of yes, they even integrate MailChimp ! Who could need another IMAP clients we got so many ! It must be like who'd like to use a Apple Mac when there's already Windows boxes ? Why do Samsung produce cellular phone when there's also LG, Apple, ZTE ? Why does you hotel exist when there's a better one across the street ?

**Comment by kevinbkk** [comment]
**I didn't ask adding a full list of cities for each country**. All I'm trying to say is improve basic features then go for more advanced development. Simply let the users search by country and don't pre-set a city name in field for us that disabled Google Maps. You're a developer and I'm explaining this to you now for 2 days and you still misunderstand. Or you got the point and just trying to destroy the questions to go nowhere. You really like long discussion that goes nowhere.

**Comment by kevinbkk** [comment]
I hope you get the point this time or I totally should give up on you. haha

**Comment by polynamaude** [comment]
@kevinbkk How are you trying to improve something ? You really think we didn't notice that there was some problem with this feature ? If you get the city "houston" it's because they system's database called GeoIP is not able to find you properly.

And now I'll talk with you like we talk with the dubest person on earth so you can understand it.
Maybe for you (that know everything but can't write a line of code but do complain about other), that's something simple because in your belief you see the word "houston" and think "Oh it must be because someone made the choice to put this city there" but not really. The GeoIP database locates you and publish users going from the closest to the one that is the farthest from you. (Got it ?).

If it does fail then it fills "Houston" as a default.

Maybe for you everything is simple but the way the API was built, there's a need to have some city filled in because if the location lookup fails then it would compare with an empty string. This would give akward result.

For sure you can give me many explanation about how it should be done, that if a admin disable Google Maps then it should work this way or that way. But what you ignore (and oh my god, do you ignore many thing) is that not that long ago the Google Maps API changed. And down the road it caused the problem you are seeing now.

What you rudelessly and without even thinking before doing so called "useless commits" was partly some work to separate the framework and the implementation of the CMS so to have an independant interface for the geolocation API.

Now I never talked about prefilling a list of city. What I did ask you is the following. You say that we shall allow people to simply search by city name.

What type of search are you talking about ? A string comparison ? So if someone make a typo in the city name then it gives false and if you have two person who write name differently (Montreal vs Montréal) then it also give false ?

We build a list of city, based on the country of the user and show this list so he can choose a specific city ?

And what if you have two city in different region of a same country ? We simply forget the location service ?

Because you talked about Google Maps but you forgot that there' also the location service based on you IP.

What you think is asking something simple may sometime be a bit more complex. Yes I did understand your question. But you've never been able to answer any question you've been asked.

For you information, you already got explanation why you get "Houston" pre-filled and how to fix this. If you don't understand how then we won't take you by the hand for free.

Now good luck ! If you we're stupid enough to have the belief of build a dating site of commercial grade using HostGator then be lucky to have "wasted" (your words) the last two months on this software because much worst could have happened. Oh maybe you forgot that it's not because you can install some software that it means you got the skill to implement it. Unless you think that a book on HTML and one on Javascript will make you a genius ? The kind of dumbo who thinks that he's gona make a fortune with an idea that everyone's got. Oh I"m gona make a dating site for my city and be rich.

**Comment by kevinbkk** [comment]
> For you information, you already got explanation why you get "Houston" pre-filled and how to fix this. If you don't understand how then we won't take you by the hand for free.

As I said you know how simple this issue is to fix and you just don't want to give it for free. Trying to waste my time and others. An empty city field for admins that disabled Google Maps is what we need here. Forget about possibilities of users typo, etc... That's OK and of course it should return no results and maybe a simple alert to tell users that "no results found, please make sure you typed the city name correctly or try other cities". Got it?

**Comment by polynamaude** [comment]
No it ain't that simple because you don't know much and try to look smart then you say it's about not giving for free.

What do you give for free?

Like I said, what you think is useless commits is refactoring work to make all those thing simple. I already explained to you why it ain't that easy.

Maybe if you ever tried programming some system then you'll understand.

Now, have an happy life wasting your time.

**Comment by pH-7** [comment]
Hey @spike99 

Thanks very much for the report. Please try this patch https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/7763c3f517a57ae4a418cb8e1d379b64318133c0
