### ISSUE TITLE
general settings 

### ISSUE THREAD

**Issue by tendoryu** [pH7Software/pH7-Social-Dating-CMS#506]
i have change the account activation type for members 
to
self activation via email 
and i get this errors 
error the hex color value is invalid has to be 
•Error: The HEX color value is invalid. Has to be "#XXXXXX" format.??

can you help me
thanks 
greatings

**Comment by polynamaude** [comment]
Please post a screenshot so we can see  in a better context.

**Comment by pH-7** [comment]
Hi @tendoryu 
Probably your browser doesn't support the HTML5 input color type.

pH7Builder uses the [https://www.w3schools.com/tags/att_input_type_color.asp](HTML5 `input type="color"`), however some browser versions such as IE, Edge or Safari don't support that field, and gives wrong value to pH7Builder, and that's why you get this error message.

Can you please use the latest versions of Chrome, Brave or Firefox? You shouldn't have this problem with them :smiley: Let me know

**Comment by pH-7** [comment]
This might also help you :) https://caniuse.com/#search=input%20type

**Comment by polynamaude** [comment]
Or Safari (Mac)

**Comment by pH-7** [comment]
Oops, sorry, there is apparently a problem with the latest link I gave.
This one is more relevant :) https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color#Browser_compatibility

**Comment by pH-7** [comment]
@polynamaude Yes, Safari is now the NEW IE that everybody hates... :D and gives some hard time to devs...
