### ISSUE TITLE
Payment module problem

### ISSUE THREAD

**Issue by walnad** [pH7Software/pH7-Social-Dating-CMS#507]
When member buys one of my memberships, it won't update his membership status.After payment is made i get an error "Provider not found" any idea? Membership level is not updating after purchase as well.Always remains the default "Free" See attached screenshot 
I'm using PayPal payment module.
Thanks for any help
![54879829-e7f0ee00-4dfa-11e9-9d19-242bba137613](https://user-images.githubusercontent.com/48806517/55887599-a2565400-5b62-11e9-8e15-503a17a34a22.png)

**Comment by pH-7** [comment]
@walnad I don't see the browser's URL tab on your screenshot.

The problem is probably caused by Paypal, which adds some GET variables in the URL when returning to your website, which causes the problem.

In order to help you fixing the problem, please give the full URL you see when you get this Not Found page?

**Comment by walnad** [comment]
but, why the membership is not upgraded to user chosen membership after payment???

**Comment by walnad** [comment]
Is there a working (fully working version) that I can buy to test it? So far I wasn't that lucky.. All version I've tried never worked out of the box. 
Thanks,

**Comment by polynamaude** [comment]
@walnad For the membership to be upgraded there's need to be a call to the good URL with the parameters that state that the transaction was completed.
If not, then it would mean that whatever result of a payment then the person would get her membership upgraded. This means **_free_** for all in some way and you don't want that.

**Comment by polynamaude** [comment]
@walnad If you take the time to read the documentation available, you'll see that it's under GPL this means that you don't have a paying version.

If you'd like I suggest you become a patreon ( https://www.patreon.com/bePatron?u=3534366 ).

You can see this issue to better understand the situation ( https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/499 ).

Probably that PH will give you a more complete explanation when he's got time but that's the best I can give you for now.

**Comment by polynamaude** [comment]
@walnad May I add one thing, none of the solutions that you'll find will give you something functional **_OOB_** (Out Of the Box). We are not talking about installing an office suite like MS-Office or LibreOffice but running a service here. You'll need to invest time to modify templates, do some marketing, write some rules, prepare system backups, etc.

Your small problem will sure get looked at but you to also understand that we all do this on our free time, as volunteer. I wrote a nice text about how to ask for help so that people can get their problem solved and understand how we work to do so. You can read it at 
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

In this precise case, the answer reside in the returned URL from PayPal and it's exactly what's missing from your screenshot.

A good chunk of pH7CMS is tested with phpUnit but there's still some part out of the developers control and everything that depends on external services (PayPal, Google Maps, Facebook, etc) is not totally in out hands. As soon they modify their API, they risk breaking the software and needing some update from our side.

**Comment by polynamaude** [comment]
@walnad May I add one thing, none of the solutions that you'll find will give you something functional **_OOB_** (Out Of the Box). We are not talking about installing an office suite like MS-Office or LibreOffice but running a service here. You'll need to invest time to modify templates, do some marketing, write some rules, prepare system backups, etc.

Your small problem will sure get looked at but you to also understand that we all do this on our free time, as volunteer. I wrote a nice text about how to ask for help so that people can get their problem solved and understand how we work to do so. You can read it at 
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

In this precise case, the answer reside in the returned URL from PayPal and it's exactly what's missing from your screenshot.

A good chunk of pH7CMS is tested with phpUnit but there's still some part out of the developers control and everything that depends on external services (PayPal, Google Maps, Facebook, etc) is not totally in out hands. As soon they modify their API, they risk breaking the software and needing some update from our side.

**Comment by pH-7** [comment]
Hey @walnad 

The membership isn't upgraded because you get the Not Found page.
So, like I already told you before, **in order to help you fixing the problem, please give the full URL you see when you get this Not Found page?**

**Comment by pH-7** [comment]
Hey @walnad 

The membership isn't upgraded because you get the Not Found page.
So, like I already told you, in order to help you fixing the problem, **please give the full URL you see when you get this Not Found page.**

This is  because the problem is probably caused by Paypal, which adds some GET variables in the URL when returning to your website, which causes the problem, so I need to see the full URL of that page.

Thank you!

**Comment by walnad** [comment]
Full url attched 
https://hot-cougars.com/payment/main/process/paypal?amt=1.99&cc=USD&cm=NXwxLjk5&item_name=Hot%20Cougars%20Dating%20Silver&item_number=5&st=Completed&tx=13C98808M44257407

**Comment by walnad** [comment]
thank you

**Comment by pH-7** [comment]
Yep, so like I said, the problem is apparently because now PayPal adds args in the URL when sending back to your website.
Anyway, I did some changes in the latest version, it should be good with v15 😊
Don't forget to Star the repo :)
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by walnad** [comment]
Thank you guys for all your help and suggestion. You definitely deserve a star.

**Comment by musixchannel** [comment]
please send me files to translate

Στις Σάβ, 13 Απρ 2019 στις 3:36 μ.μ., ο/η walnad <notifications@github.com>
έγραψε:

**Comment by polynamaude** [comment]
Look in the documentation or wiki, you'll find the info.

What you ask is not related to the current issue. Please be respectful and don't mess with unrelated discussion. Same goes on internet as in real life.
