### ISSUE TITLE
Location problem

### ISSUE THREAD

**Issue by spike99** [pH7Software/pH7-Social-Dating-CMS#508]
My city name has diacritics: 
Instead of being written Galați is IaÈi
spike from Romania, IaÈi
How can I fix the problem?

**Comment by polynamaude** [comment]
@spike99 Hi !
You problem seem to be related to the UTF8 implementation (or the lack of) and caused by the use of a different locale.

Have you looked at the encoding you specified in your different software that constitute you stack ?
Here's some hint to look after https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/324

And here's some hint if you want to get some better help.
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

If you like the CMS (and you seem to as you asked many questions) could you please make a nice review on Sourforge and star the repository on gitHub ?

That would be very appreciated.
<img width="1030" alt="star-repo" src="https://user-images.githubusercontent.com/21186871/55931618-450ae300-5bf4-11e9-8c64-77b8e8b4b926.png">

**Comment by spike99** [comment]
> @spike99 Hi !
> You problem seem to be related to the UTF8 implementation (or the lack of) and caused by the use of a different locale.
> 
> Have you looked at the encoding you specified in your different software that constitute you stack ?
> Here's some hint to look after #324
> 
> And here's some hint if you want to get some better help.
> https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help
> 
> If you like the CMS (and you seem to as you asked many questions) could you please make a nice review on Sourforge and star the repository on gitHub ?
> 
> That would be very appreciated.
> <img alt="star-repo" width="1030" src="https://user-images.githubusercontent.com/21186871/55931618-450ae300-5bf4-11e9-8c64-77b8e8b4b926.png">

My database is utf8mb4_general_ci .
If I write the manual location appears correctly.
The problem is with the script that searches for my location automatically

**Comment by polynamaude** [comment]
@spike99 There's not only the database default locale that needs to be verified.
Could you start by making a screenshot ? It's one of the point in the document "How to ask for help" and it give a good idea about where the problem may reside. And save us lot of time.

It does seem like an encoding problem and as mentionned in the issue I've linked to, it's something that does happens with non latin character.
