### ISSUE TITLE
The redirect is set in the mobile version

### ISSUE THREAD

**Issue by obmen86** [pH7Software/pH7-Social-Dating-CMS#520]
Good day.

In the script pH7Builder (formerly pH7CMS) when entering from a mobile phone, it will be redirected to another site. Perhaps a redirect is hidden in the site code.
Tell me how to check? The temporary address of the site jobdelivery.ru

**Comment by pH-7** [comment]
Hi @obmen86 

Hope you are doing well :smiley:

Your issue looks really similar to this one https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/395

**Comment by pH-7** [comment]
So, it looks you enabled the Adult Disclaimer (normally, it's disabled by default), which is a third-party service and may gives some kind of ads/redirection as mentioned on the Settings Page.

<img width="950" alt="screen_shot_2018-07-30_at_4_07_51_pm" src="https://user-images.githubusercontent.com/1325411/43402450-0b5edb38-9413-11e8-9b02-e498fe94d963.png">

Once you log in, please disable it in order to avoid this issue again (Admin Panel -> Settings -> Adult Disclaimer).

**Comment by pH-7** [comment]
Hope it helps!
By the way, if you like the software, do you mind to Star this Github repository 

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

Thanks in advance @obmen86! 💯
