### ISSUE TITLE
your connection to this site is not fully secure

### ISSUE THREAD

**Issue by merrygoes** [pH7Software/pH7-Social-Dating-CMS#522]
Hi, need you help figure out ways to solve the issue showing " Your connection to this site is not fully secure". see attached screen shot.  was using google chrome and firefox.
![site is not fully secure](https://user-images.githubusercontent.com/49989906/56748941-5dc3de80-6746-11e9-9dea-3af38b5fe0a4.jpg)

**Comment by polynamaude** [comment]
@merrygoes Hare you using a validated SSL certificates ? Contact your hosting provider with this issue. This is not related to the CMS.

**Comment by merrygoes** [comment]
> @merrygoes Hare you using a validated SSL certificates ? Contact your hosting provider with this issue. This is not related to the CMS.

after checking the SSL under https://www.sslshopper.com/ssl-checker.html#hostname=merrygoes.com
it shows correctly applied.

**Comment by polynamaude** [comment]
@merrygoes I have checked and two things:

First, your site is working fine
Second: this problem ain't related to the CMS.

It ain't because you think that there's a problem in the whole system that it's related or caused by pH7.

Go do some reading and you'll understand why this happened. You are acting like someone who'd complained to a printer manufacturer because pictures printed from Photoshop lack sharpness when using filter.

**Comment by Nigrini** [comment]
I have the same problem and my ISP told me that I must change every single link in my software from http:// to https://

Since the site is not live yet, will it be a quicker option to reinstall the script from scratch with the SSL now in place, or do I jump into the code and start changing (this might be a dangerous exercise for me)

**Comment by merrygoes** [comment]
thank you all for response. I reinstalled it and it works fine. But the original users were lost. I imported the database from the old database tables but it did not show old users. so I restored it. Keep it for now. Anyone has an idea how to get the old users onto the new install? thanks!

**Comment by merrygoes** [comment]
well, after adding new logo designed. it seems the issue is gone.
