### ISSUE TITLE
Fake profile Stats

### ISSUE THREAD

**Issue by CooperAshley2** [pH7Software/pH7-Social-Dating-CMS#536]
Is there a way to get more realistic data in the fake profiles? In the example attached, Waco is not in Massachusetts, and the zip code is neither for Waco nor Massachusetts. Also, the height of 3'11" and weight of 66 lbs is ridiculous to say the least.

![Capture](https://user-images.githubusercontent.com/50240615/57202878-73bc7500-6f78-11e9-935f-2bbd540c68de.PNG)

**Comment by pH-7** [comment]
Thank you for pointing this out!

Was it generated with the "Fake Profile Generator" or the "Bulk Members (without profile photo)"?

**Comment by CooperAshley2** [comment]
Hi, this is the case with both the Fake Profile Generator and the Bulk Members without photos. And the same issue with the Bulk Members (without profile photo), whereas the city/state/zip doesn't match up.

**Comment by pH-7** [comment]
Thank you! I will investigate on that, but they rely on third-party libraries. It's more dummy data rather than accurate data.

Concerning the weight/height, they are not generated. So, if you go to the edit form, the fields will show the lowest/highest possible values, since no values are set.
However, if you go to the profile page, you won't see ant height/weight information there 😃

**Comment by pH-7** [comment]
FYI, I also opened an issue concerning the invalid address details generated by Randomuser API https://github.com/RandomAPI/Randomuser.me-Node/issues/122
