### ISSUE TITLE
Possible Bug - User dashboard

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#543]
When User Dashboard is enabled - the page opens at the bottom of the screen 

![aa](https://user-images.githubusercontent.com/43742116/57447955-92f92200-7258-11e9-9dcd-689e410e94f1.PNG)

instead of

![bbb](https://user-images.githubusercontent.com/43742116/57447976-9d1b2080-7258-11e9-8b75-313b44c727fe.PNG)

**Comment by pH-7** [comment]
Good catch @Nigrini! 🥇

You're right. It's a bug. I will tell you what file to update in order to fix it.
The problem is due because all forms use jQuery `focus()` on the first field element of each form. 
And because on this page, the form is located at the bottom, the browser scrolls you down to that form field element :)

**Comment by pH-7** [comment]
In `_protected/framework/Layout/Form/Engine/PFBC/Form.class.php`, please just change the following ->
https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/6914c56f828856b20c5065cd869269f8a45a6f41
