### ISSUE TITLE
Bug - 15.1.0 Enable/Disable System Modules

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#544]
Clean install the latest 15.1.0 version. All the tick marks in Enable/Disable System Modules are gone

**Comment by polynamaude** [comment]
@Nigrini Maybe if I could copy / paste my life then would I save plenty of time repeating myself. As I already told you (in another message). When you do a bug report, could you please add a screenshot to your message.

It save some much needed time.

You make a plain affirmation but nothing else here. And this doesn't do much more than say something. Are you complaining about an issue ? You found a bug ? You think the user interface changes are misleading ?

Come on ! Help yourself somehow. Unless you just want to get ignored on the long run.

**Comment by kevinbkk** [comment]
He doesn't need to post a screenshot here. Move your lazy mouse over modules and see the ticks gone. What kind of person you are!? Are you sure you are not abnormal?

**Comment by Nigrini** [comment]
@polynamaude

As per your request I do as much research as possible before posting a question, and that includes going through the closed issues, as well as your personal favorite "RTFM". 

I was not able to find anything related to the problem, but I was able to scroll upon plenty of snotty remarks by you. It is quite clear that you have no real interest in helping anyone here at all.

Do you honestly require a screenshot of missing tick marks in the modules section, and how do you propose I try to explain to you the need for having the tick marks visible by way of a screenshot ?

But since you gave me an answer that I did make a screen print off, printed it out and whiped my a** with it, maybe you can stuff your snotty remarks where the sun don't shine and figure out why the 15.1.0 zip file is missing al least the following folders:

~/YOUR-PUBLIC-FOLDER/_install/data/caches/*
~/YOUR-PROTECTED-FOLDER/data/cache/*

They are after all important enough according to your "RTFM" to have 777 status on my file system.

And while you are at it, go and rewrite your IM module, this thing is so buggy that I don't think anyone out there is even enabling the module.

**Comment by polynamaude** [comment]
@Nigrini Thanks for the further explanation (about disabling) the wrong module, that wasn't in your initial message.

@kevinbkk FYI - The IM modules is made by Pierre-Henry, not me. I was in the process of writting a new one. But with all the good comments and cheers from user, I've put it on hold. Oh, by the way, no one forces you to install this software. Great to see your are still "wasting" your time (as it was your own words). You must have a really great business plan.

**Comment by kevinbkk** [comment]
Just today I delete this script and stopped using it forever. For some reason i'm still getting emails from github and i dnt know why. I unsubscribed from this email list 2 weeks ago n emails are still coming to my inbox. BTW Good luck with wasting your times

**Comment by Nigrini** [comment]
@polynamaude
I think I am talking for everyone when I say we all appreciate the time and effort that Pierre-Henry is putting into this project, and we think he is doing an excellent job. Now that said we can split the group into 2 parts. People with development skills and people without.

The people without development skills are much more important to a project like this than what you are giving the people credit for. As a developer yourself you must be well aware of testing scenarios (positive testing) as well as (negative testing).

Free vs paid – Personally I will be more than happy to donate towards the project, but I will do so once I have a reasonable stable system. But I don’t have a stable system, and the latest version of the script made matters even worse for me.

The problem with your attitude is that you are discouraging people to contribute towards the project, more so if the person is a non-technical developer. I get the impression that you look at all issues logged as a complaint, instead of an opportunity to make the software better.

**Comment by Nigrini** [comment]
This time with screen shots.

Clean Install the new script. From the ADMIN page all the modules don't have a tick mark in them. This is the way you get it, I did not remove any tick marks 

Now looking at this from the USER SIDE

when you log in you will have the following options available

![a1](https://user-images.githubusercontent.com/43742116/57586104-34020a00-74f1-11e9-96ab-56b273898d91.PNG)


So let us be nice as the system ADMIN and "enable" the chat module. Now you see that all the other options are missing and the user is left with the following

![a2](https://user-images.githubusercontent.com/43742116/57586121-6449a880-74f1-11e9-8f6d-07b6a47d383d.PNG)


I believe you have a better understanding now ?

**Comment by polynamaude** [comment]
@Nigrini Without being in a crazy madness as you may think. Where was the problem with the fact that I asked you a screenshot ?
Was there a possibility that what you said about the checkbox having disappeared be interpreted in more than one way ? Certainly.

Sometime when we don't know something then we think it's all simple. Like when I hear something like "Just fire-up the latest version and you'll see". Yes, for sure ! But what if I can solve the problem without ? Am I lazy ? Possibly.

Another thing, anyone (nearly) can install a CMS and (try) to operate it. Be it Joomla, Drupal, WordPress, etc. but it doesn't mean that you've got what it takes on the long run (aka When shit hit the fan). What I mean, is that you'll need to invest in customizing, etc. At least if you are serious in what you are doing, need to plan some backup, have some security procedure to prevent hack, etc.

I have no doubt in the usefulness of outside testers, big company do it too. And yes it's nice to have people do some check.

There's a difference between asking how to get some simple things done (like a user who asked what does it means to comment a line) and pointing a possible issue. Also, not because some software doesn't work out of the box that it's broken. Just do a check about installing MESA on Linux/Unix and you'll understand.

Yes I do understand where's the bug and I'll look at what changes have been done since.
