### ISSUE TITLE
HOTFIX ? 15.1.0 issues

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#549]
Out of desperation I installed 15.0.0 on a local host, after that I extracted the files from 15.1.0 SR2 (whatever that is) and replaced the files. 

This fixed the modules tick problem, and the default member registration option, 

Now for the first time I have a stable system that I am willing to go live with (keeping in mind that I am disabling the IM module because it is just not reliable).

I still have no idea what is the difference between 15.1.0 and 15.1.0 SR2 but at this stage I don't care.

**Comment by polynamaude** [comment]
@Nigrini Hi,
Thanks for pointing out this issue. 
Instead of just writing **_whatever that is_** concerning 15.1.0 RC2 maybe you could gain much more by doing some research. Computer aren't human and just using the simple thinking that if a manipulation work then everything is fine. That's the worst start you can get !
It may seem to work in one situation but not in another. In this case you extracted files from one version onto another. Was it all of the archives or only part of it, I don't know as you didn't mention nothing.

If you did all of the archive then you simply changed the version of your installation.

If you actually want to do something more useful and gain some knowledge then take a look at **_https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/modules/admin123/forms/DisableModuleForm.php_** and compare between release.

The last changed made on this particular file was 3 months ago.
You can easily search through all the source code using the unix (Linux) command **fgrep**. On Windows there's certainly another utility that will allow you to search inside of file. So you take a string and search into the source code for it. It will give you the beginning of a path to search for answer.

You've made a remark about the need to have people do test the software. Indeed it's a must but to be a minimum useful there's some standard rules to follow and knowledge to have. Part of this can be found here : https://en.wikipedia.org/wiki/Software_release_life_cycle

For example people who complains that they made a manipulation and broke their system. They tried to do some modification to the source code and screwed the system, corrupted the database, etc. Who's to blame other then themselves ? No one, only them because you don't operate those type of modification on a live system. Every, every and every developers knows that !

There's a line between the paid service offered by Microsoft and other provider versus the **_FREE_** software community. And even between the different communities, for example to compare Joomla that has many commercial supporters, company who offer support and invest in the development of add-ons versus this CMS that was written nearly all by one man.

And we have to beg for a minimum of support, be it to get a start on gitHub, a review on SourceForge. People expect it works out of the box but forget that it's more alike a CMF, that is the framework you use to build upon your site. For sure you can run plain out but your site is gonna look like many other pH7CMS. It's easy to say "I ain't a developer, I'm just reporting issue" but to be useful, a bug report needs one thing and it's a way to reproduce the error that is reported.

If I can reproduce it, then I can't investigate and fix it. Sometime it's easy to find the source, for example a typo in the writing of a string. But for some other where the problem is deeper then it may arise only on a certain web server software or certain operating system.

Good reading!
Remember, if you'd like to get the development done faster then contribute as a Patreon. Only the basis already given (and *unstable* as you say) is worth much more then the largest contribution in the offert.

Have a nice summer

**Comment by Nigrini** [comment]
@polynamaude 

I think what I am going to do is to "rewrite" the documentation, more accurately would be to say add on to the existing documentation. Regarding the SR2, I must confess I did not kept a record and thinking of it now I am a bit angry at myself for not doing so.

I have a set up sort of a "test lab" and will be more than happy to try and reproduce my actions.  I will send you and/or Pierre everything that I did in a hopefully understandable format so we can keep track of the changes.

I wasn't sarcastic about the SR2 part, but I seriously don't know where it fits in. Personally I stumble across the software on version 14.9 and I was busy playing with it when I saw version 15 is available. Not long after version 15 the software let me know 15.1 is available. I was actually searching for solutions om the problems that I was having by using 15.1 that I saw the 15.1 SR2 and  nowhere is it explained what the difference is between the two.

**Comment by polynamaude** [comment]
@Nigrini We'd be more than happy to get help with making a more complete documentation.
Relating to RC (Release Candidate), I firmly believe that it's not something we have to discuss or explain here. Those are thing that people planning to operare a website should master. And the same goes for the word filesystem, the notions of DNS, SMTP, etc.

We ain't gonna teach people from the ground up. If you are planning to operate a website then either you should have the knowledge required or team-up with someone who do.

If I go out and buy a electron-scanning microscope and try to find in the user manual what's an atom or an electron then it's pretty much a sign that I wen to buy something that I don't have knowledge to use or operate. I'm not saying someone who don't know what's a Release Cycle can't install a website. What I'm saying is this person should have the good work habits of making some research and learning. And if the answer is "have no time" then pay someone or change your plans.

If those basic reflex aren't developed then you'll get more than your share of **_RTFM_** and / or **_"This group is for supporting a specific product not general web development questions. Go to StackOverflow !"_**

_What you know in life is worth close to nothing. The value reside in having the understanding of what you don't know and the perimiter of what you understand. Afterward, get the information needed by validating your sources._

Actually if I follow what you say then we shall be explaining how to use the **git** version control system because we use it for our repository. We should also explain both of Apache web server and Nginx web server because they are used to serve the CMS. Also we shall explain what's a JPEG with all the different encoding, what's Javascript/EcmaScript, PHP, HTML5 and while we are here why not a chapter on how to install Linux. I'm also missing the most important part, a good 100 pages on installing a server and configuring your network / firewall / router / modem.

I expect you to get the point by now.

If you think "That's stupid, teaching how to configure network. People operating website shall know that" then I'd simply add "People who intend to install software not meant for end-user should have what's needed or be able to search for". If I sell / publish a library for the PHP language then I'm not going to explain how to do coding because people who use library need to have the knowledge for doing PHP development. But tt's not because they can install the library that they'll be able to use it.

You can go out and download a trial relase of AutoCAD. It's a many thousand dollard worth software for engineering design. Does the book explain what's a Radian ? Certainly not ! I can click on the installer and see the finish dialog after clicking **next** many time. Does it mean that I can afterward call the technical support and get help on how to build a space shuttle or the uses of different degree type for reporting angle. Again, I think we're going on the **NO** side.

I have no doubt about your good intentions but you have to understand the limits. I can tell you to use **diff** to see the differences between to source file but don't come back askig me the options for this command. It's not that I don't know but that I have limited time and if I do use all my time to answer such question then I won't have any for real stuff.

Do some reading about the MVC design pattern, software development, etc.

When you say that you are going to take send the changes or whatever "keep track". We already have all of this.

https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/7ebcda1fd55e2b98a6969ae906f3d873287ba9c5#diff-3cc326d3ac29d003a26569f2fd3fc336

If you did extract the complete archive then you just went back some version. That's all ! But because some of the configuration information reside in the database you are still with the options you've setup.

You're gona be editing some template file (HTML,JS and some PHP) to make your site custom. At least that's what I'd expect from someone who'd like to have his own social dating site. Do you have any idea what's XSS ? Stored XSS ?

On a last note, any professional knows that it's a pretty dumb thing to run the latest version of a software for production. Unless you want your production site to be used for discovering bug. Do you think that architect use the last version of AutoCAD ? Certainly not for product ! At most a handful of compute to see what's new but the bulk of the team run on a version 2 - 3 years old. They are producing not bug testing for Autodesk (AutoCAD's software firm). Do you think that office work in law firm work using the last version of Microsoft Office ? Again, no ! They want something stable. Same goes for hardware. I worked for a pharmacy group for some years, we didn't run the very last released version of Dell computer. We always made the choice of a model that's a bit behind so we'd have a good base of experience if a bug arise.

**Comment by Nigrini** [comment]
@polynamaude - With english not being my first lanuage, I suspect some communication gaps. So let me try to explain.

- I know what RC and RC2 means.
- I was more than happy to apply the fixes that was provided to certain issues that was found on V15.
- I did not expect an "official" RC on 15.1 so soon

Most importantly I am interested in the changes that was made between SR2 and the final V15.1 release because that changes resulted in V15.1 being more unstable than the RC2

**Comment by polynamaude** [comment]
@Nigrini You can enable the modules by editing the database table directly. See inside
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_Core.sql

There's a module table.

**Comment by polynamaude** [comment]
@Nigrini 
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/modules/admin123/forms/DisableModuleForm.php

Click on history and you will see all the changes made.

If you click in the 2nd column then you'll see the related **commit** . From there you'll see the description of the changes and if other files are related.

So you can modify only the pieces needed instead of faking a release. (aka learn the basis of debugging and programming).

**Comment by polynamaude** [comment]
@Nigrini What's the goal of running a website when you aren't a technical user? It's like buying a car and not knowing to drive?
Are you gonna depend on help group at every problem you got? Make an effort and I'll help too.

**Comment by Nigrini** [comment]
You must ask that question to someone else.

Personally I have a Diploma in Information systems and 'n Degree in Psychology. I was a developer for a long time, starting out with COBOL and Natural Adabas. But for the past 10 years or so I am part of management and spend my time running a business.

So I am more than capable of jumping into code if I have to and get back on the horse and start learning PHP. Currently I just prefer not to spend to much time doing so since I have more than  enough other issues taking up my time.
