### ISSUE TITLE
Minor Bug: Typing a message ?

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#560]
I notice that sometimes when typing a message the character count +1 when you press the space bar, but the cursor does not move one space to the right. This is random and may happen in one message but not in another.

**Comment by polynamaude** [comment]
@Nigrini The cursor does not seem to move but the system do receive your empty space. It's something related to the formatting of text when displayed.

**Comment by Nigrini** [comment]
Yes it's a weird thing. And it makes it difficult to trace because it is so random. But I consider this as minor, because you can complete your function as planned.

**Comment by polynamaude** [comment]
@Nigrini No it's not a bug, simply type a text in a word processor and depending of the formatting, you'll get the same effect. I don't remember the exact word for this in English (but will surely write a message when I find it). It's caused by the spacing management between word. For example if you write a space on the end of a line and you have a word following it, then even if you add another space on your end of line, you won't really see it. It's a typographic adaptation, somewhat like the **_widow and orphan_** rules used when writing but used for spaces.

If you change with the style of your message through the use of CSS then you can disable it. Use the developer tools in Firefox / Chrome and directly edit the style of the form you are typing in. You will see what I mean.
