### ISSUE TITLE
Meta Title Problem

### ISSUE THREAD

**Issue by ghost** [pH7Software/pH7-Social-Dating-CMS#569]
Hi, I got a suggestion to improve PH7CMS. I notice when I put in my home page title under meta tags the site name under general settings > global settings appears after the home page title. The problem is I want my meta home page title to be, "Disabled Dating Personals - Best FREE Disabled Dating Site". But when my site name is, "Disabled Dating Personals" and I add my meta home page title it shows up as, "Disabled Dating Personals - Best FREE Disabled Dating Site - Disabled Dating Personals". So it repeats the site name and the only way to fix it is to remove, "Disabled Dating Personals" and keep only, "Best FREE Disabled Dating Site" as my meta home page title. But then my meta home page title is reverse and shows, "Best FREE Disabled Dating Site - Disabled Dating Personals". So my suggestion is to have it so the meta home page title is separate from the general settings > global settings > site name so I can create my own meta home page title to fix this issue. Or have it so the general settings > global settings > site name is in front of the meta home page title so I can just add my slogan as the meta home page title that way the meta title will not be backwards in Google search engine or any other search engine. Thanks.

**Comment by pH-7** [comment]
Hi there,

You will need to amend the slogan, since it is also added in the webpage title.
Go to Admin Panel (generally mysite.com/admin123) -> Setting -> Meta Tags/Homepage Texts and update the "slogan" field to something else.

https://ph7cms.com/doc/en/how-to-change-promo-texts-on-homepage

Here is how the `<title></title> is generated https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/templates/themes/base/tpl/layout.tpl#L10
You can also remove the "slogan" or the site name in there if that's better for you :)
