### ISSUE TITLE
Can't enter the Chat Room

### ISSUE THREAD

**Issue by dimuller** [pH7Software/pH7-Social-Dating-CMS#572]
Hi, I'm still struggling with some modules.
As IM is not working reliably I tried to use the Chat module, but without success.
After a click on Chat the following window opens:

![ChatRoom](https://user-images.githubusercontent.com/51194360/59155122-2ae26980-8aac-11e9-808f-88370bbda146.jpg)

I entered the username, selected the gender and clicked on Enter, but nothing happened.
No error message, just nothing.

Does anybody have experience with this module?

**Comment by Nigrini** [comment]
The Chat function is a 3rd party application, that you can change in Admin Panel. I have not experience the same problem as describe by you, and have no idea what is causing it. If I were you I would do the following just to test:

Option 1
Install the chat program BlaB! AX and in the admin panel point the chat to the new BlaB! AX. 
If that is working and you do not want the users to make use of webcams you can keep using that. Or you can upgrade your BlaB! AX to the paid version.

Option 2 (Used by me personally)
Get the paid version of HTML5 chat. The quotation from them to integrate with ph7Builder is $20. That is not bad even for South African Rand / Dollar exchange in my case. All in all this will be $40 and you will have an integrated chat.

I am also looking forward to a reliable IM module

**Comment by dimuller** [comment]
Thanks a lot!
Yes, it's a 3rd party, that's why we can't do very much except looking for another option like you did.
So the original one which came with the installation worked for you?
Anyway! I will follow your recommendation and try your two options. Actually the first option without webcam would do it at the beginning, but I will definitely have a look also at your second option.

By the way! The video problem is also still pending. In my case I even don't come to the point where ffmpeg.exe is required. Already the initialization is going wrong. As soon as I know more I will let you know. Unfortunately I don't have much time for an investigation. PHP is new for me, so everything takes more time than usual.

Anyway! Thanks again for your help.

**Comment by dimuller** [comment]
As alternative to the standard chat I tried now freichat.
The issue "Freichat integration #541" was already discussed earlier.
I went in depth and could successfully realize an integration. I created a freichat driver, which can easily be integrated in the freichat software. Hopefully they will distribute it already.
It't actually very useful and can replace the IM and the Chat. Both are not working well in pH7CMS.

![freichat](https://user-images.githubusercontent.com/51194360/59488453-c78c7900-8ea9-11e9-94d2-c2649ad965e4.jpg)

I tested the free version, the full featured version with a one time fee supports also video chat.
I guess this would also solve the problem with ffmpeg.exe and we would not need to upgrade to VPS hosting.

**Comment by Nigrini** [comment]
In my opinion there is only 3 things outstanding that would make ph7CMS a complete solution.

1. IM Module needs a fix because it is a great tool to entice users to upgrade their membership status.
2. Private photos. If you use the site as a community and not dating this function is a MUST !
3. If your user = Couple, then X and Y must be able to fill in a profile detail

maybe we can work together on a couple of things, please let me know if you are interested and I will send you my contact details

**Comment by dimuller** [comment]
For me the IM and Chat room issue is solved with the integration of freichat.
The existing IM in pH7CMS is as you know faulty, not responsive and by far not as powerful as freichat.
The code maybe is not as beautiful as the pH7 code, but it's working, and that counts.
It's also Open Source, so you can make modifications.
Nice is also that you can from the chat window send files, insert smilies, save and delete the history.
To bring pH7's integrated IM to this level will almost be impossible.

Actually I just help my wife. She is running a dating business.
I have my own business and work on pH7 only in my spare time. I'm also not yet familiar with PHP and the whole web environment. I'm programmer, but I'm programming CAD software in C++.

Anyway! I see that you are very active in this community and your contributions are valuable.
So why not team up and find some common ground?

**Comment by Nigrini** [comment]
Your integration with Freichat, do you pull the existing users, or do they still need to register separately

**Comment by polynamaude** [comment]
@Nigrini Hi,
In a simple way to describe the chat in pH7CMS is simply a outside website that is displayed inside a window in the CMS. So there's no exchange of real information (like user name), it's a simple call to a URL. Let me take a look at Freichat and if I can easily do an integration. Some people seem to think all of this is easy but it's not the case. There's a a need to authenticate the user, not only identify him. You wouldn't want someone to login as another user by directly calling a URL.

Does this make sense to you ? If not, then I'll add a scoop of information !
Have a nice summer

**Comment by Nigrini** [comment]
Hi 

No this makes perfect sense. 

The problem with a simple call to a URL is that a user can then bypass the ph7CMS software in totality, and access the chat directly by typing in the URL. And secondly he/she can register with a totally different username as the one that is being used on ph7CMS. 

That may work in a perfect world, unfortunately this leaves the door wide open for people to misuse, and you can end up with people using the chat function without being a member of your website simply because he/she obtained the URL from someone.

As I said before, I really like the script a lot and I believe that if the following aspects can be sorted out the script will be right up there with the likes of WoWonder.

1. IM Module
2. Chat to be integrated with the system and not a call to a URL
3. Ability to make photos or a photo album private. 
4. If the software is used for a community then a timeline feed would be nice to see what the people are posting with the ability to like and comment ... About like Facebook.

I understand that the above may amount to a massive task (I have no idea) but I see PH is working towards a version 16 and if the 4 points are going to be included in that version he will totally rock the whole online community/dating scene.

And on a personal note - If he can add a payment gateway that is AFRICA friendly like Payfast will be awesome. None of the current gateway options cater for Africa and 2check out closed it's doors on any form of online dating sites no matter where in the world you are.

**Comment by polynamaude** [comment]
@Nigrini Hi,
I think there's something that is not getting understood properly here...
All of the options you are talking about are available quite easily with a software like Elgg or UNA.
This CMS is more akin to a CMF, it's a framework upon which you can build something. Not an out-of-box solution to be used as-is. Think of it as a proof of concept.

What I see here is many person who thinks that you can operate a dating site in two weeks without much technical knowledge. Yes this is not a false statement but you'll get something that is pretty limited and without a custom look'n feel.

Yes, I know that PH make such statement but that's what we call publicity and should be taken with caution (like all such statement).

You can look at the milestone for the release 16.
https://github.com/pH7Software/pH7-Social-Dating-CMS/milestone/9

Not to be rude but other than me, I don't see much people giving out time to help with pH7CMS. So the development is limited by scarce resources. I get all the good reason, and the one that make me laugh the most "I'm scared of breaking something"... So ? If it does break then we'll simply discard it but we'll be happy to see someone who gave time.

For your concern regarding the use of a simple URL call. This is the normal and standard way to interact with external services. You can limit the ability of someone to call the URL by putting rules regarding the referer in your web server configuration. You can also add a special token to the URL and validate it.

In the last year, I've read such statement about how thing can be perfect too many time. I'm just asking myself if people really think we don't already know those limitation.

On a final note...

One of your computer forum based friend that you said I was being rude with, well... how can I say...

He exactly told us that we are wasting our time in the last two years trying to replicate what already exist with IM and timeline, that we shouldn't try to reinvent the wheel by making a new Facebook.

So for this one, before shouting that I'm rude and if this project will go down, then I'll be one of the cause, that I disregard users with limited knowledge and everything... Please take a real deep breath and remember that you may only see a small part of what's really going on. If I do make the choice of such answer to those user, there may be a pretty good reason.

I don't see people contributing much, except for opening issues (and opening Github account for that exact reason, for sure not because they have interest in software development. Only because they want something).

**_And on a personal note - If he can add a payment gateway that is AFRICA friendly like Payfast will be awesome. None of the current gateway options cater for Africa and 2check out closed it's doors on any form of online dating sites no matter where in the world you are._**

... ? Why don't you start by doing part of the job... maybe you can do some research on the API used by Payfast to see if it's compatible with pH7CMS (on this side I'm pretty sure), how does they work with developpers, do they offer sandbox for trying with dummy transaction, etc. Get back with some answer and again, I'll take a look at what can be done.

And same goes for the list of 5 features you wrote. Give me some UML/Design Pattern/Logic schematics and I'll continue on. No this does not require deep knowledge of PHP....

**Comment by dimuller** [comment]
Hi, and sorry for long silence due to a trip. Now I'm just back and saw the comments.
First at all regarding user registration.
Freichat can be integrated in pH7CMS in a way that it automatically accesses the actual user base.
No registration is necessary and only registered users of pH7CMS can chat!
Who is interested can get my pH7CMS driver, which has to be added to the Freichat SW before installation. I can also help with the integration.
Ok, that's the answer to Nigrini's question regarding registration.
Now I will look into the rest of the conversation.

**Comment by dimuller** [comment]
polynamaude, as previously mentioned no separate registration is necessary and only pH7CMS users registered in the database can communicate with each other.

**Comment by dimuller** [comment]
Nigrini, I will check if it's possible for non pH7CMS users to register. But give me a bit time. As I said I'm just back from a trip and pretty busy. Thanks

**Comment by dimuller** [comment]
Hi polynamaude, you are totally right in many aspects.
pH7CMS is a great base, but if you take it as it is it will hardly meet all your requirements. For this reason it has to be customized, what is not possible without the necessary technical knowledge.
I'm not a PHP pro, but I'm programmer and I'm using pH7CMS to achieve the necessary knowledge to get into it, but this takes time because it's just a side business.
I made already a number of modifications, but I mainly adapted the SW to my personal needs.
I would love to contribute actively to the project and I will do so when I have the feeling that it's useful for everybody, like the integration of freichat.
I'm also willing to discuss my modifications with you and other members of the development team.
Maybe some of them could be interesting even for the public.

**Comment by Nigrini** [comment]
Hi

I have the paid version of HTML5 Chat, and currently anyone with the URL can jump into the chat like an Olympic gymnast. Luckily I am on a month 2 month and will swap it out for Freichat then.

I downloaded the Payfast Gateway available on Github and go through it to see what I can learn regarding implementing it.

**Comment by dimuller** [comment]
@Nigrini, Hi
Now I've checked the accessibility of the chat by non pH7CMS users.
It is possible to restrict chat to registered pH7CMS users only. So you can't chat as long as you are not registered in the user pH7CMS user database.
