### ISSUE TITLE
Error connecting to your database during installation

### ISSUE THREAD

**Issue by clarry2443** [pH7Software/pH7-Social-Dating-CMS#574]
Error connecting to your database.
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'
how do I resolve this please!

**Comment by polynamaude** [comment]
@clarry2443 How about starting by the basic stuff of life ?
What a great information you've got here (or the lack of). What version are you using (????), are you installing with Softaculous (???) because this look very simply like someone trying to install twice in the same database. The message is pretty straightforward, it says that you are trying to insert two records with the same primary key.

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

**Comment by pH-7** [comment]
Hi there @clarry2443 

Are you sure you install pH7CMS on a new fresh database?

If so, can you create a new database through your phpmyadmin and run the following files (in the same order)
* https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/master/_install/data/sql/MySQL/pH7_SchemaGame.sql
* https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/master/_install/data/sql/MySQL/pH7_Core.sql

And let me know here what you get as error :)

**Comment by pH-7** [comment]
Hi there @clarry2443 

Are you sure you install pH7CMS on a new fresh database?

If this isn't the case, can you create a new database through your phpmyadmin and run the following files (in the same order)
* https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/master/_install/data/sql/MySQL/pH7_SchemaGame.sql
* https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/master/_install/data/sql/MySQL/pH7_Core.sql

And let me know here what you get as error :)

**Comment by pH-7** [comment]
Hey @clarry2443 

I haven't heard from you for a while!
Have you managed to solve the problem?
