### ISSUE TITLE
Unsolicited contact is not appreciated.

### ISSUE THREAD

**Issue by koenpunt** [pH7Software/pH7-Social-Dating-CMS#58]
Among me there are probably a lot of other people who received an email from @pH-7.

I see advertising a repository this way as spam.

**Comment by pH-7** [comment]
@koenpunt Hi there, I'm sad to notice you that thought it was a spam, because it wasn’t at all. Just saw your profile three hours ago and really thought you would be the good person for some feedback. Apparently you are not the good one. Next time, please  don't create a issue for this kind of comment.

**Comment by koenpunt** [comment]
> really thought you would be the good person for some feedback. 

How should I give feedback on a product I don't use? Asking for feedback from random GitHub users, by saying "I believe you may be interested to my project" is definitely advertising.

But, if you really want your code reviewed, you better reside to sites like: http://codereview.stackexchange.com/

You won't make friends by sending out such emails. 

PS:
> [Email spam](https://en.wikipedia.org/wiki/Email_spam), unsolicited, undesired, or illegal email messages
