### ISSUE TITLE
Very New to Ph7

### ISSUE THREAD

**Issue by coop59** [pH7Software/pH7-Social-Dating-CMS#581]
Hello Everyone,

I have this up and running, I guess I need some pointers on configuration items. I have gone through the admin panel a few times and I can't figure out how to limit the location by that I mean I want to limit the signups to be from one state like: Ohio and no other states or countries is there a way to do this? Also I would like to be able to have particular cities as choices as well, can that be done? Does anyone have a good tutorial document that can help with this? Also I need to be able to edit the Privacy Notice and Legal Notices as well, where do I find these to edit them? Now I do know that these are probably text documents within the pH7 CMS directories so I am very very comfortable using cli and Linux. 

This is running currently on:
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Kernel Version:
Linux version 4.15.0-54-generic (buildd@lgw01-amd64-014) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019

Thanks for pointing me in the right direction,
Michael

**Comment by polynamaude** [comment]
@coop59 If you're used to using CLI then use **fgrep** to search inside the repository for the files you want. For example when you talk about the privacy page then simply use part of a sentence and search through the file with this string.

Regarding the ability to limit to specific city or state, you'll have to add this yourself. The GeoIP library is used and you may have to use the commercial version for better accuracy (not sure here if you really need it). By the way, the location is based on the IP so maybe you should use a different way to limit the user registration because someone using a VPN will be blocked.
