### ISSUE TITLE
I have lost my stylesheet and still have mobile device issues?

### ISSUE THREAD

**Issue by Undefined-Variables** [pH7Software/pH7-Social-Dating-CMS#582]
I have created a issue on my install of ph7cms, the style has vanished and I have tried everything to fix this and read for hours but nothing solves it. This all started because I was trying to get my SSL certificate to work on mobile devices and it wouldn't work no matter what I did but my host provider said the problem is the images on the site are using http not https so I looked for hours and couldn't how they are tied to http and thought the other thing it could be was the cache. So I deleted all the folders from _/protected/data/cache then replaced them with new empty ones and then chmod 777 them. Reload the browser and stylesheet has stopped working? I have checked the new cache folders and all have the same in them as before I wiped them. 

Something odd also happened with my .hsaccess file as I had earlier made changes in it to force https and after the steps I took above it had the old values in it again, is this included in the cached data? So right now I have no stylesheet and I still have issues with images being http please could you help? 

Thank you

**Comment by Undefined-Variables** [comment]
just noticed typo .htaccess is what I ment :)

**Comment by Undefined-Variables** [comment]
Just to add I have run this query in mysql... I had to use it after moving the admin123 folder! It worked that time I don't see what is different now.

INSERT INTO ph7_settings (settingName, settingValue, description, settingGroup) VALUES
('backgroundColor', '', 'Overwrite background color', 'design'),
('textColor', '', 'Overwrite text color', 'design'),
('footerLinkColor', '', 'Overwrite footer links color', 'design'),
('linkColor', '', 'Overwrite links color', 'design'),
('linkHoverColor', '', 'Overwrite links hover color', 'design');

UPDATE ph7_modules SET version = '1.4.3' WHERE vendorName = 'pH7CMS

**Comment by Undefined-Variables** [comment]
I have done a fresh install but the problem is something to do with .htaccess file. When you unzip the downloaded folder all the code is compressed in a few of the folders and its impossible to read that way so I open it with text editor and it pulls it back to a human friendly state, however when you save it you get a server internal error but there is nothing on any of the logs. I am doing install now using https but I need to change settings in htaccess but now im worried it will break again? Any ideas?

Also still have the https issue, and its only on the splash/login page registration loads on mobile with padlock and green tick but login page its not happy about something? Cant believe I had to reinstall im back at square one again...

**Comment by Undefined-Variables** [comment]
I give you permission to have a good laugh cos my fresh install is exactly the same so I have an issue on my server and deleted everything for no reason :( Its been a long waste of a day I am going to bed and I will look at the server issue tomorrow with a fresh head.... Anyone have any ideas? Ive not changed anything on my server today! This is just madness!

**Comment by Undefined-Variables** [comment]
Okay new day and I have upped my game, I have installed xxamp, composer, FFmpeg on windows 10 laptop that has 32g of ram and nice graphics card so I can easily mess about with it. Im now taking back ups as I go and took one before then after run time so when something goes bad I can replicate it in moments not hours! So going to take it slowly and will let you know how I get on 📄

**Comment by Undefined-Variables** [comment]
Final update you may close this thread down, thanks for all the help... NOT I have it sorted now, I have it running on my laptop and it works very nice, I have set up google, paypal and sms api's all working as they should and solved the chat issue, all you need is a separate server running a chat room like phpfreechat or phpmychat plus (tried both and both work well) then put the url in the api field in the admin panel and there you go your own chat room. I would like the code to yours @pH7 and will give you a $100 for it if you are interested as looks nice but what i have is functional just have to get it on to the real server now, going to do a fresh install first as there is a issue, seems to happen on installing sendmail, so going to try and set up dovecot as a back end! Great code pH7 very very sercure and doss protection works well even again tools like HOIC so was imprested with that :) keep up the good work im outta here :)

**Comment by polynamaude** [comment]
@Undefined-Variables Hi,
It would be great if you could keep your issue brief and make the title (and discussion) related ?

There's two uses for this type of forum.
The first one is to help in the follow-ups on bugs that may be found by users.
The second one is to serve as a database of resolved-case so that others may get help.

We are quite loosing it here !
I have made a nice page giving out some tips so you can make it easier for others to help you out.
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

You have to understand that when we first look at the title you wrote : 
**I have lost my stylesheet and still have mobile device issues?** 

At first my answer would be quite simple because this is probably related to the caching system. Simply go into your database, you'll see a table with the setting in. Modify the value for "cache" and "compression".

The problem is that if I'd like to make sure that I'm on the right track then I'll have to go through a novel by Stephen Spielberg alike...and the story goes on with some "bla bla" about chat, etc...

Yes we're all quite social and we take pleasure helping out. But if you want to get help, you'll have higher chance if you do make it easier for others.

The Windows operating system is awful for web hosting. If Unix based OS do account for more than 90% of the server on InterNet and goes higher if you talk only about Web Server there's a good reason behind it.

With Windows you'll get problem concerning CR/LF translation and others that may arise. But that's another subject, not related at all to pH7CMS.

Like written in the docs
**_Keep in mind that for security reasons, these kind of software is only recommended for a development/private server and not for a production server. Please refer to the website of the software for more information._** (Talking about using non Linux / Unix host).

It does not take much efforts to write down a clear message with punctuation and spaces between lines. Not much needed and it does give a better image, is easier to read.

**Comment by polynamaude** [comment]
@Undefined-Variables On a last note,
When you rename the **_admin123_** folder you simply change the name of the constant defined in the file constants.php

https://ph7cms.com/doc/en/rename-the-admin-folder

There's no _magic_ in computing. So the sentence _it worked that time_ is good only if you have a good idea of what you are doing.

Take a good look at the docs before opening endless issues.
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki
http://ph7cms.com/doc/
http://ph7cms.com/blog

I've noticed that the only reason you seem to have created a Github account is in relation to opening issues here. Don't get me wrong, as a community we are more than happy to help new user. But if you build yourself a reputation of asking what we already sorted out then at first you may still get answers but on the long run, you'll simply get ignored.

Same goes for unrelated question, we support pH7CMS, we don't do general computing support for your whole ecosystem. If it's something specific to pH7CMS and related to Apache then you are at the right place. But if what you expect is help in regards to options in Apache configuration files or **htaccess** then no, that's an Apache support group.

The more professional you will act, the more chance you will have of getting quality help.

**Comment by Undefined-Variables** [comment]
Yes okay I can totally see your point, It started with the stylesheet then lead on to other issues and stopping the install and waiting for a reply would have been like giving up on it.

I would never run a production site on windows that is a terrible idea. My problem was I have a server running Ubuntu that I will eventually have as a production server but while I was messing around with style and setting the constant upload <-> download to and from the real server was causing me more problems, komodo edit is a funny program and some times it will connect and play nice others it just throws errors at you. So what I was saying was I was going to stop testing on the real server. 

I only said about the chat cos I have seen a lot of people struggle with this and thought it would be helpful I am fairly new here and I was pulling my hair out after spending hours getting it perfect then I lost it all. 

I have now learned my lesson and have a fully working site but its on the development laptop! Im sorry for my overspill of thoughts. I think it is very well written and have enjoyed working with it!

**Comment by Undefined-Variables** [comment]
The first time I renamed it just as you say in the constants only and I lost the folder and the new name was getting a 404 error back and i had to read though lots of issues on here and came across the post by PH with the database insert statement to reset the colors. I followed what he said and it solved the problem so when the same thing happened again I expected the same result and that did not happen. 

Everytime I have installed and renamed it since I have renamed the folder in constants and also renamed the physical folder in _Protected/app/system/modules/admin123 and had no issues at all doing so. 

I came here looking for help because all over that code there are notes and comments saying things like if you need help or have a question or suggestion feel free to email me, I got stuck so many times before I emailed PH once and he told me to come and post a issue here, I didn't realise this community was like the way you described, I have never posted or joined because I have little value to add here but I have been a deadicated reader for many years and always felt friendly and welcome. Not so much now! 

I wish you the best with the project and I am going to close my account!

**Comment by Undefined-Variables** [comment]
One final thought before I go, I still have half the issue I OP about, the sites login page will not load on mobile devices like iPhone and android devices with a secure connection (https) but it will load all other pages no problem. After much investigation I finally called the hosting company that sold me the certificate and they said that apple wont except my site as being secure because there is a http element on that page. I cant figure out how unless its the video that moves as a background? Some advice on this would be appreciated. Thank you

**Comment by polynamaude** [comment]
@Undefined-Variables I'm not sure what you are trying to put forward here by saying you are going to close your account and that you didn't know that this community is **_like the way I described_**.

If what I say does not make any sense to you then you can simply ignore what I write, no one forces you to follow any advice.

Yes we like to help people and we need people to use (and build community).

Maybe you are missing some parts here...
Yes indeed the SQL statements you wrote did reset the colors.
But this has nothing to do with stylesheet  (CSS) !

Yes CSS is used to define the colors of the elements in your web pages. But this SQL statements is related to something different. If you problem is a global CSS then it's mostly related to cache (and this is why I told you how to disable it).

You can try by yourself by making looking inside your page sources, you'll see the link to the CSS files. Try to open one and you'll get an empty answer.

Again, as you say, I did everything like before and expected to have positive results but that wasn't the case.

There's something called "**_Differential Diagnostics_**", we teach those techniques to doctors of medecine, doctors of psychology and such. In a simple way :

If you did exactly as before and the results are different then there's no magic there. It's because something changed in between.

Start on a known base and go on from there. Everything worked with verson 12.9 then start with this version and do all the manipulation. Everything goes great ? Then go on and change of version, change of options, etc. By looking at the differences one by one, you'll see where breaking changes occurs.

If Pierre Henry told you something then simply wait for him to take a look at your issue and ignore what I wrote (as already said).

You write **_I have been a deadicated reader for many years and always felt friendly and welcome_** how can you feel such if you never interacted with this community ?

**Comment by Undefined-Variables** [comment]
I was not being funny at all, I have read here for years and I see the comments between users and the way people answer questions and have always felt it to be a friendly place so when you basically said if you have nothing to contribute to our community and only come here with your issues nobody will want to talk to you and you will be ignored. What is someone supposed to take from that comment? 

I do understand html, css and the classic php style of writing code but I will be honest and say I struggle to get my head around this object oriented way of thinking. Maybe its cos its never really been explained to me like classic php but the -> and $this-> and the fact there is so much going on but in different places like controllers, models, views and classes makes it harder to keep track off. I want to learn how it works properly and spend a lot of time just reading other peoples oop code but its slow progress. 

Good advice with making notes and back ups. I think that is a good start and also only making one change at a time would help me. Thanks for the advice though.

**Comment by polynamaude** [comment]
@polynamaude Where's the problem ? You didn't like when I said that we are not Apache technical support ? No and that's true ! Go to the good place if you want good answer. I don't ask the cook at the restaurant to cut my hair. Again, as we are somewhat used to pH7CMS and have years of experiences we can see easily some problem that comes over and over. And when this arise, we'll help out, for example the need to disable **modsecurity** or the options in Apache to redirect to SSL. But if your problem is more specific then maybe it's better to go to the Apache support group.

Again, this is one example, no reason to cry or run away.

You ask for help, we give you an answer and now you say we are unfriendly. Damn, you must have a really good business plan.

If indeed you have been reading the discussion on the Github repository for many years then most of what I said should have already been known.

If I have one hour a day to give to this project. What do you think I prefer ? Answer the same question over and over again ? This doesn't mind when there's complexity and possibly different outcomes. But if someone ask a question that was already answered because that it's impossible for them to search the discussion then I'll have less time to do some coding.

You didn't like that I refer you to Upwork ? Again, look at the issues, it's not the first time I do so and Pierre-Henry do the same.

Oh, on a final note. By respect for developers, don't offer 100$ to people for coding. You are talking about 15-20 years of experience. It doesn't even cover the opening of a service call in my case. And even if he'd like to accept your offer then I doubt he'd know what you are asking because it's far from being clear !

**Comment by polynamaude** [comment]
@Undefined-Variables I never wrote something like you said and neither did I say "If you have nothing to offer but just come here to open an issue".

Either English ain't your primary language or you have problem getting it right. What I said is clearly simple "I noticed you opened your account on Github and right after you created this issue". So what I wrote you is some tips if you want people to help you out.

That's it, I'm over.
Someone else will help you. Good luck !

**Comment by Undefined-Variables** [comment]
My primary language is english and that means the same thing in my book! I am british so maybe I just took what you said the wrong way! I apologize and I dont want anymore help I will get there in the end :)

**Comment by polynamaude** [comment]
@Undefined-Variables Take a huge breath, drink a bottle of water, a coffee or whatever you like. But ask yourself, is this the place to learn about doing backups and debug procedure ?
Not really...

This does not mean that because you don't have what's needed to run a web service and do all the development that you are not allowed to ask question here. But keep in mind that if you do ask question that we already answered or question like "How do I comment a source code line" then you may get a first answer. But in the end people are simply going to ignore such question because you can get this answer at many other places.

Yes I already got such a question about the way to comment out a PHP line.

If all I say make sense then take it into account, grow on from the knowledge of others.

The Object Oriented model has been around for quite a while now. You can find many books by googling around. I can suggest you simply search "PHP Object Oriented WordPress" and you'll see an easy free ebook. This can be a good start.

Concerning the controllers, make a search with the word **_Design Pattern PDF_** and **_Design Pattern MVC_**. This should give you some idea.

I'm not in your head, I don't know how you did take what I wrote. It does really sound logic for you what I give you hints to solve your problem but at the same time the goad of my message is to tell you "You're a dumbass, we don't want you here, you have nothing to bring to us" ?

This does not sound right to me....

**Comment by polynamaude** [comment]
@Undefined-Variables Here you go...
[WP-EBK-LT-UltimateGuideToPhp-v09.pdf](https://github.com/pH7Software/pH7-Social-Dating-CMS/files/3409796/WP-EBK-LT-UltimateGuideToPhp-v09.pdf)

[the-perfect-wordpress-development-workflow.pdf](https://github.com/pH7Software/pH7-Social-Dating-CMS/files/3409800/the-perfect-wordpress-development-workflow.pdf)

**Comment by polynamaude** [comment]
@Undefined-Variables If you install a good IDE (Integrated Development Environment) you'll get automatic object discovery and completion.

It will make it easier for you to understand what does the arrow function is used for. ( **_$object->function(param1, param2)_** )

You can get Eclipse for free (my suggestion), Visual Studio Code from Microsoft (free too but I have limited use of this one), Atom.... or even try out phpStorm.

PM

**Comment by Undefined-Variables** [comment]
hmm okay I thought that was what komodo edit was but it dont give any clues like what you just said.

**Comment by Undefined-Variables** [comment]
I have VS on here but thats for microsoft C, C++ isn't it? I am downloading atom now, I started with notepad and when I found komodo I thought that was amazing so never looked for another one. Komodo helps with html/css but not PHP it just highlights

**Comment by polynamaude** [comment]
@Undefined-Variables Well if you do understand what I say then maybe there's step to be taken in life. You don't teach a kid to drive a car before they walk.

Start by setting up your development environment and so some learning. Until then you'll only loose your time messing up your head. Without basics you can't go really far or you'll have false belief that will catch you later on.

A simple example... In javascript, by default if I start a variable with the number zero it will become octal based (8). So if you don't know this one then later on you may think that your problem is solved somewhere because it does work but as soon you'll get a user than enter 08 instead of 8, it will break if you didn't force it to be decimal encoded.

Now, please, if what I said make sense. Don't make me waste my time.
**_I have VS on here but thats for microsoft C, C++ isn't it?_**

What did I wrote ? The answer is FUCK PLAIN SIMPLE

Ask a ten years old kid to Google for you "Visual Studio Code PHP".

Nearly all the editors do color coding of source code. Even the worst one that run on the web browser like Codiad do that.

**Comment by polynamaude** [comment]
@Undefined-Variables 
https://code.visualstudio.com/

https://marketplace.visualstudio.com/search?term=PHP&target=VSCode&category=All%20categories&sortBy=Relevance

Now, it would be nice if you could star our repository on Github and make a nice review on Sourceforge.

**Comment by polynamaude** [comment]
@Undefined-Variables You'll need an IDE with good PHP support if you want to contribute some code later on. It's needed to **_lint_** the source code.

**Comment by Undefined-Variables** [comment]
ok thanks for your time :) you have been very helpful :) I am closing this now :)

**Comment by Undefined-Variables** [comment]
Just want to say thank you for introducing me to atom, oh my god where has
this been all my life? I can see logic in the code and follow exactly what
is happening and the attached browser I have been looking a pages of black
and white text and now it jumps out at me.

Also been thinking about what you said and just by chance I installed
ubuntu, nginx, php7 dovecot postfix and mariadb and ISPConfig what a fun
install that was I think I found what I want to do, I want to build a
server using the command .panel ISPConfig but also I am going to start my
own git. I plan on a ready to go front end marketing / domain control panel
for customer interaction.I am still learning and its my first ever git so
please be genual with me :)  Once I am running and fully stable I will
offer free hosting space to the community  :)

**Comment by polynamaude** [comment]
@Undefined-Variables Maybe again you are seeing too far ahead, skipping step here...
Before thinking about hosting maybe to learn the basic first ?
We're all good "know it all" when everything goes well.
But when problem arise that is where experience and knowledge is needed.

At least twice a month I get that same speech. And the question is "What do you offer that can't be easily done, that wasn't already done and is different ?".

Sorry to blow a fuse, but we are in a world of SaaS / PaaS and you can rent a managed server for less than a Happy Meal per month.

It's not because you "click click click next next install finish" and that you have a running installation that you are managing a server here. Ubuntu ( that is a easy and buggy version of Debian for people who want more bleeding edge but don't know how to install the packages in Debian) is made to be simple to install and close to everyone can do it.

There's a damn huge difference between playing around and doing serious stuff. Learning networking, planning the networking, planning disk space (let me think, everything in the same partition right ?), planning backup procedures... making use-case scenario for software development.

Don't confuse hobby and job.
