### ISSUE TITLE
reopen: DisabledForm and other checkbox forms are unselected (when selected)

### ISSUE THREAD

**Issue by dimuller** [pH7Software/pH7-Social-Dating-CMS#587]
Hi, I looked into this problem and reopened the issue because it is still an unresolved.

I found the reason why the checkbox forms are unselected.

In the **DisableModuleFormProcess.php > __construct()**
two arrays are creates, one with the id's of modules and the other one with the enabled modules. One array is a string array, the other one an int array.
Both arrays are passed to **Checkbox.php > render()** function.

Now the problem is in the following **line 54 in Checkbox.php**:
            **if (in_array($value, $this->attributes['value'], _true_))**
The 3rd parameter is set to _**true**_ what results in type conflict and all checkboxes remain unchecked.
If the parameter is set to **_false_** no type check will be performed and the Checkboxes of the enabled modules are checked.

What I don't know are the implications in other parts of the program if no type checking is performed by the Checkbox item.

**Comment by pH-7** [comment]
Hi @dimuller 
Thanks a lot for this issue! 🎉

This issue has already been fixed. https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/7e5531410c2e37bfc8478754e5d0796c1b7d8e28
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/550

You can do the changes according to the patch available here: https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/7e5531410c2e37bfc8478754e5d0796c1b7d8e28

What pH7CMS version do you use?
The problem was fixed in v15.1.6

**Comment by dimuller** [comment]
Hi @pH-7, IC!
Before I started to debug I searched the code changes, but I could not find this patch. There are so many.
I actually use v15.1.6, but when I implemented my patches something has gone wrong. I overwrote some files accidentally with v14.9 files.
Anyway! Thanks a lot too!

**Comment by pH-7** [comment]
You are very welcome @dimuller!

I see now. Yes, then please overwrite again the old files you overwrote with v14.9 by the new ones from v15.1.6 release.

P.S. If you are happy with the software and the time I spent to build it and help, I would be really happy if you can add a review at https://sourceforge.net/projects/ph7socialdating/ (you will just have to create an account in order to write a review).
This really motivates me to continue developing the software.

Good luck!

**Comment by dimuller** [comment]
Hi @pH-7
done already and it works. Thanks!

PS: I'm very happy with the software! It's amazing what you achieved. It's really a masterpiece.
Please keep on developing. It's your baby, so you can't abandon it ;-)
Ok, I'm joking. I know you won't and I will do my best to motivate you.
Slowly I understood a little bit how it works and hopefully in future I can help not only with writing reviews, but also with some contributions.
