### ISSUE TITLE
Sending mail via relay (recoding Mail.class.php)

### ISSUE THREAD

**Issue by The-Dragon-Queen** [pH7Software/pH7-Social-Dating-CMS#602]
Hey guys could you possibly give me a little help please? I need to send emails (outbound) to a relay before going on to the intended users email account. I have found the Mail.class.php file in the code but I don't know what I should change to make this happen. I'm guessing it's going to take more code but I do not write code and was hoping to find settings that could be altered but this is not the case. 

Look forward to hearing back from you

Regards

Penny

**Comment by polynamaude** [comment]
@The-Dragon-Queen What are you asking ?

No we don't do custom coding for free.

You can find someone that will do so on UpWork.

**Comment by Undefined-Variables** [comment]
I will do it for you if you put a real picture of yourself up and not a cartoon!

**Comment by Undefined-Variables** [comment]
I have just clocked on to what the random link your tispy/drunk message was on friday @polynamaude and no nothing to do with me! @The-Dragon-Queen you have a few options available you could change the code to send mail to where ever you need it but you can also set sendmail up to send all mail to the place of your choosing! I have mine sending my outgoing mail to MailGun who then send it to the correct email address! I will find some info for you!

**Comment by polynamaude** [comment]
@Undefined-Variables Hey dude ! Why don't you start by being able to run the software yourself ?
Hey what about that ?

And stop bothering people around. You open endless issue, you complain at every moment, you accuse people of hacking you when it's not true... And you say "I'm sorry like a kid all the time".

So please, find something useful and stop annoying people around.

In case you didn't understand, this guy didn't talk about using sendmail or whatsoever. He was talking about using PHP. And there's probably a good reason behind this Mr. Know-It-All.

If you want to start saying false stuff like "drunk" message, then maybe you shall invite this guy over to read your crazy rampage....

https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/595

What me to start showing all the stuff you write that doesn't make sense.

**Comment by Undefined-Variables** [comment]
Look please listen to what I'm saying to you, I do not want to fight with you. 

I do run the software myself and have multiple instances of it running right now! You are correct I accused you of hacking me and part of this is true, I was hacked and some files were deleted and I have had verification of this being true however I can not prove who hacked me and nor can the hosting company as it seems the person responsible is hiding behind a VPN, that is the words of the security department at ionos 1&1, they are a hosting company that host a few of my websites. It just seems funny to me I told you everything needed to be able to complete this, and yes it might be just chance that this happened while I was talking to you and to be honest this was my fault for leaving a open API with no authentication there to be hacked in the first place!

Then there was the YouTube thing... That is still playing on my mind and I'm not sure what the hole point of it is/was but it was no normal page, and I am 1 million percent sure of that, but at the end of the day it's no longer part of my source code and I refuse to update my copies because I can not trust the new releases! You would have been better off just being honest with me, I am no angel, and I am sure you know that but one thing I can not stand is being lied to! 

At the end of the day all I want out of this is a working website that I can launch knowing there are no issues hidden within it, every time I think I'm close to being able to release it I find more issues.

The changing of the links is still an issue and I can not see how this happens I am going to be removing these links as part of my redesign and it will be interesting to see if this problem continues! I don't wish to ague with you any longer and honestly think we could do better if we put our heads together and not keep up this silly fighting. 

I have a lot of respect for you and see how much effort you have given to this website, and I am proud to say I have played a small part in it. I am willing to put this behind us and start a fresh.

I said the drunken message because you are always so perfect with your spelling and grammar then out of the blue you send a reply that was lacking in both departments! It was almost like it was written by someone else! 

I declare a truce and will not intentionally piss you off anymore. Do you agree?

**Comment by The-Dragon-Queen** [comment]
No problem thank you for the first answer, not really sure what the second answer is about.

**Comment by polynamaude** [comment]
@The-Dragon-Queen If you look at my 2nd answer, it's made for someone else than you and his comment was deleted.
