### ISSUE TITLE
BUG: Footer Links Change On There Own (Complete with Photo Evidance).

### ISSUE THREAD

**Issue by Undefined-Variables** [pH7Software/pH7-Social-Dating-CMS#603]
__All the cache settings are off! The cache is empty! Look at the photo, my mouse is hovering over the membership link in the footer and look at the address on the left-hand side it says chatboxservices.com!__

![Admin Side Links)](https://user-images.githubusercontent.com/52648055/62368523-ba445000-b524-11e9-97d5-019d3b11b907.png)

__This one is that membership page and again the link is the same...__

![Membership Page Users Side](https://user-images.githubusercontent.com/52648055/62368530-c9c39900-b524-11e9-824a-85645739e567.png)

__This one is of a different link just in case you think it is because above is a new link, it is every single link in the footer!__

![Different Link Footer)](https://user-images.githubusercontent.com/52648055/62369160-a0a40800-b526-11e9-8e64-3986bff916d1.png)

__I've absolutely had enough of these links changing, this is a bug I have tried all you have suggested and I have got the cache off as you can see in the first image. I don't understand how this is happening but I need your help to fix it!__

 @pH-7  __If you are not willing to help me get to the root of the problem I'm going to have to update the feedback I left. I will be honest about this. I'm so sick of this issue.__

**Comment by Undefined-Variables** [comment]
__I've just gone to check the cache and look it's there even though all the cache settings are off! Something is broken, I cleared the cache after I updated settings and before I clicked anything and I checked it was empty after I switched pages.__

![2019-08-02 (33)](https://user-images.githubusercontent.com/52648055/62369960-2c1e9880-b529-11e9-8ad1-3849d4d92c8e.png)

**Comment by Total-Butterflies** [comment]
Hello Team Ph7. 

My name is John, and I am @Undefined-Variables's business partner, I have just sat here and read through the arguments he has been having with everyone on your team! I can only apologise for his outbursts, he is young and naive and a little hot headed. After reading all that I have made the decision to take over this problem on here. He has been having this issue for quite sometime now and this is slowing everything down so could we please make an attempt to solve it? 

He won't be posting here again I have just changed his password on that account and have changed passwords to my hosting accounts, so he can't recover any password reset emails. I can't stop him from making new accounts but if he should contact you, simply block the account.

**Comment by polynamaude** [comment]
@Undefined-Variables Hey you little peace of shit !
Never went through your empty that maybe Pierre-Henry is on vacation ?
That he does have better to do than to wait all summer long for you to complain about something you didn't pay a dime for and that you just expect the world to  be based upon yourself ?

Why don't you go get a life somewhere else ?
If you've never done something useful and just got a goal, that's none our problem.
Maybe you shall invest your time in a real job instead of bothering people everywhere you go.
What's next ? Gonna complain that the cash income didn't meat your expectation so get pissed ?

If you ever wondered why you never got an answer ? Maybe it's also because Pierre-Henry does not have any time to waste with people like you who's problem is caused mainly by their own self.

Strangely we installed this many time and never had any of the troubles you complained about.
And so those the other users.

So you little laptop throwing around and other things you say but regret afterward. We don't need this around, no where. You are lucky enough to be using a keyboard, so you can think before pressing enter and this you obviously don't.

Other than making you family shy, you don't do much. And other than showing the world that you can be stupid and use a computer, that's at most what you do.

Stop thinking the world revolve around you because it doesn't.

No ones like you, be it in the real world or in the virtual one. Because you don't know how to act properly in society. So go see a doctor for Borderline Personality Disorder because you are pretty much that kind of fucker.

**Comment by polynamaude** [comment]
@Undefined-Variables Don't write to other like a real genius with you "Tip of the day"... You didn't know what was a good development environment for PHP before I showed you Atom / Visual Studio Code.
