### ISSUE TITLE
Hey just got home and some really weird stuff is happening with my site! 

### ISSUE THREAD

**Issue by Undefined-Variables** [pH7Software/pH7-Social-Dating-CMS#615]
I don't know how to explain what is happening because I don't  understand myself, I have lots of 127.0.0.1 going on in my access log and all I can do is post a few screen shots in hope you might understand more than I do.

In a nutshell the site is hanging like I've never seen before and is auto switching between IP address, the real URL with mail. Subdomain added and another domain completely, these are screen shots while inspecting with Firefox development tools

![Screenshot (8)](https://user-images.githubusercontent.com/52648055/63465562-707ec380-c459-11e9-8c2b-63dff04cc0f1.png)
![Screenshot (7)](https://user-images.githubusercontent.com/52648055/63465563-707ec380-c459-11e9-98c8-0868152f2144.png)
![Screenshot (6)](https://user-images.githubusercontent.com/52648055/63465564-707ec380-c459-11e9-9c7c-26b580cb11cb.png)
![Screenshot (5)](https://user-images.githubusercontent.com/52648055/63465565-71175a00-c459-11e9-8dcb-63332aaab6b8.png)
![Screenshot (4)](https://user-images.githubusercontent.com/52648055/63465567-71175a00-c459-11e9-98c3-9a1255183826.png)
![Screenshot (3)](https://user-images.githubusercontent.com/52648055/63465569-71175a00-c459-11e9-82c7-a0b7ba556b50.png)

**Comment by Undefined-Variables** [comment]
Maybe a Doss attack I'm not sure I've not seen anything like this before.

**Comment by Undefined-Variables** [comment]
Look
![Screenshot (9)](https://user-images.githubusercontent.com/52648055/63467003-64483580-c45c-11e9-9036-ab9b76d227a3.png)
 at the count now its non-stop

**Comment by Undefined-Variables** [comment]
switched it off going sleep im slightly tipsy so not really going to fix anything like this.. tomorrows problem...

**Comment by polynamaude** [comment]
@Undefined-Variables Hey ! Never went into your mind that maybe it's the Javascript code you did that's causing all this ?

Those are simply AJAX request (the one going to totally-butter.com/assets/ )...

Everything else is related to other problems like for example your certificates for SSL and others...

Look dude, we are not going to operate your site for you.

Grow up a bit here.... No ones has time to loose planning a DDoS on you...

I already told you what to do. Use a version control system like Git so you can go back to a previous state and take note of what you modify so you can identify at what moment you made a breaking change.

I buy your lawn mower that you sell at a garage sale. Two days later I go see you and say "I modified it a bit and it doesn't work, could you help me please".

And over all of this, you don't make a damn effort so that people would like to help you.

Again your pursue saying "I'm making an effort", listen, we are not your family / sister / friend / mother / father / cousin / therapist / etc. We don't care about efforts, we care about results. And when something gets repeated more than five time, that's a sign that it's just the way the person is and it won't change.

I already told you that we aren't there 24/7 and to wait for answers. What do you do, you go on and add "Oh, I'm going to sleep". What's the reason to write this ? That won't change the time it will take for us to answer. You don't seem to get it. Keep it short and simple. It's not a book about your life that you are writing here.

**Comment by Undefined-Variables** [comment]
I have not read the above properly yet I have only been awake for 10minutes I have skimmed over it and get the gist of what you said and honestly I feel like I am taking the piss here by asking something again so soon but please I need you to believe me when I say something is not right, and I am convinced someone is playing games with me.  

Honestly if the shoe was on the other foot I would be saying the exact same thing as you are to me, but that is not the case and I am the one that can see as clear as day the things I have tried to explain, I feel like the mad person that everyone else tries to avoid and I'm really not mad I know that but no one sees what I do! (even that sounds mad).

I have just put http://mail.totalbutterflies.com in the address bar and it loaded a blank page, so I inspect the page like earlier and click on Sources. There is a list, in this list is grammer and spell checker,  Netcraft Extention,  Pop up blocker for Chrome, Pop up blocker Pro, Safe Torrent Scanner. 

I'm sure you know what Netcraft is? Within the Netcraft folder there is a script called Constants.js  and in this script there are assorts of functions, cryptojacker, heartbleed, skimmers, sslv3Url, EvilJSpattenfeed, the list is long and very real right there in black and white in front of me. 

This is not made up and cards on the table time because I have really had enough of being made to look and feel like im a loon because I swear down on my daughters life I am telling the truth and have been since day one.  

I have made a decision and think this is the only way to deal with this. After I send this message I am going to power down this laptop and the server and remove the hard drives. In the morning (a few hours away) I am going to express ship them to GCHQ and request they do a full investigation in to the things that have been happening, I don't know who it is but someone is doing this to me and it can't go on any longer.  

Think I should also tell you I found the files in the software http.php and OAuth.php 

If you have not seen these I suggest you have a good read of them, then tell me I'm wrong!  I know this is drastic but my state of mind has been questioned and this has not been a decision I have made lightly I have thought this though for weeks and I returned after a 3wk issue free break mainly to see if any funny business would start again, I wish hole hearty that it had not but it got worse and from anyone point of view the same conclusion would be reached! 

I still hope I am wrong but in my heart I know I'm not. Im sorry Poly but this has to be done. I wish you all the best and I mean that, I really do.

**Comment by Undefined-Variables** [comment]
I just want to add this for full disclosure! 

I am a criminal I served 5yrs for selling class A drugs on SilkRoad, I was good friends with Ross Ulbight and have seen first hand how technology can be abused by a select few, but there are two lines the legal line which I would happily skip over with out thinking and there is a moral line that just shouldn’t even be thought of crossing. 

The first line is easy to cross because it normally involves cash insensitives but the second line is a very dark place to step over, playing with people in this way leads you down a very dark and twisted path, i adviced Ross against many of the choices he made but he knew best and look where he is now, his life is over and he’s my age! 

Think about the company you keep and never cross that second line because once you do there is no easy way back!

**Comment by polynamaude** [comment]
You live on another planet than most of us if you think that GCHQ (Governement Communication HeadQuarter / Her Majesty Secret Services) is going to take a minute of interest in what you say here. You shall stop taking stimulants and other drugs because the only thing you are is burning your brain cells, getting close to being unable to do more than piss on yourself.

**Comment by polynamaude** [comment]
@Undefined-Variables You really think that they are going to waste time investigating why you are too stupid to secure your own server ? Because it's the second time you get on with this, last time it was a YouTube hacking whatever.... Sorry dude ! They have much better to do than this... for example investigating on people who operate what they think is a server from their bedroom. Start by passing 10 days without putting cheap drug in your brain and you are gonna see clear. Because now that what's called hallucination and delusion.

**Comment by polynamaude** [comment]
@Undefined-Variables Just like that, could you please delete this issue because you just make the whole place look like dumb.

**Comment by rondlite** [comment]
This started about access log..  just want to add there isn't a single line of access log here, just some javascript doing AJAX. The setActivity got hit by misconfiguration of domain names and is now stuck with your non-working domain.. 

![image](https://user-images.githubusercontent.com/3693902/63488356-fa0cb080-c4ae-11e9-9d5b-ddeb8380597c.png)

**Comment by polynamaude** [comment]
@rondlite You say somewhat the same as I do... Except I forgot to mention that we are missing an access log and some localhost (127.0.0.1) that he talked to us about. But as you probably know, we are all wrong. Because today "Her Majesty Secret Services / GCHQ" will investigate. I'm sure he's gonna scan the report to show us how wrong we can be.

Because you know the 1st and most important rule in life. When everyone else say that you are doing something wrong, it's because they are in the bad path.

**Comment by polynamaude** [comment]
- whois totalbutterflies.com 

   Domain Name: TOTALBUTTERFLIES.COM
   Registry Domain ID: 2410785927_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.ionos.com
   Registrar URL: http://www.ionos.com
   Updated Date: 2019-07-08T20:12:32Z
   Creation Date: 2019-07-08T20:12:25Z
   Registry Expiry Date: 2020-07-08T20:12:25Z
   Registrar: 1&1 IONOS SE
   Registrar IANA ID: 83
   Registrar Abuse Contact Email: abuse@ionos.com
   Registrar Abuse Contact Phone: +1.6105601459
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Name Server: NS1051.UI-DNS.DE
   Name Server: NS1073.UI-DNS.ORG
   Name Server: NS1097.UI-DNS.BIZ
   Name Server: NS1101.UI-DNS.COM
   DNSSEC: unsigned

- nslookup totalbutterflies.com     
Server:         192.168.1.1
Address:        192.168.1.1#53

Non-authoritative answer:
Name:   totalbutterflies.com
Address: 176.27.15.0

- whois 176.27.15.0
% This is the RIPE Database query service.
% The objects are in RPSL format.
%
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf

% Note: this output has been filtered.
%       To receive output for a database update, use the "-B" flag.

% Information related to '176.26.0.0 - 176.27.255.255'

% Abuse contact for '176.26.0.0 - 176.27.255.255' is 'abuse@sky.uk'

inetnum:        176.26.0.0 - 176.27.255.255
netname:        BSKYB-BROADBAND
descr:          Sky UK Limited
country:        GB
mnt-by:         BSKYB-BROADBAND-MNT
admin-c:        BBH-RIPE
tech-c:         BBH-RIPE
status:         ASSIGNED PA
remarks:        Please send abuse notifications to abuse@sky.uk
created:        2011-11-29T11:44:51Z
last-modified:  2016-06-17T14:28:34Z
source:         RIPE # Filtered

role:           Sky UK Broadband Hostmaster
address:        Sky Network Services
address:        1 Brick Lane
address:        London
address:        E1 6PU
address:        UK
phone:          +44 20 7032 7000
fax-no:         +44 20 7900 7812
admin-c:        NIKO7-RIPE
tech-c:         MIVS1-RIPE
nic-hdl:        BBH-RIPE
abuse-mailbox:  abuse@sky.uk
mnt-by:         BSKYB-BROADBAND-MNT
created:        2006-07-07T09:21:33Z
last-modified:  2018-12-12T16:18:33Z
source:         RIPE # Filtered

% Information related to '176.24.0.0/14AS5607'

route:          176.24.0.0/14
descr:          Sky Broadband
origin:         AS5607
mnt-by:         BSKYB-BROADBAND-MNT
created:        2011-05-19T15:41:08Z
last-modified:  2015-08-17T16:30:12Z
source:         RIPE # Filtered

% This query was served by the RIPE Database Query Service version 1.94.1 (HEREFORD)

... Look like Wally's running his Website from a home connection !

**Comment by Undefined-Variables** [comment]
I have decided to leave it. But its clear I have some serious trust issues
which is totally not fair on you guys. So I have wiped everything and I
have installed CodeIgniter, and I am going to make an attempt at a solo
effort on my own.

So this is goodbye I will not be bothering you again, It has been emotional
and I have learned a lot from Ph-7's work so a big thank you to him. I know
I get carried away sometimes but I have been though so much over the last
10yrs and its left me with an instant distrust for people and where I used
to see the good all I see now is possible bad.

Thank you for putting up with me, I wish you all the best in the future.

**Comment by Undefined-Variables** [comment]
Its a business contract with static IP addresses. I am going to call them!

**Comment by Undefined-Variables** [comment]
I did say I don't fully understand js and I will be avoiding it from now on!

**Comment by polynamaude** [comment]
@Undefined-Variables When you don't understand something, you take it into consideration.
You take a break of modding the CMS...
You modify it.
You open and issue because you fucked-up.
You say that now other people hacked up.
Never went through your head that you may have caused it ?
If you would take the time to read and do the tricks other give you then you would have been able to go back and see what you modified, get back to the original code and see that it's what caused your troubles.

And just a little note...
You try to play smart and say things like "I know everything about Kali".
But you think that OpenVPN is hard to configure ?
Oh my god ! When was the last time you used your brain before writing something ? You must have a very sad life with not much interesting in it ! Is it why you try to look interesting here ? Hey ! You just total opposite !

You think that saying you know everything will make people want to be friend but when they see that you may know stuff but you also do the worst in life, forget what you don't know. It's one of the most important things, know our own limits. And this seem to be far from what you can do.

At least you stupid VPN thing made me laugh !

**Comment by Undefined-Variables** [comment]
Yeah, the thing is I only added a couple of lines of js and that was two weeks ago. All other edits were within the template I created and still had the same issue if I switched back to the base template, this was my first thought! 

Plus me making edits does not explain everything, like the list I told you about  (grammer and spell checker, Netcraft Extention, Pop up blocker for Chrome, Pop up blocker Pro, Safe Torrent Scanner) this didn't show up because I changed something. 

I was taking back up copies every 2 hours, so I could easily back track if I really fucked things up and I was talking to you before I went for the meal with my mum and dad, everything was working fine. I came back a few hours later and the server was screaming, cooling fan's loader that I've ever heard before.  

You lost me on the OpenVPN comment, I have never tried to use it or set it up. 

I never said I know everything about Kali either I said I know Kali pretty well as I have used it lots, I don't think you could ever know everything about anything. There is always something new to learn and life would be boring as hell if there was nothing new to discover! 

I have my limits just like everyone else but I think limits are there so you can push them and expand them. 

Life is what you make of it and  I'm not on some mad friend quest, I have friends and family but I am happiest in my own company, I find the needs of others a limiting factor and love the freedom of my life! I answer to nobody and do as I please, there is nothing wrong with that so don't make it sound like I have a shitty existence because I am happy and that is the most important thing! 

The things I don't know are the things that gets me out of bed in the morning, never stop learning!

I'm glad I made you laugh, you have made me laugh occasionally too.

**Comment by Undefined-Variables** [comment]
I really can't work you out @polynamaude one minute I am sure you are one person then I read something you write and notice grammar mistakes like PH makes but other times you are spot on. 

My conclusion is split between...

Ph7 === poly || Ph7 && poly = partners and share account || poly had some wine... 

I do like a good mystery...
