### ISSUE TITLE
Some words in english

### ISSUE THREAD

**Issue by aquaskualos** [pH7Software/pH7-Social-Dating-CMS#616]
I download and install languages for spanigh language, but some wods stil are in english... like "your first name" in home page.. etc... 
And in admin zone have a lot sentences in english...

Can you helpme with this?

Thanks.

**Comment by pH-7** [comment]
Hey @aquaskualos 

Thanks for your feedback. The Spanish translation is a bit outdated. It has been translated a while ago, and over the time, some key strings changed in the software.

SInce Spanish is not my native language, I can't keep this translation up-to-date.

You can update [global.po](https://github.com/pH7Software/pH7-Internationalization/blob/master/_protected/app/langs/es_ES/LC_MESSAGES/global.po) with POEdit for instance.

Have a look here https://ph7cms.com/doc/en/how-to-translate-to-another-language to know how to do so.

Hope it helps.

**Comment by pH-7** [comment]
Hope it helps you to understand better your issue @aquaskualos 

BTW, if you appreciate the software and the hard work there, it would be very nice of you to review the software at https://sourceforge.net/projects/ph7socialdating/ (just take one minute to create an account add log a review in there).
