### ISSUE TITLE
Preference Fields

### ISSUE THREAD

**Issue by aquaskualos** [pH7Software/pH7-Social-Dating-CMS#617]
How can you add preferences in fields, such as a checkbox?
Would it be useful to, for example, add if you like to walk? if you like dancing? .. etc.
Thank you!

**Comment by polynamaude** [comment]
@aquaskualos You will have to code such function yourself.
Sorry to blow the bubble but there's no such thing as an Out-Of-the-Box do-it-all solution for any type of Website. And even if it would exist, such product would become rapidly useless because every website would have the same look.

Your idea is very good and it's with such modification that you will be different from other dating / social site.

**Comment by aquaskualos** [comment]
It's okay. The script is fantastic. A great job.
This was an idea to make searches on the site more accurate.
Do not worry thanks. Maybe you want to implement it in some update.
Best regards!!

**Comment by polynamaude** [comment]
@aquaskualos You can implement it yourself by forking the repository. If you make a "Pull Request" afterward, we'll include it in the next release.

**Comment by pH-7** [comment]
> How can you add preferences in fields, such as a checkbox?
> Would it be useful to, for example, add if you like to walk? if you like dancing? .. etc.
> Thank you!

Thanks very much for this suggestion @aquaskualos! I will keep it in mind! 😄

**Comment by pH-7** [comment]
> It's okay. The script is fantastic. A great job.
> This was an idea to make searches on the site more accurate.
> Do not worry thanks. Maybe you want to implement it in some update.
> Best regards!!


Really, really happy to hear this! These kind words always motivate me a lot!
