### ISSUE TITLE
Cookie not set when using chrome

### ISSUE THREAD

**Issue by The-Dragon-Queen** [pH7Software/pH7-Social-Dating-CMS#623]
The site does not work when you use Chrome via a IP address as mentioned in this post 

https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/498#issue-429420796 

However, I don't see a solution to this problem? Is there a way to get Chrome to set a cookie while using an IP address while developing?

**Comment by polynamaude** [comment]
@The-Dragon-Queen If you make a little research on what's a cookie (IETF RFCs) then you will notice that this limitation is not related to this site but the way secured cookies are set.
You will have to modify the headers responded and the configuration set on the cookies.
You can also set a fake domain name by modifying your local **_hosts_** file.

In all case this does not sound very serious to me as the price of domains are about the same price as a coffee.

You should ask your friend Underfined_Variables, you both seem to have the same hours of work !  And he certainly know much more than I do.

**Comment by polynamaude** [comment]
@The-Dragon-Queen On a last note, don't start to open issues that got closed. There's a reason if they haven't gone further. It's not because you don't understand why that it's worthwhile trying to push for changes or explanation.

The more time we waste with useless work, the less time we have to really help users or develop the software.

We are all volunteer here.

Not because we are behind keyboard that it means that the normal manners of life don't apply.
Again, that's not for me if I say this, in the end, you are the person that will just get ignored because when we'll see questions our reflex will be not even look at it and say to ourselves "Again, same questions already answered and even can't say thanks for what we already did". Don't tell me you didn't see the answer I gave you yesterday.

**Comment by The-Dragon-Queen** [comment]
Thank you for the advice about the headers and setting a host name. 

I do know the user who goes by @Undefined-Variables from another site, he is a very well and respected member of that community and funny enough that is how I came across this software, he asked me to set up an account and ask a question on his behalf, he said he was being picked on by a member of the support team here. I thought this was he was over thinking things but then last night I asked a reasonable question and was meet with a sarcastic reply. I'm guessing he was talking about you?

I agree he properly knows more that you but he is off grid after his mum was rushed to hospital and is in a very bad way, so I doubt he will be about anytime soon.

It almost sounds like you don't want to be here answering these questions and like you say you volunteer so if you do not enjoy being part of the support team on this project why are you here? Do you enjoy talking down to people? I don't see why you are here, you have added very little to this project and you are so rude in the way you talk to other people. 

I have not seen any answer from yesterday no! I have just logged on and sent you the trace via my email account I will look now on Github.

**Comment by The-Dragon-Queen** [comment]
Oh and the Cat Finder is a little private joke between me and Undefined-Variables it goes back to when I first meet him. Its not supposed to be serious.

**Comment by The-Dragon-Queen** [comment]
Here are some links you might benefit from

https://www.psychologytoday.com/gb/blog/fulfillment-any-age/201711/the-best-way-counteract-rude-behavior
https://www.apa.org/topics/anger/control
https://www.elitetraining.co.uk/interpersonal-skills-training-course
https://www.wikihow.com/Be-Respectful
