### ISSUE TITLE
Chat Modules - Switch to HTML5, jQuery? e.g.,Paper Chat

### ISSUE THREAD

**Issue by Scobiform** [pH7Software/pH7-Social-Dating-CMS#63]
As the title says... Flash is a bit annoying and not so secure. 

https://github.com/pubnub/paper-chat

BTW the Demo Page is down. Internal Error...

Good Luck

**Comment by pH-7** [comment]
Thanks a lot @Scobiform I'll check if we can integrate it by default.

P.S. By waiting, you can already integrate it into pH7CMS with iframe instead of the other chat. To do it, please install it on your server, then go to pH7CMS Admin Panel (generally your-site.com/admin123/) -> Settings -> Api -> Chat URL and enter the URL of your chat where you installed it on your server.

**Comment by pH-7** [comment]
@Scobiform If you know other HTML chats that might suit, please just let me know :smile:

**Comment by pH-7** [comment]
Also, maybe/otherwise propose a SaaS like the current one (ref: http://addons.hizup.com/chat/?name=%site_name%&url=%site_url%&skin=) and replace it by this one much better and fully in English (not French like the current one) 

-> https://github.com/owncloud/chat

**Comment by pH-7** [comment]
Well, currently there is no plan. Lack of time. Please feel free to contribute and add this amazing feature and you feel into a good mood! :smile_cat:

**Comment by pH-7** [comment]
IM has been fixed and many improvements has already ben done in pH7CMS 1.4

**Comment by pH-7** [comment]
Well, currently there is no plan for the Chat module. Lack of time. Please feel free to contribute and add this amazing feature and you feel into a good mood! :smile_cat:
