### ISSUE TITLE
Anyone here?

### ISSUE THREAD

**Issue by aquaskualos** [pH7Software/pH7-Social-Dating-CMS#633]
The script is nice and functional (but in English), however I am making inquiries about the translations and I do not get an answer, I have not got an answer about the integration of Facebook (well, I did not get a satisfactory answer).
If there is support I will continue trying, if you cannot even translate the texts of the main page or the register, unfortunately, I will have to set it aside.

**Comment by polynamaude** [comment]
@aquaskualos Sorry I am currently busy hiring someone who has all the knowledge for your own special needs and only the good words for your. Concerning the ability to change text on the homepage, yes it's possible do some search with the tool **fgrep** inside the repository and you will find your _strings_.

You don't seem to understand that we are volunteers and have no obligation whatsoever to help. If we do so, it's because we want to. And when we do take time to give a hand, for sure it's for someone who didn't do much more than benefit from the works of others give out complains.

It's not by opening issues with some non meaningful title that you're going to make it interesting for others to help you out. As I can see that the only thing you ever did on gitHub was to open one issue here then maybe you should look at other places how it works. There's what we call community rules and your didn't seem to appreciate that we reminds you of them.

In that case, you can continue to wait and see if someone else answer your complains. No one force you for nothing.

**Comment by polynamaude** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/Is-there-anything-(addon..)-to-turn-the-frontend-to-French%3F

**Comment by aquaskualos** [comment]
Yes, I know Github, and I know that it is a voluntary community without any obligation to have to answer any questions. And I appreciate the work that is done, of course, and to the extent that I can try to help myself, even if it is a minimal help. But when I ask something it is because I have tried to find the solution in all possible ways that are within my reach. About the integration of Facebook, I think everything is fine, it doesn't matter. But about the translations I am completely lost, I have looked in the database, in the .po and .mo files, and have used examine64 to find the text strings.
Don't get me wrong, I don't "demand" help, I just ask.
I think what happens to me should happen to more users, and that doubts are ways to improve the script.
We will wait ... Best regards.

**Comment by polynamaude** [comment]
Some string maybe be static so you will need to edit the files by themselves. This is why I told you to use **fgrep** and search through the repository.

Another user had the same problem than you but he was using Portuguese. Look in the history of issues

**Comment by aquaskualos** [comment]
ok. thx

**Comment by pH-7** [comment]
> The script is nice and functional (but in English), however I am making inquiries about the translations and I do not get an answer

Did you send a Pull Request or a Zip file with the translation as requested? https://github.com/pH7Software/pH7-Internationalization

Thanks for your message! :)

**Comment by aquaskualos** [comment]
No, do not request an extraction.
There are simply texts that are not in the .po or .mo files, nor do they appear in the databases, so I understand that they are phrases or words that are not subject to a variable, but are static phrases or words.
The idea of changing the phrases or words in the archives is a possibility, however they would also change in the other languages ... I guess ...
I will try to convert those phrases into variables and when this is done again, in case it serves someone else. However, I only have notions of how to do it with php. I will try anyway.
Thank you

**Comment by aquaskualos** [comment]
ok.  Bye
