### ISSUE TITLE
Unos cuantos

### ISSUE THREAD

**Issue by aquaskualos** [pH7Software/pH7-Social-Dating-CMS#643]
Great. There has not been a single doubt I have raised. It doesn't matter if it's because of my ignorance or because of script failures. I have been polite and patient. The script has a good image at the beginning, but it lacks no response. Abandoning this project, it doesn't work for me.

**Comment by polynamaude** [comment]
@aquaskualos I did look back at the many issues you did open. All of them got answered. If you want custom development you'll need to ask a developer. Maybe you shall read the license that pH7CMS is released under. We offer you  hours of work for free and you complain that we don't answer your questions the way you'd like.

**Comment by aquaskualos** [comment]
Do I really have to endure this?
What issues have been answered? .. ask about the translations that are not in the .po .mo files, without solution, ask about the url that you should put in facebook developers to authorize the access, without solution. Something as simple as indicating the url, ask something else that I will not bother to check, fancaly.
I have not requested dedicated support at any time. I understand that it is an open source script and there is no obligation even to answer, but my queries were very generic and concrete. I do not understand why this answer, in my opinion offensive.
Close this topic, just as you have closed all the others that I have opened, because this one will not have a solution either, from what I see, you will never accept that my queries have not been treated properly. Some elegance is missing in the deal, really.

**Comment by Undefined-Variables** [comment]
I don't understand what issue you are experiencing. There is no description of your problem and this issue is completely pointless. The people who are trying to help you do this for absolutely nothing, there is a ton of work here in this project and it free. 

When I first came across this software I had a ton of problems and thought it was down to the software but the truth of the matter was it was down to me and my setup. I thought I understood things that I didn't and I came here asking for solutions constantly. Taking this approach didn't help. The real help can be found in books and documentation about the aspects I didn't understand and once you understand how the different parts work on there own everything starts making sense. 

This software is not for inexperienced users, it uses a range of languages that can easily course problems for each other ,if you don't fully understand something get a book or Google it constantly until you master it.  Nothing is achieved overnight and it takes time and patience. I truly believe anybody can learn anything if you put enough time in to it. 

Please explain the problem you are having and I will try and help you. I spent about 4 months learning Ph7cms and have created a few templates for it that I ended up giving away. I have to fully understand everything and the only way you will ever truly get there is by doing it yourself. I have since learned CodeIgniter and am also doing night classes at a university studying JavaScript. 

So what is the issue???

**Comment by aquaskualos** [comment]
No importa ya.
Variables, si. Palabras asociadas a una variable para que se pueda mostrar en varios idiomas.
Pero da lo mismo. Estáis empleando más tiempo en publicar excusas que el que empleadores contestando dudas. 
Olvídalo ya.

**Comment by Undefined-Variables** [comment]
I No hay problema, respondí porque vi que nadie más te había respondido. He sido así antes, así que sé lo que es sentirse frustrado.

adiós

**Comment by aquaskualos** [comment]
> I No hay problema, respondí porque vi que nadie más te había respondido. He sido así antes, así que sé lo que es sentirse frustrado.
> 
> adiós

Many Thanks
