### ISSUE TITLE
ads.txt 

### ISSUE THREAD

**Issue by D4rkkking** [pH7Software/pH7-Social-Dating-CMS#645]
ads.txt is not act

https://eksiup.com/p/rx198851s4ju

**Comment by pH-7** [comment]
Hi @D4rkkking 
You got a 404 error because the current .htaccess bans the non-allowed txt files (and ads.txt wasn't allowed).
In order to avoid this kind of problem with txt files, I would suggest you to remove the `|txt` at the end. https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/.htaccess#L46

Sorry for any inconveniences about it :)
