### ISSUE TITLE
Same Message Sending Error

### ISSUE THREAD

**Issue by abuaslad** [pH7Software/pH7-Social-Dating-CMS#653]
Hi,

When we try to reply our friend with any message it shows following error:

_The following error was found:
Oops! It seems that you have already sent the same message to prevent spam you can not send multiple same content._

According to my suggestion:
Any message with same repeated content should not show error....
because we send same message everyday to same friend and other friend as well.

For example: we want to send everyday only **Hi** massage to our friends in the morning.

Kindly resolve this Issue:
![reply-message-error](https://user-images.githubusercontent.com/53337420/67065628-ace64b80-f18c-11e9-8a03-689e3e6af1e8.jpg)

**Comment by pH-7** [comment]
Most people with dating websites, just copy/paste messages to a bunch of profiles.
In order to prevent this kind of spam and keep the quality of your service high, the software doesn't allow duplicate messages from the same user.

However, you can manually disable this prevention.

1. Open your `_protected/app/system/modules/mail/forms/processing/MailFormProcess.php` file.
2. Remove the highlighted condition I mentioned
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/68ad351919352bd7b4bda08e12f2754f50d19d60/_protected/app/system/modules/mail/forms/processing/MailFormProcess.php#L50-L51


At the moment, it isn't possible to disable this anti-spam feature right in the admin panel, but I will do my best to add this setting in the Setting admin dashboard :)


Hope it helps!

**Comment by abuaslad** [comment]
Removed following code:
elseif (!$bIsAdmin && $oMailModel->isDuplicateContent($iSenderId, $sMessage)) {
            \PFBC\Form::setError('form_compose_mail', Form::duplicateContentMsg());
        }

Now I am not getting above given error so far......
Let me test more......
Thanks for prompt reply and support!!!
