### ISSUE TITLE
Danish Language install problems 

### ISSUE THREAD

**Issue by Decoydk** [pH7Software/pH7-Social-Dating-CMS#683]
**Describe the bug**
I have translated the hole site to Danish. But When I try to use it is still english nothing on danish

**To Reproduce**
1. Go to 'Setting'
2. Click on 'General'
3. Scroll down to 'Default Language'

I have added the danish translated files Maybe someone can make me a guide...
I have did try to use the one there is linked to in the admin area but maybe I do something wrong.

![lang](https://user-images.githubusercontent.com/58641293/70381050-4f78aa80-1944-11ea-950a-9adf6c52db6e.JPG)

**Comment by pH-7** [comment]
Hi @Decoydk! Congratulations! 
What you mentioned looks right. 
Can you try to specify the `?l=da_DK` in the URL, just after your domain name, like `www.mywebsite.com/?l=da_DK`?

If the problem still persists, something must be wrong in the translation files. You can always send them to hello@ph7cms.com and I will try to reproduce it on my local host and see what's wrong in there.

Good luck!

**Comment by loryel** [comment]
hi

check this out

https://github.com/pH7Software/pH7-Internationalization#troubleshooting

https://github.com/pH7Software/pH7CMS-Test-Gettext-Lang#how-to-install-the-missing-locale-language-on-my-server

**Comment by Decoydk** [comment]
Thank you is works now... the only problem now is the site dont allow dansih letters in the fields (Æ Ø Å)
how and where to fix that.. The translated files is okay with the letter dont dont the script
![danish letters](https://user-images.githubusercontent.com/58641293/70386983-b6777d00-199f-11ea-97c6-6d9cc073a36f.JPG)

**Comment by pH-7** [comment]
> Thank you @pH-7 is works now... the only problem now is the site dont allow dansih letters in the fields (Æ Ø Å)
> how and where to fix that.. The translated files is okay with the letters but in the script only A-Z letters
> ![danish letters](https://user-images.githubusercontent.com/58641293/70386983-b6777d00-199f-11ea-97c6-6d9cc073a36f.JPG)

The language key must only contain alphanumeric characters. Then, you will need to add the language key in /_protected/app/langs/da_DK/language.php file where you will be able to add special characters as the value such as "Æ Ø Å".


I hope it helps Decoydk!

Happy Sunday in Danmark! 🇩🇰

**Comment by Decoydk** [comment]
@pH-7  
Thank you and happy sunday to you to.....
I have the laguage.php file but I'am lost where and hot to but in the characters can you help me with that ?

[language.zip](https://github.com/pH7Software/pH7-Social-Dating-CMS/files/3936585/language.zip)

**Comment by pH-7** [comment]
No worries @Decoydk 

Just add it at the end of the file. Please see your file again attached. I've updated it at the end of it, with your custom word 'Højde" and named the language key "hojde". Then, updated the language.php file and use "hojde" as the language key.


[modified-language.php.zip](https://github.com/pH7Software/pH7-Social-Dating-CMS/files/3937264/modified-language.php.zip)

**Comment by pH-7** [comment]
Please let me know how it goes @Decoydk 🤞

**Comment by Decoydk** [comment]
@pH-7  is works for the word Højde but not for all works with Æ Ø Å ...
is there a way around that so it works.... BTW I will offcause share the translated file so others can get to use also

**Comment by Decoydk** [comment]
@pH-7 I have tried some things but still no luck with get from A-Å (Æ Ø Å) letter to work

**Comment by Decoydk** [comment]
@pH-7  I really dont get it why it does not work ?? I have to do something wrong or I'am missing something... 
Just to be sure I did a test install of wordpress in a subdomain and there was no problems with that so it is not the server. But somewhere in the pH7 software script... but I'am blank on where

**Comment by polynamaude** [comment]
@Decoydk Not because you can install WordPress that it means that the problem ain't on the server side. It's not because it doesn't work out of the box on your installation that it's faulty.
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

**Comment by Decoydk** [comment]
> @Decoydk Not because you can install WordPress that it means that the problem ain't on the server side. It's not because it doesn't work out of the box on your installation that it's faulty.
> https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

Thank you @polynamaude  , it is installed with the cpanel on my server.
The hole site is on danish like I did translate the problem is in admin area user field if I change them to danish it will not allow that.
I have made a search on that problem and did not find anything on the matter

**Comment by polynamaude** [comment]
@Decoydk I have big doubt that you took a minute to read what I gave you here as a link.

Start by installing the CMS yourself, not with cPanel Softaculous or anything else that does automatic installation. At least it will give you a inside look of how the procedure is done.

Afterward, do as PH wrote earlier to add both the **.PO** file and the modified **language.php** file.

**Comment by Decoydk** [comment]
@polynamaude  okay I will try to install it by my self... and then try again to add the .PO files like I did this time.
But dont say I did NOT look and that link. Do you think that the link you did send was the first time I did see that ?.. then you are wrong.
I have tried by my self before asking for help. I will not reject that it could be the install but I have my doubt on that either way I will make a clean install.
I'am 90% sure that the problem will still be there. On the photos I have added in posts you can see the it will only allow A-Z letter so THAT is was have to change so Æ Ø Å also is allowed. I dont see how a new install will correct that,

**Comment by polynamaude** [comment]
@Decoydk If you actually did read the link then either I'm blind or someone's a fool because there's not much answer to the questions asked in the document.

Also, as you know, the support for some UTF8 is only available in the latest versions.
Because you seem to know the ending  (no use to doing an installation yourself instead of using a automatic installer) to this story than I doubt there's no use for me to continue trying to help you out.

PH already explained to you what to do. He already did it for one word, you'll have to do it for the rest.

https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/683#issuecomment-562956609

Yes translating can be boring and time-consuming.

PS: By installing it yourself you show others that you have at least some very basic knowledge. It's one thing to install a CMS or any other web application. Now to run a service with active users, that something totally different.

**Comment by polynamaude** [comment]
@Decoydk Call the w3c consortium and ask them why does danish letters aren't considered alphanumeric letters and you'll get your answer. Possibly a solution the day all the web browser are updated to your new "Decoydk" standard...

When you put a limit on the input to choose "Alphanumerics" then the browser will indeed limit yourself to those particular characters.

https://www.w3schools.com/tags/att_input_type_text.asp

**Comment by Decoydk** [comment]
Yes @pH-7 did show me and he did added a word for me and as you can see it did not work then it would have been easy.

But sorry not everyone is a brain like you on this. There is a reson that I asked for help and not looked down on. If that is that is your only mission in my post please dont comment anymore.
Ia'm glad that you did try, but if you dont belive what I write to you I will rather you dont help any more

**Comment by Decoydk** [comment]
@polynamaude I try to learn this and CMS is brand new to me... wordpress I have worked with and manage that okay, not perfect like hardcore programming. So I do alot of read up on this and dont understand why I cant get the danish letters on this script like I can on other scripts.
That is what I want to know

**Comment by polynamaude** [comment]
@Decoydk Don't start to go on with the idea that if one thing work for one CMS then it should work for a different CMS.

Every system has it's own way of dealing with problem (in this case UTF8 and multilingual). There's no uniform way of doing things.
You have to remember that most application were developed at a time that the only encoding was ASCII (7bit). For sure it evolved since then and we now have a standard called UTF8.

But even with UTF8 there's many implications involved. We can't simply store everything that the user supplies without risking a stored attack (same as executing JavaScript).

Yes there's risk with UTF8. You can look at OWASP for this.

Sincerely,

**Comment by OttoKoester** [comment]
> @Decoydk Don't start to go on with the idea that if one thing work for one CMS then it should work for a different CMS.
> 
> Every system has it's own way of dealing with problem (in this case UTF8 and multilingual). There's no uniform way of doing things.
> You have to remember that most application were developed at a time that the only encoding was ASCII (7bit). For sure it evolved since then and we now have a standard called UTF8.
> 
> But even with UTF8 there's many implications involved. We can't simply store everything that the user supplies without risking a stored attack (same as executing JavaScript).
> 
> Yes there's risk with UTF8. You can look at OWASP for this.
> 
> Sincerely,

There is a big problem about this, because we can not use a translation service, it 's not querying the results as should be. It looks that the DB and the Main System is working very well with the characters but this problem is when we need to use city locations, that we need to search and parse information of the locales file. ( ex: "../dating/germany/hannoversch-mã%C2%BCnden", it should result as address "../dating/deutschland/hannoversch-muenden" and also the name of the title tag for cities is printing this problem, for other fields like name, name of website, thespeical characters is working perfectly)
