### ISSUE TITLE
Captcha not working sometimes

### ISSUE THREAD

**Issue by zeze6** [pH7Software/pH7-Social-Dating-CMS#704]
greetings everyone
i have this issues where Captcha work sometimes and sometimes not, it says captcha check faild while it's correct, plus sometimes i can't sign in as admin or as normal user, i use Ubuntu and windows 10, both firefox and chrome on Ubuntu doesn't work anymore, it was working fine but don't know what cause this, on windows 10 it does work most of the time,
note: i'm not newbie! if the script was working without issues i won't be here ask many questions.

**Comment by crolidge** [comment]
I also had trouble to login as Admin a few times. Captcha not working. I always thought it was due to me having multiple Admin sessions (simultaneously) while testing my site in multiple devices. I believe I found I couldn't log as Admin twice. Only once. That's my perception. Not due to a software perception. Anyway I would like to hear some views on the matter 🙂

**Comment by Undefined-Variables** [comment]
How can something not work sometimes? You have to give us more to work with than this... Sharing your log is generally a good initial step!
