### ISSUE TITLE
Suggesting regarding wording

### ISSUE THREAD

**Issue by digiloo** [pH7Software/pH7-Social-Dating-CMS#722]
Hi, I'm currently browsing the the 2522 (sic!) messages for possible translation.  And
I see many different words for the same thing (from a website user perspective) 

Some examples: 
```
Account, membership, member, profile, user, membership account, ..
Avatar, profile photo, ..
Register, Sign up, ..

```
I think this can be a bit confusing and I suggest that this ought to be cleaned up  in a later version of the software.

**Comment by polynamaude** [comment]
@digiloo Could you please explain a bit more what you are making as suggestion here ?
What 2522 messages are you browsing ? Are you talking about the PO files for other language ?

**Comment by digiloo** [comment]
This is words that the users of the dating site encounter, and yes I'm looking in the default po file.

**Comment by polynamaude** [comment]
@digiloo Either write in a way people understand clearly what you want to say.
So you are talking about the English language file ? Could you please explain what is the problem ? What are you referencing to ?

Yes there is many sentence that look similar but that aren't the same. When you work with many language you have the problem of proper sense and not only a word based translation. That's why you get so many different sentence that seem alike but if you look at the French or Spanish translation then it is where it will show different.

For example you may use the same word to say 4 things, all different. That's in English.
In French those will be 4 different word.

I don't know what you are trying to show here but maybe you should explain more or at least give a example.

**Comment by Undefined-Variables** [comment]
@polynamaude We have discussed this before. You are so right with translating while maintaining proper sense. 

Some languages are stupidly simple and then there is English...
