### ISSUE TITLE
Google Maps not working & email config info not found

### ISSUE THREAD

**Issue by ultra-pool** [pH7Software/pH7-Social-Dating-CMS#728]
Iv added the api key for google maps. The maps still do not show. 

Where is the info to add the email config to be able to send emails of newsletters and new users? Only thing Iv seen so far is adding the email addresses and nothing regarding setup for the site to send any emails.

**Comment by Undefined-Variables** [comment]
When you installed you entered admin, no reply, feedback and bug email addresses. These are stored in database. The software sends mail using a third party library called "swiftmailer" you don't need to do anything. Outgoing email is delivered using the email address you entered in the no reply field upon installation. 

The maps work perfectly so your problem is on googles side again. Have you set the API settings correctly there? 

This is the last issue you will get a response from me for!

**Comment by ultra-pool** [comment]
It gives a mail error. which this does even send any emails at all.

**Comment by ultra-pool** [comment]
The following error was found:

    Oops! Our email server encountered an internal error. The email could not be sent. Please try again later
