### ISSUE TITLE
Footer links

### ISSUE THREAD

**Issue by ultra-pool** [pH7Software/pH7-Social-Dating-CMS#731]
Noticed the footer links is forwarding to IP address and not using domain name

Exp = Https//x.x.x.x/help and not https://domain.com/help

Havent found any where to repair this bug. Any ideas where to look?

**Comment by Undefined-Variables** [comment]
Where is the site hosted? On a hosting providers server or a local sever you physically own yourself?

There is an underlying issue with your server configuration, we only support the software here, your server and its config is your own responsibility.

**Comment by ultra-pool** [comment]
Its a hosted server. I ran a test with one of my others sites and it doesn't do this. Only this code does it.

**Comment by Undefined-Variables** [comment]
You are not the first person to have reported this and every time the issue is their server configuration. 

Do you even try looking at closed issues to find out if your problem has been solved before? We offer support for bugs that are new and unheard of before, we are not your first port of call every time, we do this for free and repeating history is not something we do. 

This is called documentation:  [https://ph7cms.com/doc/ ](url)

This is called past issues: [https://github.com/pH7Software/pH7-Social-Dating-CMS/issues?q=is%3Aissue+is%3Aclosed](url)

You have opened 6 issues in last few days, I have no more time for this.

**Comment by Undefined-Variables** [comment]
Adding this to your .htaccess will HIDE your issue NOT solve it...

````
RewriteCond %{HTTP_HOST} ^1.1.1.1$
RewriteRule ^(.*)$ https://example-for-dummies.com/$1 [R=301,L]

````

Odiously you need to use your real URL and IP address not 1.1.1.1 and example URL.

**Comment by ultra-pool** [comment]
I post as I run into them since Iv never ran into problems like this with my stuff. Also this github is full of stuff and trying to search all the issues on github has been a waste of time so far. basically having to read every one of them and still not finding the fix for the problem. And the main dev should be really answering problems atleast some. lol

**Comment by ultra-pool** [comment]
With my web projects I use a .env for the main back bone config. which saves a lot of time and headaches searching each file in the source trying to find a noodle in a hay stack. But each dev has his/hers ways of doing things so this is a learning curve with this source.

**Comment by polynamaude** [comment]
> I post as I run into them since Iv never ran into problems like this with my stuff. Also this github is full of stuff and trying to search all the issues on github has been a waste of time so far. basically having to read every one of them and still not finding the fix for the problem. And the main dev should be really answering problems atleast some. lol

@ultra-pool 
Hey "Dude !"....
**1st thing...** You don't pay a dime for what you get so if you ain't too happy, you can look around and this is it. No one forced you here, no one made you any promise. If you're as good you think then as I already told you, yes we still have bugs laying around because we don't have a big test pool of user.
**2nd thing** If you don't like to search into thread of information then just to note, it would be lot easier if people would follow some smart move like explaining their hardware and how we can reproduce the problem they got. In that case, at least we'd waste less time trying to figure out where it come from.
**3rd thing** If it's the first time you run into issue in your life, then maybe you need to learn a bit more. It's not because you own a pool for mining that it gives you knowledge out of the box. Also, it's not because you've been running a system than you know how to do it properly. Also, searching through documents is part of your job. If you don't like it then become a janitor or any other thing that's easier for you.
**4th thing** I think you're missing a thing about community support. We're all volunteer and we do this on our free time. So it's damn pretty insulting when you say that we shall be doing thing and you expect them like a _due_.
**5th thing** If people would open less non-related issue, then it would at least be easier to search
**6th** Go pay hundred buck a month at [Una](https://www.una.io/) and you'll get assured support.
**7th thing** If you didn't know that the Google Analytics code came from Google or how to do basic troubleshooting for email then you don't have knowledge to operate a website. Sorry but it's not only about when it goes good, it's mostly about what to do when it goes wrong. Everyone is pretty good when there's not a problem around. Even my handicap grand-mother can drive a caterpillar on a straight empty road with the sun shining. Thing about this my friend ! (_that's a figure of speech_)

If we wouldn't be wasting our time with stupidity then maybe we'd have more time to really answer people...

**Comment by Undefined-Variables** [comment]
@ultra-pool You need to take a course and then you might learn something about how a computer actually works, just the way you ask a question demonstrates how limited your knowledge base and level of understanding really are. You seem to think you should be supported by us on every little thing that you can't be bothered to research for your self, my time is valuable and nobody pays me for being here. I'm here of my own free will because I believe in open source software so give some of my time to it where I am able to. Anybody can bounce around Github downloading software they have no understanding how it works. You are what id classify as a "Script Kiddy". All take no give.

Don't waste your time opening another issue, you managed to insult all the people who provide support regularly here in a single comment, i'd be shocked if you got another response...
 
@polynamaude clearly we not good enough for this person, we are not the "Main Dev", I have never been so insulted, the main dev has better things to do than teaching beginners to use a computer. His time is valuable just like us non main dev's .

**Comment by ultra-pool** [comment]
> You need to take a course and then you might learn something about how a computer actually works, just the way you ask a question demonstrates how limited your knowledge base and level of understanding really are. You seem to think you should be supported by us on every little thing that you can't be bothered to research for your self, my time is valuable and nobody pays me for being here. I'm here of my own free will because I believe in open source software so give some of my time to it where I am able to. Anybody can bounce around Github downloading software they have no understanding of how it works. You are what id classify as a "Script Kiddy". All take no give.

If you say so. Being a a$$ hole and talking sh$t to me wont get you anywhere.

Thank you for the help though. Have fun being a keyboard warrior. And best of luck
