### ISSUE TITLE
How to change example.com/meet-people to example.com/my-text

### ISSUE THREAD

**Issue by MKDan** [pH7Software/pH7-Social-Dating-CMS#744]
How to change example.com/meet-people to example.com/my-seo-text

And how to change the "Title" and "H1" tag of the "Browse Members" to "My SEO Text"

I'm during this for the page to rank for the "My SEO Text"

**Comment by polynamaude** [comment]
@MKDan Hi !
Sorry but I doubt it's the good place for your question.
This is mainly a developer forum for issues relating to the pH7CMS. We don't have the time, energy and resources to start giving a hand will all sort of problem related to general web development. Yes we're nice enough to answer some question that goes a bit over the line but we do so on a occasional basis, when it's already in line with a open topic.
You'll find much help on website like W3C and other.

All the display files are in the template folder. You can search inside the folder itself using **fgrep** on your terminal screen. So simply search a piece of text and you'll see where it is. Maybe it's a string translated and you'll get it in the locales. I'm pretty sure it is !

You can use a software like POEdit to update your locale.

Also, it's already a bit hazardous trying to find answer in all the issues, we try to limit unrelated ones so the number stays down.

Here some links
[pH7CMS Doc](https://www.ph7cms.com/doc/)
[pH7CMS Wiki](https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki)
[Change promo texts](https://ph7cms.com/doc/en/how-to-change-promo-texts-on-homepage)
[Translate](https://ph7cms.com/doc/en/how-to-translate-to-another-language)

**Comment by Undefined-Variables** [comment]
I agree I just spent half hour answering one question in detail for you, maybe you need to hire a developer if you wish to make so many changes.

**Comment by polynamaude** [comment]
@Undefined-Variables The problem is not with the desire to make changes. I don't mind to do orientation but when what's needed is teaching development that's another story....
Like you need to either have some basic knowledge or at least say "I've tried this, that and that" so that people see you've did part of the work.

I think many person land here thinking "Gonna build the next Badoo and be rich !" but forget that if it would be so easy then other people had think about it before them, and they'd be rich too...
They think that because they have some knowledge (we all know more than someone in something) they'll just run a site... 

It's the problem that come over and over when you talk about dating site.

**Comment by Undefined-Variables** [comment]
@polynamaude yeah you are right most people see this as a easy ticket to a dating site but most don't want to put any effort in to learning the way it works they just want it to work magically...

Personally I couldn't care less about being rich, that is the wrong reason to start any website, I am here for my love of developing and I enjoy seeing the final result more than anything, money is the root of all evil.

**Comment by MKDan** [comment]
I'm sorry if I have offended you.

I guess I can find the source file in PHPMyAdmin and just edit the text. Not sure, how to change the URL though. I will give a try and tell you.

But I just don't know, will it be ok with the next updates of ph7cms.
Also, there is no community forum for ph7cms.

**Comment by Undefined-Variables** [comment]
You haven't offended anyone, we are simply trying to explain the things you want to change are a lot of work and we don't have the free time to talk people though every thing they wish to change, the software is a full complete working package and any customization is down to the person who wants to see these changes. We don't mind offering advice on one issue on a change that has been attempted but failed but the issues opened are asking for step by step help and no body here has that amount of free time.

**Comment by polynamaude** [comment]
@MKDan Yes, you are right, there's no community forum. I'll repeat myself (again), we don't have that much resources and many people, so we're limited. Don't compare this project with others and expect the same here...

I've seen you opened a account for the only reason of getting here. So I'll make my opinion that you ain't a developer.

Like I already wrote to you, the answer is in my message for what you are looking for. And yes, sometime thing won't always work. So learning is a try again game...

There's a pretty simple answer that you'll learn fast enough if you continue asking question when you've got the answer in your face or easy to find. It's called RTFM...

If you start asking question that you've got an easy answer then you'll just see than in the end people will stop helping you out because you'll have use everything they had to give. And when they see you question, they'll just say "Why ? I'll guide him a bit and he won't do his part". There's end user and there's people doing development or at least wanting to. And here ain't the best place to learn.

And I can say, to learn because I've never wrote nothing about using MySQL (or any Database) for translation...

**Comment by polynamaude** [comment]
@MKDan How can you find a source file in phpMyAdmin ?
Have you ever used a command line ? Sorry but I don't think you are at the right place...
Maybe [Una](https://una.io/) is better for you... Or some software that you can just "Click your way around".

There's also [HumHub](https://www.humhub.com/en)
But I don't know much about them...
Or even Elgg or TikiCMS....

**Comment by polynamaude** [comment]
@Undefined-Variables You laughing out loud ? Don't make too much noise...
And don't invite friend over... that's an offense in the kindom of the Queen as there's virus spreading around...

**Comment by Undefined-Variables** [comment]
Sorry @polynamaude you made me laugh with that last reply! I know right we are all on lock down and they just extended it another 3wks!

**Comment by Undefined-Variables** [comment]
@polynamaude are you on any kind of lock down?

**Comment by polynamaude** [comment]
@Undefined-Variables It's time to do programming as there's nothing else to do !
In Canada we're a very socialist country. They gave 2000/month for everyone because we're on lockdown and everything except emergency services or the public service is at rest.

**Comment by Undefined-Variables** [comment]
Yes its the same here, key workers like doctors, nurses, etc are only people allowed to travel, government are paying all wages (not sure how they can afford too), and everything is shut down. 

Our prime minister got the virus and only just made it. This is worrying times, they had no choice if they didn't shut down it would have spread faster than the NHS could help people! 

Definitely a time to program... Stay safe :)

**Comment by MKDan** [comment]
> @MKDan How can you find a source file in phpMyAdmin ?
Yeah, the source files are in the file manager and phpMyAdmin is for the database.

**Comment by polynamaude** [comment]
@Undefined-Variables Yeah, I've read that for Borris Johnson.
That's basic of economy... the governement can pay all the wages because they know that on long term things will settle down and that productivity is going to rise.
I compare this to welfare. If you just leave people going down to zero, they won't really be able to get back on track and be productive. But if as a society, we help the people in need then they can become productive again.

For example a mom who's got a 5 years old kid. If you let her starve with no income, then her kid is going to have big problem, get bad grade in school, etc. But if you give her some income, offer health service, etc then she's going to be able to take care of the kid. The child gona grow up and become a productive member of society, pay taxes, etc.

Same goes for the crime rate. When you travel to Africa you see that people don't have much choice other than to keep their car inside a garage and have big fence around their house. If not, they get attacked. And they can't let their kids walk to school.
And same goes for business.
But instead if you give a minimum income to the people in need then they don't have to steal to feed their kids and all this shit. And in the end, the little amount it cost to society with welfare is far less than what would be costing as a whole as lost productivity caused by criminality.

Same goes for what we are doing now by paying wages. Don't forget that governement don't have a bank account like yours. On the end, it's related to the value of the british pound that it will impact.

**Comment by polynamaude** [comment]
@MKDan What's the link between the "File Manager" and phpMyAdmin ?
Just like that, they both work in the browser is a wrong answer.

**Comment by Undefined-Variables** [comment]
Ideally you would use an IDE or even a basic text editor and not the in-browser tools in the admin panel.

**Comment by polynamaude** [comment]
> I guess I can find the source file in PHPMyAdmin and just edit the text. Not sure, how to change the URL though. I will give a try and tell you.

So you edit source file in phpMyAdmin...

**Comment by polynamaude** [comment]
@Undefined-Variables There's some in-browser IDE like Codiad or similar... there's even one by Amazon called ACE (Amazon Code Editor) but they ain't part of pH7CMS...

**Comment by Undefined-Variables** [comment]
> @Undefined-Variables Yeah, I've read that for Borris Johnson.
> That's basic of economy... the governement can pay all the wages because they know that on long term things will settle down and that productivity is going to rise.
> I compare this to welfare. If you just leave people going down to zero, they won't really be able to get back on track and be productive. But if as a society, we help the people in need then they can become productive again.
> 
> For example a mom who's got a 5 years old kid. If you let her starve with no income, then her kid is going to have big problem, get bad grade in school, etc. But if you give her some income, offer health service, etc then she's going to be able to take care of the kid. The child gona grow up and become a productive member of society, pay taxes, etc.
> 
> Same goes for the crime rate. When you travel to Africa you see that people don't have much choice other than to keep their car inside a garage and have big fence around their house. If not, they get attacked. And they can't let their kids walk to school.
> And same goes for business.
> But instead if you give a minimum income to the people in need then they don't have to steal to feed their kids and all this shit. And in the end, the little amount it cost to society with welfare is far less than what would be costing as a whole as lost productivity caused by criminality.
> 
> Same goes for what we are doing now by paying wages. Don't forget that governement don't have a bank account like yours. On the end, it's related to the value of the british pound that it will impact.

This is very true and I didn't think about it like that. That is the bigger picture, it takes a special kind of person to see things like this.

**Comment by Undefined-Variables** [comment]
> @Undefined-Variables There's some in-browser IDE like Codiad or similar... there's even one by Amazon called ACE (Amazon Code Editor) but they ain't part of pH7CMS...

Really? What happens when the browser crashes? Loose everything?

**Comment by polynamaude** [comment]
@Undefined-Variables Most people who are in the middle class work hard and didn't have time to learn the basic of economy. So they think that it's their salaries that pay for other people welfare but in fact it takes about 10 years of working and paying income tax to cover your birth and the school you did until your 20s....

> > @Undefined-Variables There's some in-browser IDE like Codiad or similar... there's even one by Amazon called ACE (Amazon Code Editor) but they ain't part of pH7CMS...
> 
> Really? What happens when the browser crashes? Loose everything?

Think a little mo

> > @Undefined-Variables There's some in-browser IDE like Codiad or similar... there's even one by Amazon called ACE (Amazon Code Editor) but they ain't part of pH7CMS...
> 
> Really? What happens when the browser crashes? Loose everything?

Think somewhat a little more...
Do you loose everything when your computer crash ? Why would it be different for a in-browser editor ? If you're stupid enough not to save then you loose other way you'll get it back !

**Comment by polynamaude** [comment]
@Undefined-Variables What other dating site builder have you tried out?

**Comment by Undefined-Variables** [comment]
> @Undefined-Variables
> 
> > > @Undefined-Variables There's some in-browser IDE like Codiad or similar... there's even one by Amazon called ACE (Amazon Code Editor) but they ain't part of pH7CMS...
> > 
> > 
> > Really? What happens when the browser crashes? Loose everything?
> 
> Think somewhat a little more...
> Do you loose everything when your computer crash ? Why would it be different for a in-browser editor ? If you're stupid enough not to save then you loose other way you'll get it back !

This was a joke :)

**Comment by Undefined-Variables** [comment]
> @Undefined-Variables What other dating site builder have you tried out?

Dolphin, Jcow and one years ago which I cant remember the name of now, I don't only have interests in dating software and have worked with a lot of eCommerce cms packages, forum software and video software too.

**Comment by Undefined-Variables** [comment]
Didn't think much of Dolphin. Seems early in development sages.

**Comment by MKDan** [comment]
> > I guess I can find the source file in PHPMyAdmin and just edit the text. Not sure, how to change the URL though. I will give a try and tell you.
> 
> So you edit source file in phpMyAdmin...

No, I don't. Its a typo.

**Comment by Undefined-Variables** [comment]
@MKDan Download Komodo IDE, PhpStorm or Virtual Studio Code...

**Comment by polynamaude** [comment]
@Undefined-Variables No Dolphin is a very mature product (more than this one) but some module are only available after paying a service fee. It now has become Una

I remember to have seen jCow somewhere...

**Comment by polynamaude** [comment]
@MKDan Eclipse is one of the best but the learning curve can be impressive. But it has a very nice auto-complete and so does VSCode. For Komodo, it's closer to a editor and somewhat prefered by some user. But it's not as productive for project, for example doing direct code validation other than syntax coloring.

**Comment by Undefined-Variables** [comment]
Oh okay maybe that is why it gives off the impression of not being quite complete!

**Comment by Undefined-Variables** [comment]
> @MKDan Eclipse is one of the best but the learning curve can be impressive. But it has a very nice auto-complete and so does VSCode. For Komodo, it's closer to a editor and somewhat prefered by some user. But it's not as productive for project, for example doing direct code validation other than syntax coloring.

I do 95% of code validation in my head as I write the code.

**Comment by polynamaude** [comment]
@Undefined-Variables 
I doubt that you have in your head all the reference to all the library...
That you know all the reference to the phpDoc and such....

That's what's called validation... not syntax checking.

**Comment by Undefined-Variables** [comment]
No but I know what I need to know and if I get stuck I check the manual. I only have to check the manual once on any given thing and I remember it. I have a very good memory.

**Comment by polynamaude** [comment]
@Undefined-Variables Why do you think there's some type hinting in the source code...

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/5f8c9c75c07d70ca10c520e1c62e1944e3cdfdb5/_protected/app/system/core/classes/AdminCore.php#L44

For example...

That's what's called validation when you IDE checks those...

**Comment by Undefined-Variables** [comment]
I don't use the hints, I have removed all comments.

**Comment by polynamaude** [comment]
@Undefined-Variables I'm not talking about the syntax of the language... that part, we mostly all have it...that's in the manual. I'm talking about parameters for the functions, classes, return value...

**Comment by Undefined-Variables** [comment]
I have a great memory :/

**Comment by polynamaude** [comment]
@Undefined-Variables That's pretty stupid...
Because that's what make a one-man think of his belly button. How do other people know your code... When you write something it's not only for you, it's mostly for other to be able to update in the long term.

And that's also why there's way of doing things that you learn in class...

Stop saying that you have good memory, I read it once... it's like you are trying to convince yourself somewhere...

Anyway, you'll need to use phpDoc the day you'll want to publish code in projects... Be it Doxygen for C/C++, javadoc for Java, etc...

The way you say it is like if everyone else's dumb... You think we developed those system because we don't have good memory...

You may think you have good memory, but I can easily recount time and time where you said you forgot something in our discussion.

**Comment by polynamaude** [comment]
@Undefined-Variables First thing you learn in Algorithm class is that neat code is commented code...

If you want a nice reason why we put comment in code... you can read this...

https://en.wikipedia.org/wiki/Therac-25

People died because of missing comments (yeah, dead people, like in not living anymore, like gone to heaven or hell)...

**Comment by Undefined-Variables** [comment]
No that is not what I mean, I have always been able to read something once and recall it. I am not saying im better than anyone else cos there are things I am not good at but being able to remember things is something I am. I have not gotten into deep with java yet I've only just done the hello world make your first app with java! I have a long road ahead with java.

**Comment by MKDan** [comment]
I'm just trying this at the moment - https://learn.grasshopper.app/

**Comment by polynamaude** [comment]
@Undefined-Variables I'm not talking about Java or any particular language. I'm talking about commenting your code.

You have the ability to easily understand this code even if you didn't write it. Why ? Because of comments. So same apply to the code you write...

**Comment by Undefined-Variables** [comment]
> @Undefined-Variables First thing you learn in Algorithm class is that neat code is commented code...
> 
> If you want a nice reason why we put comment in code... you can read this...
> 
> https://en.wikipedia.org/wiki/Therac-25
> 
> People died because of missing comments (yeah, dead people, like in not living anymore, like gone to heaven or hell)...

W"hen you have life's in your hands yes I see that but I'm talking about software that only I read and edit if someone else was involved I would leave comments for them for sure

**Comment by Undefined-Variables** [comment]
Maybe you are right, you have been taught the correct way, I figured most things out by myself.

**Comment by polynamaude** [comment]
@Undefined-Variables It's not a thing about being taught right, it's about taking the time to learn things...

Like you said, oh my god, gonna waste a couple of weeks learning a real IDE so I stay with my text editor. Never had in mind that on the long term the week it take to learn to use a real IDE will pay back in productivity ?

Same goes for all things to learn... There's plenty of books teaching how to do algorithm programming and you can even learn it on Udemy.... they currently have a promo with 85% off... Paying a 20$ for a 200$ class or so...

**Comment by polynamaude** [comment]
@Undefined-Variables It's not a thing of having life in your hands. It's something about being able to read it back. Like everyone you forget stuff and one day you'll ask yourself how you did some of the code. For now, it's easy... that all quite simple coding...But when you'll have 20 level of looping and exception calling of different type, etc then you'll understand why I'm saying this...

Or simply in some years when you'll find a bug that goes back to what you wrote now... And you haven't played with this for a while... You'll regret...
Or simply if you need to ask someone for help ;-)

**Comment by Undefined-Variables** [comment]
@polynamaude I agree completely but you can only work with what you have available to you. I would give my left leg to be able to study this properly. I have looked in to it and university fees are £60,000 that is not within my reach!

I have total respect for those who have done this the right way... Honestly

**Comment by Undefined-Variables** [comment]
> @Undefined-Variables It's not a thing of having life in your hands. It's something about being able to read it back. Like everyone you forget stuff and one day you'll ask yourself how you did some of the code. For now, it's easy... that all quite simple coding...But when you'll have 20 level of looping and exception calling of different type, etc then you'll understand why I'm saying this...
> 
> Or simply in some years when you'll find a bug that goes back to what you wrote now... And you haven't played with this for a while... You'll regret...
> Or simply if you need to ask someone for help ;-)

Point taken.

**Comment by polynamaude** [comment]
@Undefined-Variables You can learn those thing with doing a University degree... I've just gave you a nice start...

**Comment by Undefined-Variables** [comment]
I am learning Phpstorm btw...

**Comment by polynamaude** [comment]
@Undefined-Variables Why'd you said you didn't like it?

**Comment by Undefined-Variables** [comment]
I didn't say I didnt like it, I said I found it hard to navigate and it slowed me down but this is only due to lack of knowing it. I can see some of the benefits already but I like to be productive and learning a new IDE is a delay in that productivity. 

How do I set up a server via ftp for example.... Will take time to learn is all.

**Comment by polynamaude** [comment]
Look on YouTube you'll find plenty of Video.
It's not a delay in productivity. It's optimising productivity. What's the use of doing something wrong now when you can do it good later... I doubt that you have stock holder pushing you or some real imperative, other than your desire to see result...It's nice to see result now but the real one need investment...And that's the first thing you learn when you go to college.

**Comment by Undefined-Variables** [comment]
That makes a lot of sense.

**Comment by polynamaude** [comment]
@Undefined-Variables Go out and get the "ADA Lovelace" tutorial. Install a distribution with GPS... (Ubuntu has it and so does Windows from the Ada Core Technology).
You'll learn a great deal of the good basis of programming, how to structure code and algorithm.

**Comment by Undefined-Variables** [comment]
Love how you can browse/edit DB in this to be fair! Makes life easier.

**Comment by polynamaude** [comment]
@Undefined-Variables Same goes on with Eclipse with the Database Development Tools.

**Comment by Undefined-Variables** [comment]
Can you try and explain javascript:void(0) to me? Is it because of a keyword in javascript?

**Comment by polynamaude** [comment]
@Undefined-Variables I'd probably need more info than what you just gave me so I can answer...
But has the way the code is placed inside this repo, you probably need to tweak validation a bit or you'll get many errors...

**Comment by polynamaude** [comment]
https://stackoverflow.com/questions/1291942/what-does-javascriptvoid0-mean

**Comment by Undefined-Variables** [comment]
Thank you.

**Comment by polynamaude** [comment]
@Undefined-Variables Can also be a form of injection when you don't sanitize correctly. For example by asking user a URL and the person give you javascript: then they may get code executed.

**Comment by Undefined-Variables** [comment]
Yes that is what I ment, undefined is a keyword in javascript. so void is used instead...

**Comment by Undefined-Variables** [comment]
So why is it used here
````
    <a href="javascript:void(0)" onclick="Messenger.chatWith(\'' . $oUserModel->getUsername($iProfileId) . '\')">Click</a>

**Comment by Undefined-Variables** [comment]
Everyone has there own view this is what confuses me...

> 428

In addition to the technical answer, javascript:void means the author is Doing It Wrong.

There is no good reason to use a javascript: pseudo-URL(*). In practice it will cause confusion or errors should anyone try things like ‘bookmark link’, ‘open link in a new tab’, and so on. This happens quite a lot now people have got used to middle-click-for-new-tab: it looks like a link, you want to read it in a new tab, but it turns out to be not a real link at all, and gives unwanted results like a blank page or a JS error when middle-clicked.

<a href="#"> is a common alternative which might arguably be less bad. However you must remember to return false from your onclick event handler to prevent the link being followed and scrolling up to the top of the page.

In some cases there may be an actual useful place to point the link to. For example if you have a control you can click on that opens up a previously-hidden <div id="foo">, it makes some sense to use <a href="#foo"> to link to it. Or if there is a non-JavaScript way of doing the same thing (for example, ‘thispage.php?show=foo’ that sets foo visible to begin with), you can link to that.

Otherwise, if a link points only to some script, it is not really a link and should not be marked up as such. The usual approach would be to add the onclick to a <span>, <div>, or an <a> without an href and style it in some way to make it clear you can click on it. This is what StackOverflow [did at the time of writing; now it uses href="#"].

The disadvantage of this is that you lose keyboard control, since you can't tab onto a span/div/bare-a or activate it with space. Whether this is actually a disadvantage depends on what sort of action the element is intended to take. You can, with some effort, attempt to mimic the keyboard interactability by adding a tabIndex to the element, and listening for a Space keypress. But it's never going to 100% reproduce the real browser behaviour, not least because different browsers can respond to the keyboard differently (not to mention non-visual browsers).

If you really want an element that isn't a link but which can be activated as normal by mouse or keyboard, what you want is a <button type="button"> (or <input type="button"> is just as good, for simple textual contents). You can always use CSS to restyle it so it looks more like a link than a button, if you want. But since it behaves like a button, that's how really you should mark it up.

(*: in site authoring, anyway. Obviously they are useful for bookmarklets. javascript: pseudo-URLs are a conceptual bizarreness: a locator that doesn't point to a location, but instead calls active code inside the current location. They have caused massive security problems for both browsers and webapps, and should never have been invented by Netscape.)

**Comment by polynamaude** [comment]
@Undefined-Variables Stop making link everywhere when someone say something unless you understand it...

I didn't say that everywhere it's written it's an injection... Go read the OWASP documents and you'll see what's XSS and JS injection...

This code stimply says that the target off the link go nowhere bt when someone click on the link, you call the JS object **_Messenger.chatWith_** (chatWith being the function of the preceeding object). Passing as parameter the variable _**$oUserModel->getUsername($iProfileId)**_

**Comment by Undefined-Variables** [comment]
> @Undefined-Variables Stop making link everywhere when someone say something unless you understand it...
> 
> I didn't say that everywhere it's written it's an injection... Go read the OWASP documents and you'll see what's XSS and JS injection...
> 
> This code stimply says that the target off the link go nowhere bt when someone click on the link, you call the JS object **_Messenger.chatWith_** (chatWith being the function of the preceeding object). Passing as parameter the variable _**$oUserModel->getUsername($iProfileId)**_

Oh I see, I thought I understood it but then I read something else and it confused me, thank you for explaining,.

**Comment by polynamaude** [comment]
@Undefined-Variables There's more than a handful of things wrong with this software...Starting by the backlinking... (writing your own domain name everywhere in the code so that it shows on the person who install your software). That's called back linking and if you do so, you either have to write it upfront or it's somewhat not ethic.

But no using javascript:void(0) is not a good way of doing it... it's like writing **print (NULL);**

**Comment by Undefined-Variables** [comment]
I see. Thank you

**Comment by polynamaude** [comment]
@Undefined-Variables It's like creating a dating site to pick up girls phone number... it's not a thing to do...
Or if you prefer like going to the bank asking a loan to buy a gun to go do a hold-up in a bank....

**Comment by Undefined-Variables** [comment]
Yeah I understand. I have removed most of the "back links" and left a single mention of the author in the header. It was everywhere!!!

**Comment by polynamaude** [comment]
@Undefined-Variables Well that's pretty bad to do (backlinking)...
You can get your extension removed and account banned if you do so on Joomla Extension Directory (JED).

Oh, your friend asked you a question about DOB... I think I answered him what you meant but he didn't understand what you said...

**Comment by Undefined-Variables** [comment]
OMG!

**Comment by pH-7** [comment]
Hey @MKDan! Sorry for my late reply. Just say it.

> How to change example.com/meet-people to example.com/my-seo-text

You can change easily that URL in _protected/app/configs/routes/en.xml 
<small>(note: if you have different XML route files in there, due to other languages, please edit the appropriate one).</small>

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/c0c3a46049bbcdfaec4adf87b8d03916e380ada4/_protected/app/configs/routes/en.xml#L25

Just change `meet-people` to the path you want :)

Then, clear the "Database and Other Data" cache. https://ph7cms.com/doc/en/how-to-clear-caches 

<img width="950" alt="how-to-clear-caches" src="https://user-images.githubusercontent.com/1325411/79682997-61cdf380-8216-11ea-88d5-b66cc3b12bca.png">

**Comment by MKDan** [comment]
> Hey @MKDan! Sorry for my late reply. Just say it.
> 
> > How to change example.com/meet-people to example.com/my-seo-text
> 
> You can change easily that URL in **_protected/app/configs/routes/en.xml**
> _(note: if you have different XML route files in there, due to other languages, please edit the appropriate one. e.g., fr.xml. de.xml, ...)._
> 
> https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/c0c3a46049bbcdfaec4adf87b8d03916e380ada4/_protected/app/configs/routes/en.xml#L25
> 
> Just change `meet-people` to the path you want :)
> 
> Then, clear the "Database and Other Data" cache => https://ph7cms.com/doc/en/how-to-clear-caches
> 
> <img alt="how-to-clear-caches" width="950" src="https://user-images.githubusercontent.com/1325411/79682997-61cdf380-8216-11ea-88d5-b66cc3b12bca.png">

Thank you so much!
I'll try it out.

**Comment by MKDan** [comment]
> "File Manager" and phpMyAdmin

GitHub Community Guidelines:-

**Respect each other**. Nothing sabotages healthy conversation like rudeness. Be civil and professional, and don’t post anything that a reasonable person would consider offensive, abusive, or hate speech. Don’t harass or grief anyone. Treat each other with dignity and consideration in all interactions.

You may wish to respond to something by disagreeing with it. That’s fine. But remember to criticize ideas, not people. Avoid name-calling, ad hominem attacks, responding to a post’s tone instead of its actual content, and knee-jerk contradiction. Instead, provide reasoned counter-arguments that improve the conversation.

**Comment by Undefined-Variables** [comment]
I like that :) I have had my own fair share of ups and downs with the delightful @polynamaude over my time here but the more I have gotten to know her I can now see the manor in which she can come across is not deliberately done! She’s just tells you the truth with no filter!

**Comment by MKDan** [comment]
> @Undefined-Variables You laughing out loud ? Don't make too much noise...
> And don't invite friend over... that's an offense in the kindom of the Queen as there's virus spreading around...

@Undefined-Variables One can possess very high knowledge but treating others like trash doesn't take them anywhere.

**Comment by polynamaude** [comment]
@MKDan As you seem too sensitive to what I say then I'll just ignore you and do like most would do. Don't tell you what's wrong because you ain't worth accepting critics.

Being off topic, asking question on the wrong thread, etc are all things that get you ignored or ban on most developer forums. If you didn't get it yet that the more time I waste with silly talk, the less I have left for real stuff.

For sure at usual hourly rate, I'll listen to all bullshit and even answer you long sentence. If you can find one thing false in what I say then I'll correct it. We choose people who think like us and go away from those who don't. Be it right wing or left wing, Republican or Democrats, Eurosceptic  or Eurocentric. And we loose the ability to ask ourself what can we learn.

Maybe you shall be as good reading Github policies as doing a RTFM on pH7CMS....

**Comment by Undefined-Variables** [comment]
I’m also happy to listen to bullshit and answer in long sentences for an hourly rate.... Oh wait I already do this out of kindness! Unfortunately sometimes the truth is hard to hear but you need to hear it to better yourself! Not every person you meet will mummy cuddle your feelings

**Comment by polynamaude** [comment]
@Undefined-Variables You can always find a girl that will do so on a hourly rate but you'll have to travel to the red light district and you'd better wear a condom. You'll get pretty akward mummy affection as you need there....You can get pretty much anything for hourly rate, you'll always find someone who satisfy your need. And even robots nowadays !

**Comment by polynamaude** [comment]
@Undefined-Variables Can't you create a test instance out of cPanel?

**Comment by polynamaude** [comment]
@Undefined-Variables I don't use cPanel....feel like Softaculous for me.

**Comment by Undefined-Variables** [comment]
I don’t use it I do everything via ssh with putty but my business partner needs it!

**Comment by Undefined-Variables** [comment]
I bet I could use an instance I installed node.js and reacts dev server runs okay!

**Comment by MKDan** [comment]
> @MKDan As you seem too sensitive to what I say then I'll just ignore you and do like most would do. Don't tell you what's wrong because you ain't worth accepting critics.
> 
> Being off topic, asking question on the wrong thread, etc are all things that get you ignored or ban on most developer forums. If you didn't get it yet that the more time I waste with silly talk, the less I have left for real stuff.
> 
> For sure at usual hourly rate, I'll listen to all bullshit and even answer you long sentence. If you can find one thing false in what I say then I'll correct it. We choose people who think like us and go away from those who don't. Be it right wing or left wing, Republican or Democrats, Eurosceptic or Eurocentric. And we loose the ability to ask ourself what can we learn.
> 
> Maybe you shall be as good reading Github policies as doing a RTFM on pH7CMS....

I'm not banned anywhere. So, are you on-topic here? At least I take about the issue/project related.

**Comment by polynamaude** [comment]
@MKDan Great question you asked there ! Maybe you shall be opening a new issue on the subject...

What you didn't seem to get is that you came here asking for help... No one's forcing your hand. In case you didn't notice, there's a minima of knowledge to be able to do something useful for this software. If you didn't like the way the information got served to you then I can't do much about it...
I think @Undefined-Variables described it in a nice way. There won't always be people to nurture around so it's a give and take.

If you ain't smart enough to take a deep breath and why you've got such answer then I'll give a one-shot hint...

[How to ask for Help](https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help)

**Comment by MKDan** [comment]
> I bet I could use an instance I installed node.js and reacts dev server runs okay!

AngularJS vs ReactJS vs NodeJS: Which is best to learn in 2020?

**Comment by polynamaude** [comment]
@MKDan There's no such answer... depend for what...

Also, you shall do some research on Google because you can surely compare AngularJS and ReactJS (and VueJS). But it can't be compared to NodeJS.

NodeJS is a Javascriopt-based web server used to serve application written in JS. So you can write server side application in JS. The goal being the simplicity of having the same language for both front-end and back-end. Also, NodeJS is very fast for serving IO-based application (like database query for example).

The two other are front-end JS framework...

**Comment by polynamaude** [comment]
@MKDan Here's some starting point to look...

https://medium.com/unicorn-supplies/angular-vs-react-vs-vue-a-2017-comparison-c5c52d620176

https://reactjs.org/tutorial/tutorial.html

https://www.valentinog.com/blog/react-webpack-babel/

https://hackernoon.com/how-to-build-a-react-project-from-scratch-using-webpack-4-and-babel-56d4a26afd32

https://github.com/facebook/draft-js

**Comment by polynamaude** [comment]
@MKDan If you are starting to learn (and it seems like it) then I'd go with Vue.JS as it's a more progressive framework. That is you can use only part of it and it's pretty easy to lean. It's lightweight (around 20kb). AngularJS require the use of TypeScript, that's not bad in itself but that will be something else to learn. It can be good because it integrate a real typing system into Javascript. That is that variable have type (integer, string, etc).

Again, like I was saying to UV, there's a hard lesson to respect in the learning curve. You can surely end up writting a ReactJS application in one afternoon but in the end there's some stuff that you'll have passed by in your learning. So later on when bugs show off you'll have a hard time finding them and understanding why.

It can seem time-consuming and useless to do tutorials that seem for beginner when we may already know most of it. But there's subtility that can show off.

A simple example, most people don't know that if you precede a number by 0 in PHP it will make it octal based. So if someone enter 010 in you don't strip zero while treating your user input you can finish with some problem. Example with the number above, you may think it's gonna give you 10 but it gives 8 (0*8^0 + 1 * 8^1 + 0*8^3)...

And JS also does this in it's own way...

Those are small subtility of many language and it's why it's always better to do a rehearsal of what we already know !.

Hope this help a bit...

**Comment by MKDan** [comment]
@polynamaude Thank you I will try Vue.JS first
