### ISSUE TITLE
after login, page is refreshing itself can't browser users

### ISSUE THREAD

**Issue by LearnSpread** [pH7Software/pH7-Social-Dating-CMS#751]
I installed it today and logged in after creating a user but the page is refreshing itself and doesn't stay still to see the members profile. similar action is happening to photo, videos and forum tabs.

can someone suggest the solution for it.

Many thanks

**Comment by polynamaude** [comment]
@LearnSpread 

Start here...
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

**Comment by polynamaude** [comment]
@LearnSpread We ain't the almighty god above... How do you want to get helped if you don't say a word about what you have as system, what version you installed, etc...

Possibly sharing some logs would be a good start to !

**Comment by LearnSpread** [comment]
@polynamaude thank you for reply.
I'm using Opera browser windows 10, 
pH7 - version 15.3.0

**Comment by LearnSpread** [comment]
just tried opening the file in Google Chrome same issue.

**Comment by polynamaude** [comment]
@LearnSpread I think you are missing some thing around here...
Honestly, I don't really give any type of usefulness to the description of the browser you are using. It doesn't make any type of change to the CMS itself...

Maybe you shall go read a bit about the link I've wrote in the message above...

Also, maybe this product ain't the one meant for you... If you'd expect something working out of the box, without needing to know programming (real programming, not scripting) then maybe you'd be better looking at another solution...

**Comment by polynamaude** [comment]
@LearnSpread Do you have any knowledge of what the word client / server architectures means ? You are having problems with your server, why do you describe the client you are using ?

Also, it doesn't work very good on Windows. Like we wrote in the documentation, it's only usefulness would be to try some stuff around if you are lucky. Go ahead installing a Linux virtual box on your machine and then try it out.

**Comment by LearnSpread** [comment]
@polynamaude I disabled the:  Ajax Site with AjPH. Now it's working I appreciate your prompt answer. yes, I'm trying to see if it works for me.

**Comment by polynamaude** [comment]
@LearnSpread If I look at your profile, you've created an account on GitHub for the only purpouse of getting here for support. Thatt may not be the thing to do... It's not because you can download a software (and try to use it) that you've got the knowledge needed to get it work.

You can go out to the hardware store and buy many tools, it won't make you a carpenter, mechanic or electrician. Same apply to software...

It's a bit like not having knowledge on programming and saying that Symfony CMS is useless but not knowing much programming...

Anyway, take the time to read around because it ain't a general support for all your problems and we won't be taking you by the hand.

**Comment by polynamaude** [comment]
@LearnSpread Just like that, like another user who does support like to say "Issues are like door, when you are finished, you close them". So it's somewhat the basic to close it...

**Comment by LearnSpread** [comment]
@polynamaude Thank You:)
