### ISSUE TITLE
Warning bad programming method - back linking

### ISSUE THREAD

**Issue by polynamaude** [pH7Software/pH7-Social-Dating-CMS#781]
**Describe the bug**
Someone having a over-sized ego put plenty of back-link and call to his own server in this software.
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/0ca67c22a2053f99ecd9a61f67e1f1bc55fb13ea/static/js/cookie_consent/eu-states.js#L6

Why write a call to your own server that just serve the latest version of a software from CND ?
Want to get usage stats ? Do it the proper way.
That's mostly like creating a dating site to sniff girls phone number : BAD
There's a name for this : Stalker
No excuse for lack of time.

DO I GO FORWARD AND TALK ABOUT GHOST USERS AND SUCH?

(a clear and concise description of what the bug is.)

**To Reproduce**

**Expected Behavior**
DONT DO THIS
(a clear and concise description of what you expected to happen.)

**Screenshots / Screencasts**

(if applicable, add screenshots or screencast the scenario to help explain your issue the best you can.)
FELT LIKE GETTING FUCK BACKWARD WITHOUT LUBE

**Comment by polynamaude** [comment]
![Screenshot from 2020-05-31 09-49-00](https://user-images.githubusercontent.com/21186871/83353964-1eda6200-a324-11ea-82c0-ae3a931e20fa.png)

This is what we get from eustate.js
`document.write('<script src="https://cdn.jsdelivr.net/cookie-bar/1/cookiebar-latest.js"></script>');`

**Comment by Undefined-Variables** [comment]
I kind of see your point and would like to hear the thinking behind this was...

Its same for the adult warning bar. This has a deliberate link to a porn site...

**Comment by Undefined-Variables** [comment]
We are going to have the Ghost talk at some point in the future because in my head this is starting make me question a few things... 

First real alarm bell was the script that screams home announcing every new install, then there is the dead user I have seen come to life, that in theory could be used to login to any one of those installed sites.

The same URL is automatically included in the config.ini under

````
[ph7cms.api]
private_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

allow_domains[] = "ph7cms.com"
````

You are warned never to change the key. but id advice replacing this api key that controls access to private user data is the first thing you should do after installation. Also a user who was to change the chat from the default and didn't think or even know he has to remove the allow_domains comment above then he has left his server with the front door wide open! 

The out of date jquery library that will cut conversation instantly dead if asked about was odd! Lots of old dependencies used with composer (a tool invented to keep these up to date doesn't make much sense either! 

I advice people to change api-key, set a new password on userId = 1 and alter the email address too just for there own peace of mind! There is so much more now I think about it! 

@pH-7 Please explain yourself.

**Comment by pH-7** [comment]
Hey @polynamaude & @Undefined-Variables 

Great questions! 😊


- Concerning the ghost user, it's like the Ghost user on GitHub user. It will be used when a user removed its account, the forum posts, or other contents like comments left by that user will be changed to the "ghost" user. The ghost user is unusable. And beside of that, it has a random password, so it's impossible for anyone to know the ghost password. https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_Core.sql#L161

- If you use the API offered by the software (e.g. to build native apps; https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-To-Use-the-RESTful-API-and-Add-new-Endpoints), the API key is auto-generated for each installation
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/dc9b5ffffc560d89d0631de61eab4c345e9dbe5d/_install/data/configs/config.ini#L119

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/2bd215a7a00d49a8cc33264a5e92dfbc288e8def/_install/controllers/InstallController.php#L238

**Comment by pH-7** [comment]
@Undefined-Variables What composer outdated dependencies are they? Would you mind to open a PR for this?

**Comment by pH-7** [comment]
Concerning the jQuery version, there were some incompatibilities from other JS libraries that weren't working correctly with the newer jQuery version. The plan in the future would be to get rid of jQuery and just use vanilla JS (but that's a huge work!)

**Comment by pH-7** [comment]
>>  that will cut conversation instantly dead if asked about was odd! 

What do you mean? I'm not sure to understnad that one.

**Comment by pH-7** [comment]
>> the script that screams home announcing every new install, 
Sorry about it, but I'm also not sure to get that line... Can you clarify it? :)

**Comment by Undefined-Variables** [comment]
Hey @pH-7 Firstly thank you for the explanation. Sorry but you have to ask these questions sometimes. 

I understand what you are saying about the automation of the api_key but how do two applications set valid tokens for each other and share them having never being connected? I use the api for many things but the PWA is just as usable. Its a pleasure to use and feels like app store native installed app. 

What I mean by screaming home  is the amount of calls to ph7cms.com being done. 

News feed, js cookie banner, adult content banner with pop up porn site ready and waiting.... 
What I don't understand is why eu-states.js does this...
````
    document.write('<script src="//ph7cms.com/addons/cookieconsent/eustates.js"></script>');

````

This is a call to your server from the hosing server to get this script but when you get to the URL you get this...

````
    document.write('<script src="https://cdn.jsdelivr.net/cookie-bar/1/cookiebar-latest.js"></script>');
    
````

This is another redirect to a 3rd party script that could have been called the first time so what is the reason for the first redirect no going direct... What was the reason for landing on your server first?

Yes I will PR for outdated dependances.

**Comment by pH-7** [comment]
> News feed, js cookie banner, adult content banner with pop up porn site ready and waiting....
> What I don't understand is why eu-states.js does this...

Cookie consent banner will only be called if enabled from the admin dashboard (General settings).
Same for the adult disclaimer. 

The reason that the CMS was getting the EU consent banner from pH7CMS domain name is that it used to be part of an 'addon'. And my plan was to build a "housemade" banner which would be also available without the software, available at addons.ph7cms.com. However, this isn't the case.

I fixed the issue mentioned https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/f902a00f475cfa3a651a1cf0db05ba3d4e1c89d0 

Concerning the adult disclaimer, I'm currently looking for an open source library that does pretty much the same as the current third-party does. And I will also remove the call to pH7CMS's Addons URL. If you know a nice and open source adult disclaimer JS library, I will be really happy to make the replacement.
 

> I understand what you are saying about the automation of the api_key but how do two applications set valid tokens for each other and share them having never being connected? I use the api for many things but the PWA is just as usable. Its a pleasure to use and feels like app store native installed app.

By default, the API module isn't used. If you or a third-party developer build an external application (such as a mobile app), he will need to ask you the private API key you can see from your config.ini file and share will him in order to be able to use the api module.

If you build another program or app that has also to use your API, it will also have to know your unique api key in order to get access to the API.

I'm not sure if I was clear on that one. But hopefully, you understand 😃 Doc page that can also help you to see clearer: https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-To-Use-the-RESTful-API-and-Add-new-Endpoints

 > Yes I will PR for outdated dependances.

Awesome! I really appreciate it!!

**Comment by Undefined-Variables** [comment]
Cookie bar...
    https://github.com/ketanmistry/ihavecookies

Age-Verification 
    https://drive.google.com/file/d/16LCnYtkJUIShNDQhnYo5SYQ820SPN31Q/view?usp=sharing

cookie.js is required
    https://github.com/js-cookie/js-cookie

And odiously jquery with I have updated on my development server and not seen any issues yet but I will let you know if it works out if not I will fix the problems and upgrade it. 

The excuse  "It wasn't upgraded due to it having incompatibilities is not good enough... Its a developers job to solve this issues. The old version has 8 known xss vulnerabilities and this is live published software...

I have upgraded font-awesome too also no problems just changed a few icons.

**Comment by Undefined-Variables** [comment]
> I'm not sure if I was clear on that one. But hopefully, you understand 😃 Doc page that can also help you to see clearer: https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-To-Use-the-RESTful-API-and-Add-new-Endpoints

Yes I use the API for many reasons and have a good understanding regarding API's. It works like a dream. Makes so much possible too. 

> By default, the API module isn't used. If you or a third-party developer build an external application (such as a mobile app), he will need to ask you the private API key you can see from your config.ini file and share will him in order to be able to use the api module.

So it makes no difference if its changed. Sorry sounded like you were saying they are automatically shared. That would odiously not be secure! 

> The reason that the CMS was getting the EU consent banner from pH7CMS domain name is that it used to be part of an 'addon'. And my plan was to build a "housemade" banner which would be also available without the software, available at addons.ph7cms.com. However, this isn't the case. I fixed this at: f902a00

Yeah okay this checks out but you can see how this looks and security is everyone's concern, we all rely on it and voicing concerns you have is and should be seen as a proactive approch. 

> Concerning the adult disclaimer, I totally agree with you. The current one isn't perect at all.
I'm currently looking for an open source library that does pretty much the same as the current third-party one. And I will also remove the call to pH7CMS's Addons URL. If you know a nice and open source adult disclaimer JS library (it has to be responsive too), I will be really happy to make the replacement.
Otherwise, I will create one from scratch.

I have given you a few links in post above, the age-verification is clean simple and uses jquery, I have used it on a couple of sites and it is spot on. I have also written my own but lost is when a HDD failed. The cookie consent is highly customisable and covers all the required aspects for the EU law. 



Can I ask why it says do not remove ghost user without your permission? I have removed it and return an error if the user is banned, deleted, got privacy settings to ME and this works just as well. 

Sorry I jumpped to that conclusion!

**Comment by pH-7** [comment]
Hey @Undefined-Variables!


I understand you were worried about the depreciated jQuery version and its vulnerabilities. I was focusing on different aspects of the software. I’m glad you brought this back! If this is working for you, when you will open your PR, I will be glad to QA those modifications and merge them. 
Although those vulnerabilities look scary, there is nothing to be worried about here. pH7Builder doesn’t use many features from jQuery and there are no vulnerabilities with what the software uses from the library :)

Concerning the ghost user, the software uses it in different modules, and it might break things if you remove it. In other words, the user is part of the core software. That why it says to inexperienced users to keep it. That user is locked and cannot be used. 
Now, if you don’t like it and want to remove it, feel free to do it! The software is made to be modified and changed as you want in order to reflect your own taste. But it’s always at your risk and peril (especially for those without programming knowledge).


Concerning the adult notice disclaimer, yesterday I made two mockups and I will now code them. They are much nicer and modern than the current one.
I would also love to hear your feedback. See them below. How do you like them?


![pH7Builder-Adult-Disclaimer-Mockup](https://user-images.githubusercontent.com/1325411/83739931-bbaf3f00-a645-11ea-8158-da95f08133cb.png)

![pH7Builder-new-adult-disclaimer-mockup](https://user-images.githubusercontent.com/1325411/83739926-b94ce500-a645-11ea-81ee-c92a7c9d4221.png)

**Comment by Undefined-Variables** [comment]
@pH-7 I know what you are saying with the user being deeply rooted in to the software. Removal is not a simple task and took days! 

Yeah the age content warning is absolutly perfect, looks nice, simple to use and most importantly its clean and not linking to dodgy porn sites. 

Can I ask you about the activity wall? Have you finished it in the latest release? I seem to have all the files for it even forms and ajax controller but cant get it to accept the input from the form if its displayed on the wall. User comments are displayed but I get 500 error on subbitting. Now this is not my first day and I have everything correct its just not liking something.

**Comment by Undefined-Variables** [comment]
You may wish to include an option for age 21 for the states.

**Comment by polynamaude** [comment]
@pH-7 You may add an option to remind guys that trust is the most important thing in a relationship so it's NOT OKAY to dig into your user base to date a girl. It's the same as putting your dick into a customer when you're a gynecologist. There's enough girl on this planet, go look somewhere else....
Like that, just a little hint...

**Comment by Undefined-Variables** [comment]
@pH-7 Dont worry I have worked out your intentions with the wall :) 

Great stuff!
