### ISSUE TITLE
Site redirect to other site on mobile device.

### ISSUE THREAD

**Issue by Luke67** [pH7Software/pH7-Social-Dating-CMS#787]
Site redirects to adult site when i open site on mobile device. 
When entering url site redirects without the 18+ warning to adult site. On multiple devies mobile and or laptops. But not the one I installed the site on.
Is it cause its a adult dating site?

**Comment by pH-7** [comment]
Hi @Luke67 
Thanks for your message!

It seems you enabled the Adult Disclaimer (which is disabled by default). At the moment, the software uses a third-party service to provide the disclaimer, and it may give some kind of adult ads/redirection, **as mentioned in the Settings Page**.

<img width="950" alt="screen_shot_2018-07-30_at_4_07_51_pm" src="https://user-images.githubusercontent.com/1325411/43402450-0b5edb38-9413-11e8-9b02-e498fe94d963.png">

Right now, to solve this problem, you can  keep it disabled, and use another Adult Disclaimer of your choice by adding its javascript code through Admin Panel -> Settings -> JavaScript

I hope it helps. And really sorry for any inconveniences

**Comment by pH-7** [comment]
I know that this is not good, and can be very annoying. 
Because of this, I already created a brand new disclaimer from scratch https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/782 which will replace the third-party one. It will be available in v16. From then, you won't longer have this kind of very annoying redirections.

**Comment by Luke67** [comment]
Wow you are wonderful Thanks a lot!
