### ISSUE TITLE
Cannot Change Theme

### ISSUE THREAD

**Issue by SpaceGray-AI** [pH7Software/pH7-Social-Dating-CMS#811]
Can i change the theme on the ph7cms sofeware to a different one other that the ones that the ph7cms software comes with (Datelove, Zendate, Base, Cartoon). If it can be changed how do i do it?
Thanks in advance

**Comment by Undefined-Variables** [comment]
That is all there is. If you want something unique you will have to create it yourself.

This is easiest done by copying Base folder from templates/themes/base rename it then upload it to the same directory.

Base has all the code in it the others are just linked back to base. Once you do this you can select your new theme and start modifying it!

**Comment by polynamaude** [comment]
@Undefined-Variables What ? I need to do something myself ? Are you crazy ! ? I was expecting to have my own custom theme without any work.

**Comment by Undefined-Variables** [comment]
@polynamaude I can explain the basics for the right $incentive lol!

**Comment by pH-7** [comment]
> Can i change the theme on the ph7cms sofeware to a different one other that the ones that the ph7cms software comes with (Datelove, Zendate, Base, Cartoon). If it can be changed how do i do it?
> Thanks in advance

Like what @Undefined-Variables says, I suggest you to use "datelove" as a new skeleton theme, rename the folder name to a new theme name, the add your own rewritten CSS styles in `css/_inc/common.custom.css`

"Datelove", "Zendate", and "Cartoon" rely on the "Base" theme, but extend new customed styles. It allows you to create a new theme with just some little changes since everything else will depend on "base" theme.
