### ISSUE TITLE
select by country, region, city

### ISSUE THREAD

**Issue by excalibur-web** [pH7Software/pH7-Social-Dating-CMS#836]
Hello Pierre-Henry

let's make together select by country, region, city and autocomplete when typing,
for one country or several

**Comment by polynamaude** [comment]
@excalibur-web Your hope are too high.
Look at the other person who wrote code and made Pull Request. It all went stale...

The only thing you might get is that PH is gonna complain about your code and let you write all by yourself !

There's a bug that happens when you reach 2000 or so user. It's related to the use of unsigned field in the database.  Me (I finally decided to let go and do something else, plus another user who's a good developer. We both wanted to fix it but we asked some guidance as maybe he had a reason to use unsigned. We never got a answer)...

https://github.com/pH7Software/pH7-Social-Dating-CMS/pulls

https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/793

Don't waste your time. You've got better to do ;-)

https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/830
