### ISSUE TITLE
Admin page doesn't exist

### ISSUE THREAD

**Issue by Fulgencio12** [pH7Software/pH7-Social-Dating-CMS#838]
![Screenshot_3](https://user-images.githubusercontent.com/74460126/99149744-433ab880-2690-11eb-8268-43e6a8c5905f.png)
![Screenshot_4](https://user-images.githubusercontent.com/74460126/99149746-43d34f00-2690-11eb-9206-7d3986124a2c.png)

**Comment by Fulgencio12** [comment]
Forgot to mention, I got the CMS from github, just downloaded it, but after I finished the installation it told me to download the CMS from sourceforge, so I did. After installing it the second time(The one from sourceforge) the CSS isn't working and there is no admin123 folder in the server.

**Comment by polynamaude** [comment]
@Fulgencio12 Have you took the time to read the docs ?
Have you configurer the protected folder ?
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki
http://ph7cms.com/doc/

No there's no _admin123_ folder because we use **mod_rewrite**.

Maybe if you just did the basic installation procedure before expecting magic to happens.

Have you looked at the file **installation-instructions** ????

**Comment by polynamaude** [comment]
@Fulgencio12 And let me guess... Didn't looked at _README2.TXT_ and didn't configure the _htaccess_ file ?

**Comment by polynamaude** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

**Comment by Fulgencio12** [comment]
Luv ya bruv, thanks for helpin, will check it out now.
