### ISSUE TITLE
Installation in PHP 8.0.1

### ISSUE THREAD

**Issue by nickotech2000** [pH7Software/pH7-Social-Dating-CMS#855]
Just download and try this software

I am trying to run in PHP 8.0.1 (latest), on IIS, Windows 10, FastCGI, etc..
When I try for the first time, there is error

Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)

**Expected Behavior**

Have no error for installation. Since I see the requirement can also run on WIndows, IIS, Fast CGI, and latest PHP 7.04 or higher.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/51929/108141652-179bf400-70ff-11eb-93ae-ef9c6a93db6b.png)

**Comment by polynamaude** [comment]
@nickotech2000 This software is full of unfixed bug, doesn't work on PHP 8 too,
Also, one of the bug is that it will crash randomly when you reach more than 1000 users.
Just looked at all the issues that got automatic closed...
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/830
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/803
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/795
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/793

**Comment by pH-7** [comment]
Patch https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/f34f8c9c6701e6234e9fca14104785cc0621c3c8
