### ISSUE TITLE
Web Cam not working

### ISSUE THREAD

**Issue by norspeed22** [pH7Software/pH7-Social-Dating-CMS#888]
Web Cam not working, any idea as to why ?

**Comment by pH-7** [comment]
Thanks for your comment!

What module are you related to?
If you are speaking about the "webcam" module, it has been discontinued and will be removed to the next version, because it isn't relevant anymore for 2021 (it was good for 2010 when it was released, but definitely "outdated" for 2020 and beyond).

**Comment by pH-7** [comment]
If you are pointing another module, please let me know 🙂 I may be wrong 😃

**Comment by norspeed22** [comment]
Hi.
Many thanks for that.

Also: Where can i find the file to change the pink backround ?

Regards.
Keith.

---
New Outlook Express and Windows Live Mail replacement - get it here:
https://www.oeclassic.com/







----- Original Message -----
From: ♚ PH⑦ de Soria™♛ ***@***.***>
Reply-To: pH7Software/pH7-Social-Dating-CMS 
***@***.***>
To: pH7Software/pH7-Social-Dating-CMS ***@***.***>
Cc: norspeed22 ***@***.***>, Author ***@***.***>
Sent: 13/07/2021 10:41:27
Subject: Re: [pH7Software/pH7-Social-Dating-CMS] Web Cam not working (#888)



Closed #888 via 1dde288.
